#ifndef NITMOD_ENTITY_IDS_H
#define NITMOD_ENTITY_IDS_H
/* Original entity types 0..55. 56..58 are reserved, events start at 59. */
static const int nitmodEntityTypes[] = {
		ET_GENERAL, ET_PLAYER, ET_ITEM, ET_MISSILE, ET_MOVER, ET_BEAM,
		ET_PORTAL, ET_SPEAKER, ET_PUSH_TRIGGER, ET_TELEPORT_TRIGGER,
		ET_INVISIBLE, ET_CONCUSSIVE_TRIGGER, ET_OID_TRIGGER, ET_EXPLOSIVE_INDICATOR,
		ET_EXPLOSIVE, ET_ALARMBOX, ET_CORONA, ET_TRAP, ET_GAMEMODEL, ET_FOOTLOCKER,
		ET_FLAMEBARREL, ET_FP_PARTS, ET_FIRE_COLUMN, ET_FIRE_COLUMN_SMOKE,
		ET_RAMJET, ET_FLAMETHROWER_CHUNK, ET_EXPLO_PART, ET_PROP, ET_AI_EFFECT,
		ET_CAMERA, ET_MOVERSCALED, ET_CONSTRUCTIBLE_INDICATOR, ET_CONSTRUCTIBLE,
		ET_CONSTRUCTIBLE_MARKER, ET_BOMB, ET_BEAM_2, ET_TANK_INDICATOR,
		ET_TANK_INDICATOR_DEAD, ET_CORPSE, ET_SMOKER, ET_TEMPHEAD, ET_MG42_BARREL,
		ET_TEMPLEGS, ET_TRIGGER_MULTIPLE, ET_TRIGGER_FLAGONLY, ET_TRIGGER_FLAGONLY_MULTIPLE,
		ET_GAMEMANAGER, ET_CABINET_H, ET_CABINET_A, ET_HEALER, ET_SUPPLIER,
		ET_LANDMINE_HINT, ET_ATTRACTOR_HINT, ET_SNIPER_HINT, ET_LANDMINESPOT_HINT,
		ET_COMMANDMAP_MARKER
	};
static int NITMOD_NativeEntityType(int original) {
    return original>=0 && original<(int)(sizeof(nitmodEntityTypes)/sizeof(nitmodEntityTypes[0]))?nitmodEntityTypes[original]:-1;
}
static int NITMOD_OriginalEntityType(int native) {
    int i;
    for(i=0;i<(int)(sizeof(nitmodEntityTypes)/sizeof(nitmodEntityTypes[0]));++i)
        if(nitmodEntityTypes[i]==native) return i;
    return -1;
}
#endif
