/* Original qagame SHA256 84a7e7958952f804d65fbe6db6b4758ea0cf6b596b26a514a68de0ba3bd9ef49.
 * g_shrubbot_cmds: ELF32 VA 0x2a3aa0, 78 entries, 20-byte stride. */
#ifndef NITMOD_ADMIN_COMMANDS_H
#define NITMOD_ADMIN_COMMANDS_H
typedef struct { const char *name,*description,*usage; } nitmodAdminCommandInfo_t;
static const nitmodAdminCommandInfo_t nitmodAdminCommands[] = {
    {"readconfig","Reloads levels and commands database files (levels.db and commands.db)",""},
    {"time","displays server's local time",""},
    {"setlevel","sets the admin level of a player","[name|slot#] [level]"},
    {"kick","kick a player with an optional reason","[name|slot#] (reason)"},
    {"ban","ban a player by IP NGUID and MAC Address with an optional expiration time (seconds) and reason","[name|slot#] (time) (reason)"},
    {"unban","unbans a player specified ban number as seen in ^2!showbans","[ban#]"},
    {"put","move a player to a specified team","[name|slot#] [r|b|s]"},
    {"pause","pauses the game for all players",""},
    {"unpause","unpauses the game if it had been paused by ^2!pause",""},
    {"listplayers","display a list of connected players, their slot numbers as well as their admin levels",""},
    {"records","display spree and frag records of the current map",""},
    {"mute","mutes a player","[name|slot#]"},
    {"unmute","unmutes a muted player","[name|slot#]"},
    {"showbans","display a (partial) list of active bans","(start at ban#) ((banner) (banner's name)) ((find) (banned player)) ((reason) (reason for ban))"},
    {"help","display commands available to you or help on a specific command","(command)"},
    {"gibme","Instagib yourself, funny alternative to /kill",""},
    {"admintest","display your current admin level",""},
    {"cancelvote","cancels the vote currently taking place",""},
    {"passvote","passes the vote currently taking place",""},
    {"spec999","moves 999 pingers to the spectator team",""},
    {"shuffle","shuffle the teams to try and even them",""},
    {"rename","renames a player","[name|slot#] [new name]"},
    {"splat","insantly gibs a player","[name|slot#]"},
    {"splata","insantly gibs every player",""},
    {"slap","give a player a specified amount of damage","[name|slot#] (damage)"},
    {"burn","burns a player taking some of his health","[name|slot#]"},
    {"warn","warns a player by displaying the reason","[name|slot#] [reason]"},
    {"news","play the map's news reel or another map's news reel if specified","(mapname)"},
    {"lock","lock one or all of the teams from players joining","[r|b|s|all]"},
    {"unlock","unlock one or all locked teams","[r|b|s|all]"},
    {"nade","makes a player drop a bunch of grenades or all players","[name|slot#|-1] (grenades)"},
    {"pip","show sparks around a player or all players","[name|slot#|-1]"},
    {"pop","pops the helmets of a player or all players","[name|slot#|-1]"},
    {"restart","restarts the current map",""},
    {"reset","resets the current match",""},
    {"fling","flings a player or all players (if none specified) in a random direction","(name|slot#)"},
    {"throw","throws a player or all players (if none specified) forward","(name|slot#)"},
    {"launch","launch a player or all players (if none specified) vertically","(name|slot#)"},
    {"disorient","flips a player's view","[name|slot#]"},
    {"orient","unflips a disoriented player's view","[name|slot#]"},
    {"resetxp","reset a player's XP","[name|slot#] (reason)"},
    {"resetmyxp","resets your own XP",""},
    {"nextmap","loads the next map",""},
    {"swap","swap teams",""},
    {"swap_restart","swap teams and restart the map",""},
    {"revive","revives player","[name|slot#]"},
    {"panzerwar","enable/disable panzerwar","(1|on|0|off)"},
    {"sniperwar","enable/disable sniperwar","(1|on|0|off)"},
    {"disguise","gives a player a disguise of the specified class","[name|slot#] (class letter/number)"},
    {"poison","poisons a player","[name|slot#]"},
    {"ammopack","an ammo pack will spawn out of the player if they have enough chargebar","[name|slot#]"},
    {"medpack","a health pack will spawn out of the player if they have enough chargebar","[name|slot#]"},
    {"pants","removes a player's pants!","(name|slot#)"},
    {"give","gives a player something...","[name|slot#] [item/thing]"},
    {"finger","gives specific information about a player","[name|slot#]"},
    {"uptime","displays server uptime",""},
    {"glow","makes player(s) glow","[name|slot#|-1]"},
    {"freeze","freezes player(s) move","[name|slot#|-1]"},
    {"unfreeze","makes player(s) moving again","[name|slot#|-1]"},
    {"blind","makes a player blind","[name|slot#|-1]"},
    {"unblind","unblind a player","[name|slot#|-1]"},
    {"about","Prints informations about the Server mod",""},
    {"stats","Displays stats for connected players (SMG only)",""},
    {"levedit","Allow to modify levels","([level] [grant|revoke|name|gtext|gsound] [arguments]"},
    {"levinfo","Displays informations of the specicied level","[level]"},
    {"levlist","Displays a list of the levels",""},
    {"spec","Move to spectators and start following the specified player","[name|slot#]"},
    {"banguid","Ban a player using his 8 last NGUID characters (UserID)","[UserID]"},
    {"userlist","List users","[name|level|ip|mac] [argument] (page)\012^xOR\012Syntax: !userlist [page]"},
    {"useredit","Edit an user","[UserID] [grant|revoke|level|gtext|gsound] [arguments]"},
    {"userinfo","Display user details","[UserID]"},
    {"seen","Display last time the user was on this server","[UserID]"},
    {"delrecords","Delete frag and spree records for a specified map, or clear all the records in database","[map_name|DELETEALL]"},
    {"dbsave","Saves the current 'in memory' database into the remote MySQL database",""},
    {"userdelete","Deletes user from database (XP and Admin level will be lost. If the user is banned, the ban will NOT be removed)","[UserID]"},
    {"levdelete","Deletes a level and migrates its users to level 0 OR to the 2nd level specified","[level#] (MigrateUsersToLevel#)"},
    {"levadd","Adds a level","[level#]"},
    {"crazygravity","Toggle Crazy Gravity","[0|1]"},
};
#endif
