game_manager
{
	spawn
	{
		//  29 DM spawns

		create
		{
			scriptName "dmspawn1"
			classname "team_CTF_greenspawn"
			targetname "dmspawn1"
			origin "-9534 -5218 220"
			spawnflags 2	// TEAM_ALLIES
			angle 178
		}

		create
		{
			scriptName "dmspawn2"
			classname "team_CTF_greenspawn"
			targetname "dmspawn2"
			origin "-9354 -5490 512"
			spawnflags 2	// TEAM_ALLIES
			angle 90
		}

		create
		{
			scriptName "dmspawn3"
			classname "team_CTF_greenspawn"
			targetname "dmspawn3"
			origin "-8438 -5844 370"
			spawnflags 2	// TEAM_ALLIES
			angle -179
		}

		create
		{
			scriptName "dmspawn4"
			classname "team_CTF_greenspawn"
			targetname "dmspawn4"
			origin "-8836 -6624 272"
			spawnflags 2	// TEAM_ALLIES
			angle 0
		}

		create
		{
			scriptName "dmspawn5"
			classname "team_CTF_greenspawn"
			targetname "dmspawn5"
			origin "-9757 -6726 332"
			spawnflags 2	// TEAM_ALLIES
			angle -140
		}

		create
		{
			scriptName "dmspawn6"
			classname "team_CTF_greenspawn"
			targetname "dmspawn6"
			origin "-11317 -7641 288"
			spawnflags 2	// TEAM_ALLIES
			angle 90
		}

		create
		{
			scriptName "dmspawn7"
			classname "team_CTF_greenspawn"
			targetname "dmspawn7"
			origin "-12309 -6164 249"
			spawnflags 2	// TEAM_ALLIES
			angle 90
		}

		create
		{
			scriptName "dmspawn8"
			classname "team_CTF_greenspawn"
			targetname "dmspawn8"
			origin "-11980 -5711 240"
			spawnflags 2	// TEAM_ALLIES
			angle 0
		}

		create
		{
			scriptName "dmspawn9"
			classname "team_CTF_greenspawn"
			targetname "dmspawn9"
			origin "-12205 -5922 240"
			spawnflags 2	// TEAM_ALLIES
			angle 90
		}

		create
		{
			scriptName "dmspawn10"
			classname "team_CTF_greenspawn"
			targetname "dmspawn10"
			origin "-10926 -6804 248"
			spawnflags 2	// TEAM_ALLIES
			angle 0
		}

		create
		{
			scriptName "dmspawn11"
			classname "team_CTF_greenspawn"
			targetname "dmspawn11"
			origin "-11141 -6853 448"
			spawnflags 2	// TEAM_ALLIES
			angle 90
		}

		create
		{
			scriptName "dmspawn12"
			classname "team_CTF_greenspawn"
			targetname "dmspawn12"
			origin "-10978 -6645 632"
			spawnflags 2	// TEAM_ALLIES
			angle 90
		}

		create
		{
			scriptName "dmspawn13"
			classname "team_CTF_greenspawn"
			targetname "dmspawn13"
			origin "-12284 -1648 636"
			spawnflags 2	// TEAM_ALLIES
			angle -90
		}

		create
		{
			scriptName "dmspawn14"
			classname "team_CTF_greenspawn"
			targetname "dmspawn14"
			origin "-11289 -2003 584"
			spawnflags 2	// TEAM_ALLIES
			angle 0
		}

		create
		{
			scriptName "dmspawn15"
			classname "team_CTF_greenspawn"
			targetname "dmspawn15"
			origin "-8092 -3206 332"
			spawnflags 2	// TEAM_ALLIES
			angle 100
		}

		create
		{
			scriptName "dmspawn16"
			classname "team_CTF_greenspawn"
			targetname "dmspawn16"
			origin "-8240 -4008 536"
			spawnflags 2	// TEAM_ALLIES
			angle -30
		}

		create
		{
			scriptName "dmspawn17"
			classname "team_CTF_greenspawn"
			targetname "dmspawn17"
			origin "-6460 -3453 358"
			spawnflags 2	// TEAM_ALLIES
			angle 80
		}

		create
		{
			scriptName "dmspawn18"
			classname "team_CTF_greenspawn"
			targetname "dmspawn18"
			origin "-6450 -1167 416"
			spawnflags 2	// TEAM_ALLIES
			angle -50
		}

		create
		{
			scriptName "dmspawn19"
			classname "team_CTF_greenspawn"
			targetname "dmspawn19"
			origin "-5199 -1513 608"
			spawnflags 2	// TEAM_ALLIES
			angle -90
		}

		create
		{
			scriptName "dmspawn20"
			classname "team_CTF_greenspawn"
			targetname "dmspawn20"
			origin "-5510 -2471 600"
			spawnflags 2	// TEAM_ALLIES
			angle 100
		}

		create
		{
			scriptName "dmspawn21"
			classname "team_CTF_greenspawn"
			targetname "dmspawn21"
			origin "-5318 -1879 832"
			spawnflags 2	// TEAM_ALLIES
			angle 90
		}

		create
		{
			scriptName "dmspawn22"
			classname "team_CTF_greenspawn"
			targetname "dmspawn22"
			origin "-3690 -4946 124"
			spawnflags 2	// TEAM_ALLIES
			angle 90
		}

		create
		{
			scriptName "dmspawn23"
			classname "team_CTF_greenspawn"
			targetname "dmspawn23"
			origin "-2092 -1383 672"
			spawnflags 2	// TEAM_ALLIES
			angle -90
		}

		create
		{
			scriptName "dmspawn24"
			classname "team_CTF_greenspawn"
			targetname "dmspawn24"
			origin "261 -3640 128"
			spawnflags 2	// TEAM_ALLIES
			angle 176
		}

		create
		{
			scriptName "dmspawn25"
			classname "team_CTF_greenspawn"
			targetname "dmspawn25"
			origin "-278 -7125 327"
			spawnflags 2	// TEAM_ALLIES
			angle 160
		}

		create
		{
			scriptName "dmspawn26"
			classname "team_CTF_greenspawn"
			targetname "dmspawn26"
			origin "-1084 -8392 368"
			spawnflags 2	// TEAM_ALLIES
			angle 0
		}

		create
		{
			scriptName "dmspawn27"
			classname "team_CTF_greenspawn"
			targetname "dmspawn27"
			origin "-3271 -8304 452"
			spawnflags 2	// TEAM_ALLIES
			angle 0
		}

		create
		{
			scriptName "dmspawn28"
			classname "team_CTF_greenspawn"
			targetname "dmspawn28"
			origin "-3568 -6640 307"
			spawnflags 2	// TEAM_ALLIES
			angle 80
		}

		create
		{
			scriptName "dmspawn29"
			classname "team_CTF_greenspawn"
			targetname "dmspawn29"
			origin "-1898 -4080 228"
			spawnflags 2	// TEAM_ALLIES
			angle 55
		}
		
		//  29 DM spawns
		
		// Game rules
		wm_axis_respawntime	5
		wm_allied_respawntime	5
		wm_number_of_objectives 1
		wm_set_round_timelimit	5

		// Remove tunnel spawn point
		setstate tunnel_wobj invisible

		// Setup the auto spawn points for the map
		wait 50
		setstate t108 invisible

		// Garage Doors
		globalaccum 4 set 0		// Flexible Door 1 status. (0=stationary, 1=moving)
		globalaccum 5 set 0		// Flexible Door 2 status. (0=stationary, 1=moving)

		wait 1000
	}
}

thebridge_lms
{
	spawn
	{
		wait 100
		setstate thebridge_lms default
		setstate lms_alliedstaircase default

		setstate tankbay_hacabinet_cm_marker invisible
		setstate tankbay_hacabinet_toi invisible

		setstate tankbay_healthcabinet invisible
		setstate tankbay_ammocabinet invisible
		setstate tankbay_healthtrigger invisible
		setstate tankbay_ammotrigger invisible
		setstate tankbay_healthcabinet_dmg invisible
		setstate tankbay_ammocabinet_dmg invisible
		setstate tankbay_healthcabinet_clip invisible
		setstate tankbay_ammocabinet_clip invisible

		setstate alliedhut_hacabinet_cm_marker invisible
		setstate alliedhut_hacabinet_toi invisible

		setstate alliedhut_healthcabinet invisible
		setstate alliedhut_ammocabinet invisible
		setstate alliedhut_healthtrigger invisible
		setstate alliedhut_ammotrigger invisible
		setstate alliedhut_healthcabinet_clip invisible
		setstate alliedhut_ammocabinet_clip invisible

		setstate tunneldoor_toi invisible
		setstate depotgate_toi invisible
		setstate depotsidewall_toi invisible

		setstate hurt_tunnelgrateblast invisible
		setstate hurt_cavedoorblast invisible
		setstate hurt_basedoorblast invisible
		setstate hurt_basewallblast invisible
		setstate hurt_fueldumpblast invisible
		setstate axistunneltowerblast invisible
		setstate axissidetowerblast invisible
		setstate axistunneltowerblast invisible
		setstate axissidetowerblast invisible

		setstate fueldump_solid invisible
		setstate fueldump_damaged default
		setstate fueldump_smoke1 invisible
		setstate fueldump_smoke2 invisible
		setstate fueldump_smoke3 invisible
	}
}

axisbasedoor
{
	spawn
	{
		wait 100
		remove
	}
}

axiscentraldoor
{
	spawn
	{
		wait 100
		remove
	}
}

tunnelgrate_solid
{
	spawn
	{
		wait 100
		setstate tunnelgrate_dmg default
		setstate tunnelgrate_solid invisible
	}
}

cavedoor_solid
{
	spawn
	{
		wait 100
		setstate cavedoor_dmg default
		setstate cavedoor_solid invisible
	}
}

basedoor_solid
{
	spawn
	{
		wait 100
		setstate basedoor_dmg default
		setstate basedoor_solid invisible
	}
}

basewall_solid
{
	spawn
	{
		wait 100
		setstate basewall_solid invisible
		setstate basewall_trighurt invisible
	}
}

frontdump
{
	spawn
	{
		wait 100
		setstate frontdumpmaterials_stage1 invisible
		setstate frontdumpmaterials_stage2 invisible
		setstate frontdump_toi invisible
		setstate frontdump1_trighurt invisible
		setstate frontdump2_trighurt invisible
		wait 100
		remove
	}
}

reardump
{
	spawn
	{
		wait 100
		setstate reardumpmaterials_stage1 invisible
		setstate reardumpmaterials_stage2 invisible
		setstate reardump_toi invisible
		setstate reardump1_trighurt invisible
		setstate reardump2_trighurt invisible
		wait 100
		remove
	}
}

axisfueldump
{
	spawn
	{
		wait 100
		setstate fueldump_ladder invisible
		setstate fueldump_toi invisible
		wait 100
		remove
	}
}

tank
{
	spawn
	{
		wait 100
		remove
	}
}

tank_disabler
{
	spawn
	{
		wait 100
		remove
	}
}

tank_enabler
{
	spawn
	{
		wait 100
		remove
	}
}

tank_trigger
{
	spawn
	{
		wait 200
		remove
	}
}

tank_build
{
	spawn
	{
		wait 100
		remove
	}
}

tank_construct
{
	spawn
	{
		wait 100
		remove
	}
}

tank_turret
{
	spawn
	{
		wait 100
		remove
	}
}

tank_turret2solid
{
	spawn
	{
		wait 50
		remove
	}
}

tank_turret2
{
	spawn
	{
		wait 50
		remove
	}
}

tank_smoke
{
	spawn
	{
		wait 50
		remove
	}
}

tank_flash
{
	spawn
	{
		wait 50
		remove
	}
}

thebridge
{
	spawn
	{
		wait 200
		setstate bridgematerials_stage1 invisible
		setstate bridgematerials_stage2 invisible
		setstate bridge_construct_toi invisible
		wait 100
		remove
	}
}

footbridge
{
	spawn
	{
		wait 200
		setstate footbridgematerials invisible
		setstate footbridge_toi invisible

		setstate footbridge invisible
		setstate lms_footbridge default
	}
}

alliedbarnmg42nest
{
	spawn
	{
		wait 200
		constructible_class 2
		setstate alliedbarnmg42 invisible
		setstate alliedbarnmg42materials default
	}

	buildstart final
	{
		setstate alliedbarnmg42 underconstruction
	}

	built final
	{
		setstate alliedbarnmg42 default
		setstate alliedbarnmg42materials invisible
	}

	death
	{
		setstate alliedbarnmg42 invisible
		setstate alliedbarnmg42materials default
		repairmg42 alliedbarnmg42
	}
}

axistunneltower
{
	spawn
	{
		wait 200
		constructible_class 2
		setstate tunneltowerstructure invisible
		setstate axistunneltowermg42 invisible
		setstate tunneltowermaterials default
	}

	buildstart final
	{
		setstate tunneltowerstructure underconstruction
		setstate axistunneltowermg42 underconstruction
	}

	built final
	{
		setstate tunneltowerstructure default
		setstate axistunneltowermg42 default
		setstate tunneltowermaterials invisible
	}

	death
	{
		setstate tunneltowerstructure invisible
		setstate axistunneltowermg42 invisible
		setstate tunneltowermaterials default
		repairmg42 axistunneltowermg42
	}
}


alliedsidemg42
{
	spawn
	{
		wait 200
		constructible_class 2
		setstate alliedsidemg42_sandbags invisible
		setstate alliedsidemg42_gun invisible
	}

	buildstart final
	{
		setstate alliedsidemg42_sandbags underconstruction
		setstate alliedsidemg42_gun underconstruction
	}

	built final
	{
		setstate alliedsidemg42_sandbags default
		setstate alliedsidemg42_gun default
		setstate sidetowermaterials invisible
	}

	death
	{
		setstate alliedsidemg42_sandbags invisible
		setstate alliedsidemg42_gun invisible
		repairmg42 alliedsidemg42_gun

		setstate sidetowermaterials default
	}
}

axissidetower
{
	spawn
	{
		wait 200
		constructible_class 2
		setstate sidetowerstructure invisible
		setstate axissidetowermg42 invisible
		setstate sidetowermaterials default
	}

	buildstart final
	{
		setstate sidetowerstructure underconstruction
		setstate axissidetowermg42 underconstruction
	}

	built final
	{
		setstate sidetowerstructure default
		setstate axissidetowermg42 default
		setstate sidetowermaterials invisible
	}

	death
	{
		setstate sidetowerstructure invisible
		setstate axissidetowermg42 invisible
		repairmg42 axissidetowermg42

		setstate sidetowermaterials default
	}
}

tbdoor1_trigger1
{
	spawn
	{
		accum 3 set 0			// Initial state of lever. (0=down, 1=up)
	}
	trigger main
	{
		trigger tbdoor1_trigger1 up
		trigger tbdoor1_trigger1 down
	}

	trigger up
	{
		accum 3 abort_if_not_equal 0		// Lever up already ?
		globalaccum 4 abort_if_not_equal 0	// Flexible Door moving ?
		resetscript

//		print "Flex Door 1 opening ..."
		globalaccum 4 set 1			// Door is opening ...
		accum 3 set 1				// Lever is in up position
		trigger tbflywheel1 start			// Set flywheel moving
		trigger tbflywheel1 clockwise		// Start turning
		trigger tbflywheel1_sound wheel1_run
		trigger tbdoor1_lever1 up		// Move lever
		trigger tbdoor1-9 open		// Start moving all the door sections
	}

	trigger down
	{
		accum 3 abort_if_not_equal 1		// Lever down already ?
		globalaccum 4 abort_if_not_equal 0	// Flexible Door moving ?
		resetscript

//		print "Flex Door 1 closing ..."
		globalaccum 4 set 1			// Door is opening ...
		accum 3 set 0				// Lever is in up position
		trigger tbflywheel1 start			// Set flywheel moving
		trigger tbflywheel1 anticlockwise		// Start turning
		trigger tbflywheel1_sound wheel1_run
		trigger tbdoor1_lever1 down		// Move lever
		trigger tbdoor1-9 close		// Start moving all the door sections
	}
}

tbdoor1_lever1
{
	trigger down
	{
		gotomarker tbdoor1_lever1_downpos 16
		playsound sound/movers/switches/butn2.wav
	}
	trigger up
	{
		gotomarker tbdoor1_lever1_uppos 16
		playsound sound/movers/switches/switch.wav
	}
}

tbflywheel1_sound
{
	trigger wheel1_run
	{
		trigger tbflywheel1 sound_start
		wait 400
		trigger tbflywheel1 sound_run
	}
}

tbflywheel1
{
	spawn
	{
		accum 3 set 0			// Flywheel moving (0=No, 1=Yes)
	}

	trigger sound_start
	{
		stopsound
		playsound sound/movers/motors/motor_start_01.wav volume 127
	}

	trigger sound_run
	{
		playsound sound/movers/motors/motor_loop_01.wav looping volume 512
	}

	trigger sound_stop
	{
		stopsound
		playsound sound/movers/motors/motor_end_01.wav volume 127
	}

	trigger clockwise
	{
		accum 3 abort_if_not_equal 1	// Flywheel moving ?
		faceangles 90 0 0 250 wait
		accum 3 abort_if_not_equal 1	// Flywheel moving ?
		faceangles 180 0 0 250 wait
		accum 3 abort_if_not_equal 1	// Flywheel moving ?
		faceangles 270 0 0 250 wait
		accum 3 abort_if_not_equal 1	// Flywheel moving ?
		faceangles 0 0 0 250 wait

		trigger tbflywheel1 clockwise
	}

	trigger anticlockwise
	{
		accum 3 abort_if_not_equal 1	// Flywheel moving ?
		faceangles 270 0 0 250 wait
		accum 3 abort_if_not_equal 1	// Flywheel moving ?
		faceangles 180 0 0 250 wait
		accum 3 abort_if_not_equal 1	// Flywheel moving ?
		faceangles 90 0 0 250 wait
		accum 3 abort_if_not_equal 1	// Flywheel moving ?
		faceangles 0 0 0 250 wait

		trigger tbflywheel1 anticlockwise
	}

	trigger start
	{
		accum 3 set 1			// Start wheel moving
	}

	trigger stop
	{
		accum 3 set 0			// Stop wheel moving
		trigger self sound_stop
	}
}

tbdoor1-9
{
	spawn
	{
		wait 200
		followpath 1 tbdrspln1-2 100 wait length 16
	}

	trigger open
	{
		stopsound				// Kill all currently playing sounds belonging to this entity only
		playsound sound/movers/misc/garage_door_start_01.wav volume 96
		wait 50
		playsound sound/movers/misc/garage_door_loop_01.wav looping volume 512
		followpath 1 tbdrspln1-3 50 wait length 16
		followpath 1 tbdrspln1-4 50 wait length 16
		trigger tbflywheel1 stop		// Turn off flywheel
		globalaccum 4 set 0		// Flexible door 1 has stopped moving
		stopsound				// Kill all currently playing sounds belonging to this entity only
		playsound sound/movers/misc/garage_door_end_01.wav volume 96
	}

	trigger close
	{
		stopsound				// Kill all currently playing sounds belonging to this entity only
		playsound sound/movers/misc/garage_door_start_01.wav volume 96
		wait 50
		playsound sound/movers/misc/garage_door_loop_01.wav looping volume 512
		followpath 0 tbdrspln1-4 50 wait length 16
		followpath 0 tbdrspln1-3 50 wait length 16
		trigger tbflywheel1 stop		// Turn off flywheel
		globalaccum 4 set 0		// Flexible door 1 has stopped moving
		stopsound				// Kill all currently playing sounds belonging to this entity only
		playsound sound/movers/misc/garage_door_end_01.wav volume 96
	}
}

tbdoor1-8
{
	spawn
	{
		wait 100
		attatchtotrain tbdoor1-9 16
	}
}

tbdoor1-7
{
	spawn
	{
		wait 100
		attatchtotrain tbdoor1-8 16
	}
}

tbdoor1-6
{
	spawn
	{
		wait 100
		attatchtotrain tbdoor1-7 16
	}
}

tbdoor1-5
{
	spawn
	{
		wait 100
		attatchtotrain tbdoor1-6 16
	}
}

tbdoor1-4
{
	spawn
	{
		wait 100
		attatchtotrain tbdoor1-5 16
	}
}

tbdoor1-3
{
	spawn
	{
		wait 100
		attatchtotrain tbdoor1-4 16
	}
}

tbdoor1-2
{
	spawn
	{
		wait 100
		attatchtotrain tbdoor1-3 16
	}
}

tbdoor1-1
{
	spawn
	{
		wait 100
		attatchtotrain tbdoor1-2 16
	}
}


tbdoor2_trigger1
{
	spawn
	{
		accum 3 set 0			// Initial state of lever. (0=down, 1=up)
	}
	trigger main
	{
		trigger tbdoor2_trigger1 up
		trigger tbdoor2_trigger1 down
	}

	trigger up
	{
		accum 3 abort_if_not_equal 0		// Lever up already ?
		globalaccum 5 abort_if_not_equal 0	// Flexible Door moving ?
		resetscript

		globalaccum 5 set 1			// Door is opening ...
		accum 3 set 1				// Lever is in up position
		trigger tbflywheel2 start			// Set flywheel moving
		trigger tbflywheel2 clockwise		// Start turning
		trigger tbflywheel2_sound wheel2_run
		trigger tbdoor2_lever1 up		// Move lever
		trigger tbdoor2-9 open		// Start moving all the door sections
	}

	trigger down
	{
		accum 3 abort_if_not_equal 1		// Lever down already ?
		globalaccum 5 abort_if_not_equal 0	// Flexible Door moving ?
		resetscript

		globalaccum 5 set 1			// Door is opening ...
		accum 3 set 0				// Lever is in up position
		trigger tbflywheel2 start		// Set flywheel moving
		trigger tbflywheel2 anticlockwise	// Start turning
		trigger tbflywheel2_sound wheel2_run
		trigger tbdoor2_lever1 down		// Move lever
		trigger tbdoor2-9 close		// Start moving all the door sections
	}
}

tbdoor2_lever1
{
	trigger down
	{
		gotomarker tbdoor2_lever1_downpos 16
		playsound sound/movers/switches/butn2.wav
	}
	trigger up
	{
		gotomarker tbdoor2_lever1_uppos 16
		playsound sound/movers/switches/switch.wav
	}
}

tbflywheel2_sound
{
	trigger wheel2_run
	{
		trigger tbflywheel2 sound_start
		wait 400
		trigger tbflywheel2 sound_run
	}
}

tbflywheel2
{
	spawn
	{
		accum 3 set 0			// Flywheel moving (0=No, 1=Yes)
	}

	trigger sound_start
	{
		stopsound
		playsound sound/movers/motors/motor_start_01.wav volume 127
	}

	trigger sound_run
	{
		playsound sound/movers/motors/motor_loop_01.wav looping volume 512
	}

	trigger sound_stop
	{
		stopsound
		playsound sound/movers/motors/motor_end_01.wav volume 127
	}

	trigger clockwise
	{
		accum 3 abort_if_not_equal 1	// Flywheel moving ?
		faceangles 90 0 0 250 wait
		accum 3 abort_if_not_equal 1	// Flywheel moving ?
		faceangles 180 0 0 250 wait
		accum 3 abort_if_not_equal 1	// Flywheel moving ?
		faceangles 270 0 0 250 wait
		accum 3 abort_if_not_equal 1	// Flywheel moving ?
		faceangles 0 0 0 250 wait

		trigger tbflywheel2 clockwise
	}

	trigger anticlockwise
	{
		accum 3 abort_if_not_equal 1	// Flywheel moving ?
		faceangles 270 0 0 250 wait
		accum 3 abort_if_not_equal 1	// Flywheel moving ?
		faceangles 180 0 0 250 wait
		accum 3 abort_if_not_equal 1	// Flywheel moving ?
		faceangles 90 0 0 250 wait
		accum 3 abort_if_not_equal 1	// Flywheel moving ?
		faceangles 0 0 0 250 wait

		trigger tbflywheel2 anticlockwise
	}

	trigger start
	{
		accum 3 set 1			// Start wheel moving
	}
	trigger stop
	{
		accum 3 set 0			// Stop wheel moving

		trigger self sound_stop
	}
}

tbdoor2-9
{
	spawn
	{
		wait 200
		trigger tbdoor2_trigger1 up
	}

	trigger open
	{
		stopsound				// Kill all currently playing sounds belonging to this entity only
		playsound sound/movers/misc/garage_door_start_01.wav volume 96
		wait 50
		playsound sound/movers/misc/garage_door_loop_01.wav looping volume 512
		followpath 1 tbdrspln2-3 50 wait length 16
		followpath 1 tbdrspln2-4 50 wait length 16
		trigger tbflywheel2 stop		// Turn off flywheel
		globalaccum 5 set 0		// Flexible door 1 has stopped moving
		stopsound				// Kill all currently playing sounds belonging to this entity only
		playsound sound/movers/misc/garage_door_end_01.wav volume 96
	}

	trigger close
	{
		stopsound				// Kill all currently playing sounds belonging to this entity only
		playsound sound/movers/misc/garage_door_start_01.wav volume 96
		wait 50
		playsound sound/movers/misc/garage_door_loop_01.wav looping volume 512
		followpath 0 tbdrspln2-4 50 wait length 16
		followpath 0 tbdrspln2-3 50 wait length 16
		trigger tbflywheel2 stop		// Turn off flywheel
		globalaccum 5 set 0		// Flexible door 1 has stopped moving
		stopsound				// Kill all currently playing sounds belonging to this entity only
		playsound sound/movers/misc/garage_door_end_01.wav volume 96
	}
}

tbdoor2-8
{
	spawn
	{
		wait 100
		attatchtotrain tbdoor2-9 16
	}
}

tbdoor2-7
{
	spawn
	{
		wait 100
		attatchtotrain tbdoor2-8 16
	}
}

tbdoor2-6
{
	spawn
	{
		wait 100
		attatchtotrain tbdoor2-7 16
	}
}

tbdoor2-5
{
	spawn
	{
		wait 100
		attatchtotrain tbdoor2-6 16
	}
}

tbdoor2-4
{
	spawn
	{
		wait 100
		attatchtotrain tbdoor2-5 16
	}
}

tbdoor2-3
{
	spawn
	{
		wait 100
		attatchtotrain tbdoor2-4 16
	}
}

tbdoor2-2
{
	spawn
	{
		wait 100
		attatchtotrain tbdoor2-3 16
	}
}

tbdoor2-1
{
	spawn
	{
		wait 100
		attatchtotrain tbdoor2-2 16
	}
}

axis_radio_destroyed
{
	spawn
	{
		wait 200
		setstate axis_radio_destroyed invisible
		setstate axis_radio_destroyed_model invisible
	}
	trigger hide
	{
		setstate axis_radio_destroyed invisible
		setstate axis_radio_destroyed_model invisible
	}
	trigger show
	{
		setstate axis_radio_destroyed default
		setstate axis_radio_destroyed_model default
		setstate axishqstuff invisible // Arial tower outside of building
	}
}

axis_radio_closed
{
	spawn
	{
		wait 200
		setstate axis_radio_closed default
		setstate axis_radio_closed_model default
	}
	trigger hide
	{
		setstate axis_radio_closed invisible
		setstate axis_radio_closed_model invisible
	}
	trigger show
	{
		setstate axis_radio_closed default
		setstate axis_radio_closed_model default
	}
}

axis_radio_built
{
	spawn
	{
		wait 400

		constructible_class 2

		trigger self setup
		setstate axishqstuff invisible

	}

	trigger setup
	{
		sethqstatus 0 1
	}

	buildstart final
	{
		trigger axis_radio_built_model trans
		trigger axis_radio_destroyed hide
		trigger axis_radio_closed hide
	}

	decayed final
	{
		trigger axis_radio_built_model hide
		trigger axis_radio_closed show
	}

	built final
	{
		trigger axis_radio_built_model show
		trigger axis_radio_closed hide
		trigger axis_radio_destroyed hide

		trigger allied_radio_built_model enable_axis_features
		enablespeaker axishq_sound
	}

	death
	{
		trigger axis_radio_built_model hide
		trigger axis_radio_destroyed show

		trigger axis_radio_built_model disable_axis_features
		disablespeaker axishq_sound
	}
}

axis_radio_built_model
{
	spawn
	{
		wait 400
		setstate axis_radio_built_model invisible

		accum 0 bitreset 0	// set if radio is built
		accum 0 bitreset 1	// set if goal should be ignored
	}

	trigger show
	{
		setstate axis_radio_built_model default
	}

	trigger hide
	{
		setstate axis_radio_built_model invisible
	}

	trigger trans
	{
		setstate axis_radio_built_model underconstruction
	}

	trigger enable_axis_features
	{
		sethqstatus 0 1
		accum 0 bitset 0
	}

	trigger disable_axis_features
	{
		sethqstatus 0 0
		accum 0 bitreset 0
	}
}

allied_radio_destroyed
{
	spawn
	{
		wait 200
		setstate allied_radio_destroyed invisible
		setstate allied_radio_destroyed_model invisible
	}
	trigger hide
	{
		setstate allied_radio_destroyed invisible
		setstate allied_radio_destroyed_model invisible
	}
	trigger show
	{
		setstate allied_radio_destroyed default
		setstate allied_radio_destroyed_model default
	}
}

allied_radio_closed
{
	spawn
	{
		wait 200
		setstate allied_radio_closed default
		setstate allied_radio_closed_model default
	}
	trigger hide
	{
		setstate allied_radio_closed invisible
		setstate allied_radio_closed_model invisible
	}
	trigger show
	{
		setstate allied_radio_closed default
		setstate allied_radio_closed_model default
	}
}

allied_radio_built
{
	spawn
	{
		wait 400
		constructible_class 2
		trigger allied_radio_built setup
	}

	trigger setup
	{
		sethqstatus 1 0
	}

	buildstart final
	{
		trigger allied_radio_built_model trans
		trigger allied_radio_destroyed hide
		trigger allied_radio_closed hide
	}

	decayed final
	{
		trigger allied_radio_built_model hide
		trigger allied_radio_closed show
	}

	built final
	{
		trigger allied_radio_built_model show
		trigger allied_radio_closed hide
		trigger allied_radio_destroyed hide

		trigger allied_radio_built_model enable_allied_features
		enablespeaker alliedhq_sound
	}

	death
	{
		trigger allied_radio_built_model hide
		trigger allied_radio_destroyed show

		trigger allied_radio_built_model disable_allied_features
		disablespeaker alliedhq_sound
	}
}

allied_radio_built_model
{
	spawn
	{
		wait 400
		setstate allied_radio_built_model invisible

		accum 0 bitreset 0	// set if radio is built
		accum 0 bitreset 1	// set if goal should be ignored
	}

	trigger show
	{
		setstate allied_radio_built_model default
	}

	trigger hide
	{
		setstate allied_radio_built_model invisible
	}

	trigger trans
	{
		setstate allied_radio_built_model underconstruction
	}

	trigger enable_allied_features
	{
		accum 0 bitset 0
	}

	trigger disable_allied_features
	{
		sethqstatus 1 1
		accum 0 bitreset 0
	}
}
