game_manager
{
	spawn
	{
		//  29 DM spawns

		create
		{
			scriptName "dmspawn1"
			classname "team_CTF_greenspawn"
			targetname "dmspawn1"
			origin "252 2981 -428"
			spawnflags 2	// TEAM_ALLIES
			angle 0
		}

		create
		{
			scriptName "dmspawn2"
			classname "team_CTF_greenspawn"
			targetname "dmspawn2"
			origin "2407 2303 -520"
			spawnflags 2	// TEAM_ALLIES
			angle -130
		}

		create
		{
			scriptName "dmspawn3"
			classname "team_CTF_greenspawn"
			targetname "dmspawn3"
			origin "5206 4592 -855"
			spawnflags 2	// TEAM_ALLIES
			angle -174
		}

		create
		{
			scriptName "dmspawn4"
			classname "team_CTF_greenspawn"
			targetname "dmspawn4"
			origin "2336 4688 -215"
			spawnflags 2	// TEAM_ALLIES
			angle 50
		}

		create
		{
			scriptName "dmspawn5"
			classname "team_CTF_greenspawn"
			targetname "dmspawn5"
			origin "2261 6292 -382"
			spawnflags 2	// TEAM_ALLIES
			angle -136
		}

		create
		{
			scriptName "dmspawn6"
			classname "team_CTF_greenspawn"
			targetname "dmspawn6"
			origin "3142 7300 -415"
			spawnflags 2	// TEAM_ALLIES
			angle -133
		}

		create
		{
			scriptName "dmspawn8"
			classname "team_CTF_greenspawn"
			targetname "dmspawn8"
			origin "3881 7919 -127"
			spawnflags 2	// TEAM_ALLIES
			angle 177
		}

		create
		{
			scriptName "dmspawn9"
			classname "team_CTF_greenspawn"
			targetname "dmspawn9"
			origin "3229 7307 -275"
			spawnflags 2	// TEAM_ALLIES
			angle -66
		}

		create
		{
			scriptName "dmspawn10"
			classname "team_CTF_greenspawn"
			targetname "dmspawn10"
			origin "5157 7655 -447"
			spawnflags 2	// TEAM_ALLIES
			angle 40
		}

		create
		{
			scriptName "dmspawn11"
			classname "team_CTF_greenspawn"
			targetname "dmspawn11"
			origin "5485 6568 -135"
			spawnflags 2	// TEAM_ALLIES
			angle -174
		}

		create
		{
			scriptName "dmspawn12"
			classname "team_CTF_greenspawn"
			targetname "dmspawn12"
			origin "6424 6447 -215"
			spawnflags 2	// TEAM_ALLIES
			angle -38
		}

		create
		{
			scriptName "dmspawn13"
			classname "team_CTF_greenspawn"
			targetname "dmspawn13"
			origin "6375 5130 -279"
			spawnflags 2	// TEAM_ALLIES
			angle 0
		}

		create
		{
			scriptName "dmspawn14"
			classname "team_CTF_greenspawn"
			targetname "dmspawn14"
			origin "7136 3999 -375"
			spawnflags 2	// TEAM_ALLIES
			angle -68
		}

		create
		{
			scriptName "dmspawn15"
			classname "team_CTF_greenspawn"
			targetname "dmspawn15"
			origin "7942 3350 -415"
			spawnflags 2	// TEAM_ALLIES
			angle 56
		}

		create
		{
			scriptName "dmspawn16"
			classname "team_CTF_greenspawn"
			targetname "dmspawn16"
			origin "7576 4328 -415"
			spawnflags 2	// TEAM_ALLIES
			angle -131
		}

		create
		{
			scriptName "dmspawn17"
			classname "team_CTF_greenspawn"
			targetname "dmspawn17"
			origin "7780 4995 -159"
			spawnflags 2	// TEAM_ALLIES
			angle 49
		}

		create
		{
			scriptName "dmspawn18"
			classname "team_CTF_greenspawn"
			targetname "dmspawn18"
			origin "7445 5483 -99"
			spawnflags 2	// TEAM_ALLIES
			angle -93
		}

		create
		{
			scriptName "dmspawn19"
			classname "team_CTF_greenspawn"
			targetname "dmspawn19"
			origin "7414 4034 -159"
			spawnflags 2	// TEAM_ALLIES
			angle 40
		}

		create
		{
			scriptName "dmspawn20"
			classname "team_CTF_greenspawn"
			targetname "dmspawn20"
			origin "8271 4321 -135"
			spawnflags 2	// TEAM_ALLIES
			angle 177
		}

		create
		{
			scriptName "dmspawn21"
			classname "team_CTF_greenspawn"
			targetname "dmspawn21"
			origin "8278 4063 -415"
			spawnflags 2	// TEAM_ALLIES
			angle -7
		}

		create
		{
			scriptName "dmspawn22"
			classname "team_CTF_greenspawn"
			targetname "dmspawn22"
			origin "8315 3917 -415"
			spawnflags 2	// TEAM_ALLIES
			angle -44
		}

		create
		{
			scriptName "dmspawn23"
			classname "team_CTF_greenspawn"
			targetname "dmspawn23"
			origin "9421 3925 -159"
			spawnflags 2	// TEAM_ALLIES
			angle 0
		}

		create
		{
			scriptName "dmspawn24"
			classname "team_CTF_greenspawn"
			targetname "dmspawn24"
			origin "8313 3770 -159"
			spawnflags 2	// TEAM_ALLIES
			angle 145
		}

		create
		{
			scriptName "dmspawn25"
			classname "team_CTF_greenspawn"
			targetname "dmspawn25"
			origin "9775 5513 -350"
			spawnflags 2	// TEAM_ALLIES
			angle -31
		}

		create
		{
			scriptName "dmspawn26"
			classname "team_CTF_greenspawn"
			targetname "dmspawn26"
			origin "8493 5713 -99"
			spawnflags 2	// TEAM_ALLIES
			angle -52
		}

		create
		{
			scriptName "dmspawn27"
			classname "team_CTF_greenspawn"
			targetname "dmspawn27"
			origin "9363 5335 -351"
			spawnflags 2	// TEAM_ALLIES
			angle -157
		}

		create
		{
			scriptName "dmspawn28"
			classname "team_CTF_greenspawn"
			targetname "dmspawn28"
			origin "8797 3093 -318"
			spawnflags 2	// TEAM_ALLIES
			angle -129
		}

		create
		{
			scriptName "dmspawn29"
			classname "team_CTF_greenspawn"
			targetname "dmspawn29"
			origin "4498 6306 -368"
			spawnflags 2	// TEAM_ALLIES
			angle 45
		}

		create
		{
			scriptName "dmspawn30"
			classname "team_CTF_greenspawn"
			targetname "dmspawn30"
			origin "5642 4536 -845"
			spawnflags 2	// TEAM_ALLIES
			angle 0
		}

		//  29 DM spawns

		// Game rules
		wm_axis_respawntime	5
		wm_allied_respawntime	5
		wm_number_of_objectives 1
		wm_set_round_timelimit	5

		// start triggered loops on/off
		disablespeaker wp1_sound				// water pump 1
		disablespeaker wp2_sound				// water pump 2
		disablespeaker hose1_sound1				// water outlet 1
		disablespeaker hose1_sound2				// water tunnel 1
		disablespeaker hose2_sound1				// water outlet 2
		disablespeaker hose2_sound2				// water tunnel 2
		disablespeaker allies_compost_sound		// allies command post
		disablespeaker axis_compost_sound		// axis command post
		disablespeaker axis_compost_sound_lms	// axis command post lms

		wait 1000
	}
}

oldcityflag
{
	spawn
	{
		wait 400

		remove
	}
}

oldcityspawns
{
	spawn
	{
		wait 50

		remove
	}
}

old_city_wobj
{
	spawn
	{
		wait 50

		remove
	}
}

old_city_wall_toi
{
	spawn
	{
		wait 400

		remove
	}
}

oldcitywall
{
	spawn
	{
		wait 400

		remove
	}
}

vo_in_base
{
	spawn
	{
		wait 400

		remove
	}
}

// -----------------
// End sequence tank
end_tank
{
	spawn
	{
		wait 400

		remove
	}
}

end_turret
{
	spawn
	{
		wait 400

		remove
	}
}

// ---------------
// Team only doors
team_only_door_1
{
	spawn
	{
		wait 400

		remove
	}
}

team_only_door_2
{
	spawn
	{
		wait 400

		remove
	}
}

team_only_door_3
{
	spawn
	{
		wait 400

		remove
	}
}

// ----------
// Oasis Pump
water_pump_1_toi
{
	spawn
	{
		wait 400

		remove
	}
}

water_pump_1
{
	spawn
	{
		wait 200

		trigger water_pump_1 hideoasispump
	}

	trigger hideoasispump
	{
		setstate water_pump_1 invisible
		setstate pump_materials_1 invisible
		setstate pump_materials_clip_1 invisible
		setstate pump_flag_1 invisible
		setstate pump1_p1 default
		setstate pump1_p2 default
		setstate pump_sound invisible
		setstate water_pump_1_oldclip default
		setstate water_pump_1_lms_clip default
	}
}

// -------------
// Old City Pump
water_pump_2_toi
{
	spawn
	{
		wait 400

		remove
	}
}

water_pump_2
{
	spawn
	{
		wait 200

		trigger water_pump_2 hideoldcitypump
	}

	trigger hideoldcitypump
	{
		setstate water_pump_2 invisible
		setstate pump_materials_2 invisible
		setstate pump_materials_clip_2 invisible
		setstate pump_flag_2 invisible
		setstate pump2_p1 default
		setstate pump2_p2 default
		setstate pump2_sound invisible
		setstate water_pump_2_oldclip default
		setstate water_pump_2_lms_clip default
	}
}

// -----------------
//Water tunnel stuff

water_tunnel
{
	spawn
	{
		wait 200

		trigger self down
	}

	trigger down
	{
		gotomarker path_water_tunnel_lower 8 wait
	}
}

water_tunnel2
{
	spawn
	{
		wait 200

		trigger self down
	}

	trigger down
	{
		gotomarker path_water_tunnel_lower 8 wait
	}
}

water_discharge
{
	spawn
	{
		wait 200

		trigger self up
	}

	trigger up
	{
		gotomarker path_water_discharge_top 3 wait
	}
}

water_discharge_2
{
	spawn
	{
		wait 200

		trigger self up
	}

	trigger up
	{
		gotomarker path_water_discharge_2_top 3 wait
	}
}

// Axis ONLY - Garrison MG Nest
mg42_clip_1
{
	spawn
	{
		wait 200

		constructible_class 2

		trigger mg42_clip_1 setup
	}

	trigger setup
	{
		setstate mg42_1 invisible

		setstate mg42_materials_1 default
		setstate mg42_materials_clip_1 default
		setstate mg42_flag_1 default
	}

	buildstart final
	{
		setstate mg42_1 underconstruction

		setstate mg42_materials_1 default
		setstate mg42_materials_clip_1 default
		setstate mg42_flag_1 default
	}

	built final
	{
		setstate mg42_1 default

		setstate mg42_materials_1 invisible
		setstate mg42_materials_clip_1 invisible
		setstate mg42_flag_1 invisible
	}

	death
	{
		setstate mg42_1 invisible
		repairmg42 mg42_1
		setstate mg42_materials_1 default
		setstate mg42_materials_clip_1 default
		setstate mg42_flag_1 default
	}

	decayed final
	{
		setstate mg42_1 invisible

		setstate mg42_materials_1 default
		setstate mg42_materials_clip_1 default
		setstate mg42_flag_1 default
	}
}

// Allied ONLY - Old City MG Nest
mg42_clip_2
{
	spawn
	{
		wait 200

		constructible_class 2

		trigger mg42_clip_2 setup
	}

	trigger setup
	{
		setstate mg42_2 invisible

		setstate mg42_materials_2 default
		setstate mg42_materials_clip_2 default
		setstate mg42_flag_2 default
	}

	buildstart final
	{
		setstate mg42_2 underconstruction

		setstate mg42_materials_2 default
		setstate mg42_materials_clip_2 default
		setstate mg42_flag_2 default
	}

	built final
	{
		setstate mg42_2 default

		setstate mg42_materials_2 invisible
		setstate mg42_materials_clip_2 invisible
		setstate mg42_flag_2 invisible
	}

	death
	{
		setstate mg42_2 invisible
		repairmg42 mg42_2
		setstate mg42_materials_2 default
		setstate mg42_materials_clip_2 default
		setstate mg42_flag_2 default
	}

	decayed final
	{
		setstate mg42_2 invisible

		setstate mg42_materials_2 default
		setstate mg42_materials_clip_2 default
		setstate mg42_flag_2 default
	}
}

// North Gun
pak75_1_toi
{
	spawn
	{
		wait 400

		remove
	}
}

pak75_clip_1
{
	spawn
	{
		wait 200

		trigger pak75_clip_1 hidenorthpak75
	}

	trigger hidenorthpak75
	{
		setstate pak75_clip_1 invisible
		setstate pak75_smoke_1 invisible
		setstate pak75_model_broken_1 default
		setstate pak75_clip_broken_1 default
		setstate pak75_model_1 invisible
		setstate north_pak_clipbrush invisible
	}
}

end_boom_north
{
	spawn
	{
		wait 400

		remove
	}
}

end_north_pak_muzzle
{
	spawn
	{
		wait 400

		remove
	}
}

// South Gun
pak75_2_toi
{
	spawn
	{
		wait 400

		remove
	}
}

pak75_clip_2
{
	spawn
	{
		wait 200

		trigger pak75_clip_2 hidesouthpak75
	}

	trigger hidesouthpak75
	{
		setstate pak75_clip_2 invisible
		setstate pak75_smoke_2 invisible
		setstate pak75_model_broken_2 default
		setstate pak75_clip_broken_2 default
		setstate pak75_model_2 invisible
		setstate south_pak_clipbrush invisible
	}
}

end_boom_south
{
	spawn
	{
		wait 400

		remove
	}
}


end_south_pak_muzzle
{
	spawn
	{
		wait 400

		remove
	}
}

// ================================================
// =============== COMMAND POSTS ==================
// ================================================

allied_radio_destroyed
{
	spawn
	{
		wait 400
		setstate allied_radio_destroyed invisible
		setstate allied_radio_destroyed_model invisible
	}

	trigger hide
	{
		setstate allied_radio_destroyed invisible
		setstate allied_radio_destroyed_model invisible
	}

	trigger show
	{
		accum 0 abort_if_equal 0
		setstate allied_radio_destroyed default
		setstate allied_radio_destroyed_model default
	}

	trigger enable
	{
		accum 0 set 1
	}
}

allied_radio_closed
{
	trigger hide
	{
		setstate allied_radio_closed invisible
		setstate allied_radio_closed_model invisible
	}

	trigger show
	{
		accum 0 abort_if_equal 1
		setstate allied_radio_closed default
		setstate allied_radio_closed_model default
	}

	trigger disable
	{
		accum 0 set 1
	}
}

allied_radio_built
{
	spawn
	{
		wait 400
		trigger allied_radio_built setup
	}

	trigger setup
	{
		sethqstatus 1 0
	}

	buildstart final
	{
		trigger allied_radio_built_model trans

		trigger allied_radio_destroyed hide
		trigger allied_radio_closed 	hide
	}

	built final
	{
		trigger allied_radio_built_model show

		trigger allied_radio_destroyed enable
		trigger allied_radio_closed 	disable

		trigger allied_radio_built_model enable_allied_features

		enablespeaker allies_compost_sound
	}

	death
	{
		trigger allied_radio_built_model hide

		trigger allied_radio_destroyed show

		trigger allied_radio_built_model disable_allied_features

		disablespeaker allies_compost_sound
	}
}

allied_radio_built_model
{
	spawn
	{
		wait 400
		setstate allied_radio_built_model invisible
	}

	trigger show
	{
		setstate allied_radio_built_model default
	}

	trigger hide
	{
		setstate allied_radio_built_model invisible
	}

	trigger trans
	{
		setstate allied_radio_built_model underconstruction
	}

	trigger enable_allied_features
	{
		sethqstatus 1 1
	}

	trigger disable_allied_features
	{
		sethqstatus 1 0
	}
}

axis_radio_lms_destroyed
{
	spawn
	{
		wait 400
		setstate axis_radio_lms_destroyed invisible
		setstate axis_radio_destroyed_lms_model invisible
	}

	trigger hide
	{
		setstate axis_radio_lms_destroyed invisible
		setstate axis_radio_destroyed_lms_model invisible
	}

	trigger show
	{
		accum 0 abort_if_equal 0
		setstate axis_radio_lms_destroyed default
		setstate axis_radio_destroyed_lms_model default
	}

	trigger enable
	{
		accum 0 set 1
	}
}

axis_radio_lms_closed
{
	trigger hide
	{
		setstate axis_radio_lms_closed invisible
		setstate axis_radio_closed_lms_model invisible
	}

	trigger show
	{
		accum 0 abort_if_equal 1
		setstate axis_radio_lms_closed default
		setstate axis_radio_closed_lms_model default
	}

	trigger disable
	{
		accum 0 set 1
	}
}

axis_radio_built_lms
{
	spawn
	{
		wait 400
		trigger axis_radio_built_lms setup
	}

	trigger setup
	{
		sethqstatus 0 0
	}

	buildstart final
	{
		trigger axis_radio_built_lms_model trans

		trigger axis_radio_lms_destroyed hide
		trigger axis_radio_lms_closed 	hide
	}

	built final
	{
		trigger axis_radio_built_lms_model show

		trigger axis_radio_lms_destroyed enable
		trigger axis_radio_lms_closed 	disable

		trigger axis_radio_built_lms_model enable_axis_features

		enablespeaker axis_compost_sound_lms
	}

	decayed final
	{
		trigger axis_radio_built_lms_model hide

		trigger axis_radio_lms_destroyed show
		trigger axis_radio_lms_closed 	show
	}

	death
	{
		trigger axis_radio_built_lms_model hide

		trigger axis_radio_lms_destroyed show

		trigger axis_radio_built_lms_model disable_axis_features

		disablespeaker axis_compost_sound_lms
	}
}

axis_radio_built_lms_model
{
	spawn
	{
		wait 400
		setstate axis_radio_built_lms_model invisible
	}

	trigger show
	{
		setstate axis_radio_built_lms_model default
	}

	trigger hide
	{
		setstate axis_radio_built_lms_model invisible
	}

	trigger trans
	{
		setstate axis_radio_built_lms_model underconstruction
	}

	trigger enable_axis_features
	{
		sethqstatus 0 1
	}

	trigger disable_axis_features
	{
		sethqstatus 0 0
	}
}

axis_command_post_toi
{
	spawn
	{
		wait 400

		remove
	}
}

axis_command_post_clip_garison
{
	spawn
	{
		wait 400

		trigger self rem_otherbits
		trigger self rem_commandpost_clip

		remove
	}

	trigger rem_otherbits
	{
		setstate axis_radio_closed invisible
		setstate axis_radio_destroyed invisible
		setstate axis_radio_built invisible
		setstate axis_radio_closed_model invisible
		setstate axis_radio_destroyed_model invisible
		setstate axis_radio_built_model invisible
	}

	trigger rem_commandpost_clip
	{
		setstate axis_command_post_clip_lms default
	}
}
// ===================================================
// ============== END COMMAND POSTS ==================
// ===================================================
