game_manager
{
	spawn
	{
		accum 1 set 0
		accum 2 set 0

		//  26 DM spawns
		
		create
		{
			scriptName "dmspawn1"
			classname "team_CTF_greenspawn"
			targetname "dmspawn1"
			origin "-194 -2099 -79"
			spawnflags 2	
			angle 90
		}
		
		create
		{
			scriptName "dmspawn2"
			classname "team_CTF_greenspawn"
			targetname "dmspawn2"
			origin "-1587 -2556 -103"
			spawnflags 2	
			angle 75
		}
		
		create
		{
			scriptName "dmspawn3"
			classname "team_CTF_greenspawn"
			targetname "dmspawn3"
			origin "-333 -3922 -63"
			spawnflags 2	
			angle 100
		}
		
		create
		{
			scriptName "dmspawn4"
			classname "team_CTF_greenspawn"
			targetname "dmspawn4"
			origin "-829 -3403 80"
			spawnflags 2	
			angle 40
		}
		
		create
		{
			scriptName "dmspawn5"
			classname "team_CTF_greenspawn"
			targetname "dmspawn5"
			origin "-188 -3690 -24"
			spawnflags 2	
			angle 90
		}
		
		create
		{
			scriptName "dmspawn6"
			classname "team_CTF_greenspawn"
			targetname "dmspawn6"
			origin "-45 -4007 -63"
			spawnflags 2	
			angle 90
		}
		
		create
		{
			scriptName "dmspawn7"
			classname "team_CTF_greenspawn"
			targetname "dmspawn7"
			origin "1112 -2447 -103"
			spawnflags 2	
			angle 130
		}
		
		create
		{
			scriptName "dmspawn8"
			classname "team_CTF_greenspawn"
			targetname "dmspawn8"
			origin "514 -693 48"
			spawnflags 2	
			angle 160
		}
		
		create
		{
			scriptName "dmspawn9"
			classname "team_CTF_greenspawn"
			targetname "dmspawn9"
			origin "-900 -727 48"
			spawnflags 2	
			angle 20
		}
		
		create
		{
			scriptName "dmspawn10"
			classname "team_CTF_greenspawn"
			targetname "dmspawn10"
			origin "238 989 70"
			spawnflags 2	
			angle -90
		}
		
		create
		{
			scriptName "dmspawn11"
			classname "team_CTF_greenspawn"
			targetname "dmspawn11"
			origin "277 1072 48"
			spawnflags 2	
			angle 40
		}
		
		create
		{
			scriptName "dmspawn12"
			classname "team_CTF_greenspawn"
			targetname "dmspawn12"
			origin "-1008 576 48"
			spawnflags 2	
			angle 40
		}
		
		create
		{
			scriptName "dmspawn13"
			classname "team_CTF_greenspawn"
			targetname "dmspawn13"
			origin "1133 2847 104"
			spawnflags 2	
			angle 40
		}
		
		create
		{
			scriptName "dmspawn14"
			classname "team_CTF_greenspawn"
			targetname "dmspawn14"
			origin "386 2100 -159"
			spawnflags 2	
			angle -90
		}
		
		create
		{
			scriptName "dmspawn15"
			classname "team_CTF_greenspawn"
			targetname "dmspawn15"
			origin "1651 1509 -31"
			spawnflags 2	
			angle 35
		}
		
		create
		{
			scriptName "dmspawn16"
			classname "team_CTF_greenspawn"
			targetname "dmspawn16"
			origin "2548 1737 137"
			spawnflags 2	
			angle 0
		}
		
		create
		{
			scriptName "dmspawn17"
			classname "team_CTF_greenspawn"
			targetname "dmspawn17"
			origin "1726 2237 104"
			spawnflags 2	
			angle -125
		}
		
		create
		{
			scriptName "dmspawn18"
			classname "team_CTF_greenspawn"
			targetname "dmspawn18"
			origin "1590 3300 104"
			spawnflags 2	
			angle 130
		}
		
		create
		{
			scriptName "dmspawn19"
			classname "team_CTF_greenspawn"
			targetname "dmspawn19"
			origin "1543 2921 104"
			spawnflags 2	
			angle 35
		}
		
		create
		{
			scriptName "dmspawn20"
			classname "team_CTF_greenspawn"
			targetname "dmspawn20"
			origin "2203 2833 -159"
			spawnflags 2	
			angle -170
		}
		
		create
		{
			scriptName "dmspawn21"
			classname "team_CTF_greenspawn"
			targetname "dmspawn21"
			origin "1706 3685 -159"
			spawnflags 2	
			angle 90
		}
		
		create
		{
			scriptName "dmspawn22"
			classname "team_CTF_greenspawn"
			targetname "dmspawn22"
			origin "341 4043 -159"
			spawnflags 2	
			angle -10
		}
		
		create
		{
			scriptName "dmspawn23"
			classname "team_CTF_greenspawn"
			targetname "dmspawn23"
			origin "517 2211 -159"
			spawnflags 2	
			angle 90
		}
		
		create
		{
			scriptName "dmspawn24"
			classname "team_CTF_greenspawn"
			targetname "dmspawn24"
			origin "862 3181 96"
			spawnflags 2	
			angle -90
		}
		
		create
		{
			scriptName "dmspawn25"
			classname "team_CTF_greenspawn"
			targetname "dmspawn25"
			origin "-314 2635 -191"
			spawnflags 2	
			angle -90
		}
		
		create
		{
			scriptName "dmspawn26"
			classname "team_CTF_greenspawn"
			targetname "dmspawn26"
			origin "5 3150 -95"
			spawnflags 2	
			angle -90
		}

		//  26 DM spawns

                // Game rules
                wm_axis_respawntime		5
                wm_allied_respawntime		5
                wm_number_of_objectives		1
                wm_set_round_timelimit		5

		setstate forwardbunker_wo invisible

		wait 1000
		
		setstate axis_lever_trigger invisible
		setstate goldclip2 invisible
	}

	trigger objective_counter
	{
		accum 1 inc 1
		trigger game_manager checkgame
	}

	trigger checkgame
	{
		accum 1 abort_if_not_equal 2

		wm_announce "Allies have escaped with the Gold!"
		wm_setwinner 1
		//wait 500
		wm_endround
	}		
}

forwardbunkerflag
{
	spawn
	{
		accum 0 set 0
		remove
	}

	trigger axis_capture
	{
		accum 0 abort_if_equal 0
		accum 0 set 0

		wm_announce "Axis reclaim the Forward Bunker!"

		setstate forwardbunker_wo invisible

		setautospawn "The Train Cars" 1

		wm_objective_status 4 0 1
		wm_objective_status 4 1 2

		wm_addteamvoiceannounce 0 "radar_axis_bunker_stop"
		wm_addteamvoiceannounce 1 "radar_allies_bunker_capture"
		wm_removeteamvoiceannounce 1 "goldrush_allies_gold_get"

		wm_teamvoiceannounce 0 "radar_axis_bunker_reclaimed"
		wm_teamvoiceannounce 1 "radar_allies_bunker_reclaimed"
	}

	trigger allied_capture
	{
		accum 0 abort_if_equal 1
		accum 0 set 1

		wm_announce "Allies capture the Forward Bunker!"

		setstate forwardbunker_wo default

		setautospawn "Forward Bunker" 1

		wm_objective_status 3 0 2
		wm_objective_status 3 1 1

		wm_removeteamvoiceannounce 1 "radar_allies_bunker_capture"
		wm_removeteamvoiceannounce 0 "radar_axis_bunker_stop"
		wm_addteamvoiceannounce 1 "goldrush_allies_gold_get"

		wm_teamvoiceannounce 0 "radar_axis_bunker_captured"
		wm_teamvoiceannounce 1 "radar_allies_bunker_captured"
		wm_teamvoiceannounce 1 "goldrush_allies_gold_get"
	}

	trigger switchit
	{
		accum 0 abort_if_equal 1
		alertentity forwardbunkerspawns
	}
}

east_wall
{
	spawn 
	{
		constructible_class 3
		accum 3 set 0
		remove
	}

	death 
	{
		accum 3 abort_if_equal 1
		accum 3 set 1

		alertentity east_rubble

		wm_announce "Allies have damaged the East Wall"

		wm_teamvoiceannounce 0 "general_objdestroy_axis"
		wm_teamvoiceannounce 1 "general_objdestroy_allies"

		wm_objective_status 1 0 2
		wm_objective_status 1 1 1

	}
}

west_wall
{
	spawn 
	{
		constructible_class 3
		accum 4 set 0
		remove
	}

	death 
	{
		accum 4 abort_if_equal 1
		accum 4 set 1

		alertentity west_rubble

		wm_announce "Allies have damaged the West Wall"

		wm_teamvoiceannounce 0 "general_objdestroy_axis"
		wm_teamvoiceannounce 1 "general_objdestroy_allies"

		wm_objective_status 2 0 2
		wm_objective_status 2 1 1
	}
}

axis_gold1
{
	spawn
	{
		wait 200
		setstate axis_gold_captured1 invisible
		remove
	}

	trigger stolen
	{
		wm_announce "The Allies have stolen a gold crate!"

		setstate axis_gold_cm_marker invisible

		wm_objective_status 4 0 2
		wm_objective_status 4 1 1

		wm_teamvoiceannounce 0 "goldrush_axis_gold1_taken"
		wm_teamvoiceannounce 1 "goldrush_allies_gold1_taken"
	}

	trigger returned
	{
		setstate axis_gold_cm_marker default

		wm_announce "The Axis have intercepted the stolen gold crate!"

		wm_teamvoiceannounce 0 "goldrush_axis_gold1_returned"
		wm_teamvoiceannounce 1 "goldrush_allies_gold1_returned"
	}

	trigger captured
	{
		setstate axis_gold_cm_marker default
		setstate goldclip invisible
		setstate goldclip2 default

		trigger golddoor2 schnellzu
		wait 100
		alertentity golddoor2fake
		alertentity golddoor1fake
		trigger golddoor1 bewege
		trigger golddoor2 bewege
		wait 100
		trigger golddoor2 auf

		trigger game_manager objective_counter

		wm_announce "The Allies have secured a gold crate!"

		wm_objective_status 6 0 2
		wm_objective_status 6 1 1

		wm_teamvoiceannounce 0 "goldrush_axis_gold1_secured"
		wm_teamvoiceannounce 1 "goldrush_allies_gold1_secured"
	}
}

axis_gold2
{
	spawn
	{
		wait 200

		setstate axis_gold_captured2 invisible
		remove
	}

	trigger stolen
	{
		setstate axis_gold_cm_marker invisible

		wm_announce "The Allies have stolen a gold crate!"

		wm_teamvoiceannounce 0 "goldrush_axis_gold2_taken"
		wm_teamvoiceannounce 1 "goldrush_allies_gold2_taken"
	}

	trigger returned
	{
		setstate axis_gold_cm_marker default

		wm_announce "The Axis have intercepted the stolen gold crate!"

		wm_teamvoiceannounce 0 "goldrush_axis_gold2_returned"
		wm_teamvoiceannounce 1 "goldrush_allies_gold2_returned"
	}

	trigger captured
	{
		trigger game_manager objective_counter

		wm_announce "The Allies have secured a gold crate!"

		wm_objective_status 7 0 2
		wm_objective_status 7 1 1

		wm_teamvoiceannounce 0 "goldrush_axis_gold2_secured"
		wm_teamvoiceannounce 1 "goldrush_allies_gold2_secured"
	}
}

truckbed_trigger1
{
	spawn
	{
	}

	death
	{
		setstate axis_gold_red1 invisible
		setstate axis_gold_captured1 default

		trigger game_manager checkgame

		remove
	}
}

truckbed_trigger2
{
	spawn
	{
	}

	death
	{
		setstate axis_gold_red2 invisible
		setstate axis_gold_captured2 default

		trigger game_manager checkgame

		remove
	}
}

lever
{
	spawn
	{
	}

	trigger move_up
	{
		playsound sound/movers/switches/switch.wav
	}
	
	trigger move_down
	{
		playsound sound/movers/switches/butn2.wav
	}
}

lever_trigger
{
	spawn
	{
		accum 1 set 1
	}

	trigger up
	{
		accum 1 abort_if_not_equal 1
		accum 1 set 0

		trigger lever move_up
		trigger door2 move_up
		trigger door3 move_up

		alertentity door_open_trigger

		trigger sounds off

		wm_announce "The Loading Doors are Opening!"

		wm_objective_status 5 0 2
		wm_objective_status 5 1 1

		wait 2500

		setstate allies_lever_trigger invisible
		setstate axis_lever_trigger default

		trigger lever_trigger2	setaccum0

		
		//trigger golddoor1 auf
		//trigger golddoor2 auf
	}
	
	trigger setaccum1
	{
		accum 1 set 1
	}

}

sounds
{
	spawn
	{
	}

	off
	{
		wait 10000

		alertentity door_open_trigger
	}
	
	offer
	{
		wait 5000
		
		alertentity door_open_trigger
	}
}

lever_trigger2
{
	spawn
	{
		accum 2 set 1
	}
	
	trigger down
	{
		accum 2 abort_if_not_equal 0
		accum 2 set 1

		trigger lever move_down
		trigger door2 move_down
		trigger door3 move_down

		wm_announce "The Loading Doors are Closing!"

		wait 2500

		setstate allies_lever_trigger default
		setstate axis_lever_trigger invisible

		alertentity door_open_trigger

		trigger sounds offer

		trigger lever_trigger setaccum1

		//trigger golddoor1 zu
		//trigger golddoor2 zu
	}

	trigger setaccum0
	{
		accum 2 set 0
	}
}


door2
{
	spawn
	{
	}

	trigger move_up
	{
		wait 500

		playsound sound/movers/misc/big_gate1.wav

		wait 400

		playsound sound/movers/misc/big_gate2.wav looping forever

		gotomarker door2_uppos 32 wait

		stopsound

		playsound sound/movers/misc/big_gate3.wav
	}
	
	trigger move_down
	{
		wait 500

		playsound sound/movers/misc/big_gate1.wav

		wait 400

		playsound sound/movers/misc/big_gate2.wav looping forever

		gotomarker door2_downpos 32 wait

		stopsound

		playsound sound/movers/misc/big_gate3.wav
	}
}

door3
{
	spawn
	{
	}

	trigger move_up
	{
		wait 500

		playsound sound/movers/misc/big_gate1.wav

		wait 400

		playsound sound/movers/misc/big_gate2.wav looping forever

		gotomarker door3_uppos 32 wait

		stopsound

		playsound sound/movers/misc/big_gate3.wav
	}
	
	trigger move_down
	{
		wait 500

		playsound sound/movers/misc/big_gate1.wav

		wait 400

		playsound sound/movers/misc/big_gate2.wav looping forever

		gotomarker door3_downpos 32 wait

		stopsound

		playsound sound/movers/misc/big_gate3.wav
	}
}

golddoor1
{
	spawn
	{
	}

	trigger auf
	{
		wait 500

		playsound sound/movers/doors/door5_open.wav

		faceangles 0 270 0 3000

	}
	
	trigger zu
	{
		wait 500

		playsound sound/movers/doors/door5_close.wav

		faceangles 0 0 0 3000


	}

	trigger bewege
	{
		gotomarker golddoor1point 1000 wait
	}
}

golddoor2
{
	spawn
	{
	}

	trigger auf
	{
		wait 500

		playsound sound/movers/doors/door5_open.wav

		faceangles 0 270 0 3000

	}
	
	trigger zu
	{
		wait 500

		playsound sound/movers/doors/door5_close.wav

		faceangles 0 0 0 3000
		
	}

	trigger bewege
	{
		gotomarker golddoor2point 1000 wait
	}

	trigger schnellzu
	{
		faceangles 0 0 0 1
	}
}

elevator_trigger
{
	spawn
	{
	}

	trigger activate
	{
		trigger bottom_l_door close
		trigger bottom_r_door close

		wait 700

		trigger eldoor_l closelow
		trigger eldoor_r closelow

		wait 2000

		trigger eldoor_l move_up
		trigger eldoor_r move_up
		trigger elevator move_up

		wait 2500


		trigger top_l_door open
		trigger top_r_door open

		wait 700

		alertentity ding_trigger

		trigger eldoor_l openhigh
		trigger eldoor_r openhigh

		wait 1000


		wait 3000

		trigger top_l_door close
		trigger top_r_door close

		wait 700

		trigger eldoor_l closehigh
		trigger eldoor_r closehigh

		wait 2000

		trigger eldoor_l move_down
		trigger eldoor_r move_down
		trigger elevator move_down

		wait 2500

		trigger bottom_l_door open
		trigger bottom_r_door open

		wait 700

		trigger eldoor_l openlow
		trigger eldoor_r openlow
	}

}

elevator
{
	spawn
	{
	}

	trigger move_up
	{
		gotomarker elevator_uppos 100
	}

	trigger move_down
	{
		gotomarker elevator_downpos 100
	}
}

eldoor_l
{
	spawn
	{
	}

	trigger openlow
	{
		gotomarker eldoor_l_openlow 24
	}

	trigger closelow
	{
		gotomarker eldoor_l_closedlow 24
	}

	trigger move_up
	{
		gotomarker eldoor_l_closedhigh 100
	}

	trigger move_down
	{
		gotomarker eldoor_l_closedlow 100
	}

	trigger openhigh
	{
		gotomarker eldoor_l_openhigh 24
	}

	trigger closehigh
	{
		gotomarker eldoor_l_closedhigh 24
	}
}

eldoor_r
{
	spawn
	{
	}

	trigger openlow
	{
		gotomarker eldoor_r_openlow 24
	}

	trigger closelow
	{
		gotomarker eldoor_r_closedlow 24
	}

	trigger move_up
	{
		gotomarker eldoor_r_closedhigh 100
	}

	trigger move_down
	{
		gotomarker eldoor_r_closedlow 100
	}

	trigger openhigh
	{
		gotomarker eldoor_r_openhigh 24
	}

	trigger closehigh
	{
		gotomarker eldoor_r_closedhigh 24
	}


}

bottom_l_door
{
	spawn
	{
	}

	trigger open
	{
		gotomarker bottom_l_door_open 24
	}

	trigger close
	{
		gotomarker bottom_l_door_closed 24
	}
}

bottom_r_door
{
	spawn
	{
	}

	trigger open
	{
		gotomarker bottom_r_door_open 24
	}

	trigger close
	{
		gotomarker bottom_r_door_closed 24
	}
}

top_l_door
{
	spawn
	{
	}

	trigger open
	{
		gotomarker top_l_door_open 24
	}

	trigger close
	{
		gotomarker top_l_door_closed 24
	}
}

top_r_door
{
	spawn
	{
	}

	trigger open
	{
		gotomarker top_r_door_open 24
	}
	
	trigger close
	{
		gotomarker top_r_door_closed 24
	}
}

doorbutton
{
	spawn
	{
		wait 400
		trigger doorbutton setup

		constructible_class 2

		setstate axis_lever_trigger invisible
		setstate allies_lever_trigger invisible
	}

	trigger setup
	{
		setstate doorbutton_materials default
		setstate doorbutton_materials_clip default
	}

	buildstart final
	{
		setstate doorbutton_materials default
		setstate doorbutton_materials_clip default
	}

	built final
	{
		setstate axis_lever_trigger default
		setstate allies_lever_trigger default

		setstate doorbutton_materials invisible
		setstate doorbutton_materials_clip invisible
		setstate doorbutton_toi invisible

		setstate forwardbunkerflag invisible

		setstate forwardbunker_wo default

		accum 0 trigger_if_equal 0 forwardbunkerflag switchit

		setautospawn "Forward Bunker" 1		

		wm_announce "Allies have secured the forward bunker."
		wm_announce "Door Controls have been constructed."

		trigger golddoor1 auf

		wm_teamvoiceannounce 0 "construction_completed"
		wm_teamvoiceannounce 1 "construction_completed"
	}

	decayed final
	{
		setstate doorbutton_materials default
		setstate doorbutton_materials_clip default
	}

	death
	{
	}

	trigger remove
	{
		setstate doorbutton_toi invisible
		setstate doorbutton_materials invisible
		setstate doorbutton_materials_clip invisible

		remove
	}
}

