#ifndef NITMOD_ADMIN_H
#define NITMOD_ADMIN_H

/* Admin, bans, mutes, shrubbot/nitrox permissions */

#include "nitmod_types.h"
#include "nitmod_globals.h"

void G_WarnFireTeamPlayer(uint param_1,uint param_2);
void G_KickFireTeamPlayer(uint param_1,uint param_2);
void G_PrintBanners(void);
void G_PlayerBan(void);
void G_MakeReferee(void);
void G_RemoveReferee(void);
void G_MuteClient(void);
void G_UnMuteClient(void);
void G_refMute_cmd(uint32_t param_1,int param_2);
void G_refWarning_cmd(int param_1);
bool G_shrubbot_time(void);
uint32_t G_shrubbot_spec999(void);
uint32_t G_shrubbot_pause(uint32_t param_1);
uint32_t G_shrubbot_unpause(uint32_t param_1);
uint32_t G_shrubbot_shuffle(void);
uint32_t G_shrubbot_medpack(int param_1);
uint32_t G_shrubbot_ammopack(int param_1);
uint32_t G_shrubbot_news(uint32_t param_1,int param_2);
uint32_t G_shrubbot_swap_restart(void);
uint32_t G_shrubbot_swap(void);
uint32_t G_shrubbot_reset(uint32_t param_1,uint32_t param_2);
uint32_t G_shrubbot_nextmap(void);
uint32_t G_shrubbot_mute_check_part_6(char *param_1,char *param_2);
void G_shrubbot_print_part_8(uint32_t param_1);
uint32_t _shrubbot_command_permission(int param_1,uint32_t param_2);
uint32_t G_shrubbot_splata(int param_1);
uint32_t G_shrubbot_cancelvote(int param_1);
uint32_t G_shrubbot_passvote(int param_1);
uint32_t G_shrubbot_resetmyxp(int param_1);
void G_shrubbot_buffer_print_part_15(int param_1,uint32_t param_2);
uint32_t G_shrubbot_disguise_part_12(int param_1,int param_2);
uint32_t G_shrubbot_disguise(int param_1,int param_2);
uint32_t G_shrubbot_about(int param_1);
uint32_t G_shrubbot_revive_part_11(int param_1,int param_2);
uint32_t G_shrubbot_revive(int param_1,int param_2);
uint32_t G_shrubbot_admintest(int param_1);
uint32_t G_shrubbot_levinfo(int param_1,int param_2);
uint32_t G_shrubbot_give(int param_1,int param_2);
uint32_t G_shrubbot_warn(int param_1,int param_2);
uint32_t G_shrubbot_resetxp(int param_1,int param_2);
uint32_t G_shrubbot_rename(int param_1,int param_2);
uint32_t G_shrubbot_unban(int param_1,int param_2);
uint32_t G_shrubbot_spec(int param_1,int param_2);
uint32_t G_shrubbot_userdelete(int param_1,int param_2);
uint32_t G_shrubbot_orient(int param_1,int param_2);
uint32_t G_shrubbot_putteam(int param_1,int param_2);
uint32_t G_shrubbot_lock(int param_1,int param_2);
uint32_t G_shrubbot_unlock(int param_1,int param_2);
uint32_t G_shrubbot_levlist(int param_1);
void nitrox_SetAdminCommandPermissions(int param_1);
void nitrox_SetLevelCommandPermissions(int param_1);
int G_shrubbot_permission(int param_1,char *param_2);
bool _shrubbot_admin_higher(int param_1,int param_2);
void G_shrubbot_writeconfig_string(char *param_1,uint32_t param_2);
void G_shrubbot_writeconfig_int(uint32_t param_1,uint32_t param_2);
void G_shrubbot_readconfig_string(uint32_t param_1,char *param_2,uint param_3);
void G_shrubbot_readconfig_string_nico(uint32_t param_1,char *param_2,uint param_3);
void G_shrubbot_readconfig_int(uint32_t param_1,long *param_2);
uint32_t _shrubbot_level(int param_1);
void _shrubbot_log(int param_1,uint32_t param_2,int param_3);
void G_shrubbot_duration(uint param_1,uint32_t param_2,uint32_t param_3);
int G_shrubbot_ban_check(char *param_1,char *param_2,int param_3,char *param_4);
longlong G_shrubbot_mute_check(uint32_t param_1,uint param_2);
void G_shrubbot_greeting(int param_1);
uint32_t G_shrubbot_tempban(int param_1,char *param_2,int param_3);
uint32_t G_shrubbot_kick_part_9(int param_1,int param_2);
uint32_t G_shrubbot_kick(int param_1,int param_2);
int MuteNumbersFromString(char *param_1,int *param_2);
uint32_t G_MatchOneMute(int *param_1,char *param_2,uint param_3);
uint32_t G_shrubbot_lockteams(int param_1,int param_2,int param_3);
void G_shrubbot_print_chat(int param_1,uint32_t param_2);
uint32_t G_shrubbot_records(uint32_t param_1);
uint32_t G_shrubbot_uptime(uint32_t param_1);
uint32_t G_shrubbot_delrecords(int param_1,int param_2);
void G_shrubbot_print(int param_1,uint32_t param_2);
uint32_t G_shrubbot_cmd_check(int param_1);
uint32_t G_shrubbot_setlevel(int param_1,int param_2);
uint32_t G_shrubbot_ban(int param_1,int param_2);
uint32_t G_shrubbot_mute(int param_1,int param_2);
uint32_t G_shrubbot_unmute(int param_1,int param_2);
uint32_t G_shrubbot_splat(int param_1,int param_2);
uint32_t G_shrubbot_gibme(int param_1);
uint32_t G_shrubbot_slap(int param_1,int param_2);
uint32_t G_shrubbot_panzerwar(int param_1,int param_2);
uint32_t G_shrubbot_sniperwar(int param_1,int param_2);
uint32_t G_shrubbot_poison(int param_1,int param_2);
uint32_t G_shrubbot_blind(int param_1,int param_2);
uint32_t G_shrubbot_unblind(int param_1,int param_2);
uint32_t G_shrubbot_glow(int param_1,int param_2);
uint32_t G_shrubbot_pants(int param_1,int param_2);
uint32_t G_shrubbot_freeze(int param_1,int param_2);
uint32_t G_shrubbot_unfreeze(int param_1,int param_2);
uint32_t G_shrubbot_burn(int param_1,int param_2);
uint32_t G_shrubbot_lol(int param_1,int param_2);
uint32_t G_shrubbot_pop(int param_1,int param_2);
uint32_t G_shrubbot_pip(int param_1,int param_2);
uint32_t G_shrubbot_fling(int param_1,int param_2);
uint32_t G_shrubbot_disorient(int param_1,int param_2);
uint32_t G_shrubbot_finger(int param_1,int param_2);
uint32_t G_shrubbot_leveledit(int param_1,int param_2);
int G_shrubbot_banguid(int param_1,int param_2);
uint32_t G_shrubbot_useredit(int param_1,int param_2);
uint32_t G_shrubbot_seen(int param_1,int param_2);
uint32_t G_shrubbot_levdelete(int param_1,int param_2);
uint32_t G_shrubbot_levadd(int param_1,int param_2);
uint32_t G_shrubbot_listplayers(int param_1);
uint32_t G_shrubbot_stats(int param_1);
uint32_t G_shrubbot_userinfo(int param_1,int param_2);
uint32_t G_shrubbot_showbans(int param_1,int param_2);
uint32_t G_shrubbot_userlist(int param_1,int param_2);
void G_shrubbot_buffer_begin(void);
void G_shrubbot_buffer_end(int param_1);
uint32_t G_shrubbot_help(int param_1,int param_2);
void G_shrubbot_buffer_print(int param_1,uint32_t param_2);
void G_shrubbot_cleanup(void);
uint32_t G_shrubbot_level(int param_1);
void UpdateIPBans(int param_1);
bool G_FilterIPBanPacket(char *param_1);
void AddIPBan(char *param_1);
void G_ProcessIPBans(void);
void ClearMaxLivesBans(void);
uint32_t G_Kick_v(int param_1,uint32_t param_2,int param_3,uint32_t param_4,int param_5);
uint32_t G_Mute_v(int param_1,uint32_t param_2,int param_3,uint32_t param_4,int param_5);
uint32_t G_UnMute_v(int param_1,uint32_t param_2,int param_3,uint32_t param_4,int param_5);
G_Referee_v(int param_1,uint32_t param_2,int param_3,uint32_t param_4,uint32_t param_5);
G_Unreferee_v(int param_1,uint32_t param_2,int param_3,uint32_t param_4,uint32_t param_5);
uint32_t G_Mutespecs_v(int param_1,int param_2,int param_3,char *param_4,uint32_t param_5);
void G_CanisterKick(uint32_t *param_1);
uint32_t _et_G_shrubbot_level(uint32_t param_1);
uint32_t _et_G_shrubbot_permission(uint32_t param_1);
void Nit_AdminChat(int param_1);
void nitrox_InitBansTable(void);
void nitrox_InitMutesTable(void);
void nitrox_LoadBans(void);
void nitrox_LoadMutes(void);
void nitrox_SaveBans(uint32_t param_1,uint32_t param_2);
void nitrox_SaveMutes(uint32_t param_1,uint32_t param_2);
void nitrox_SaveSingleBan(uint32_t param_1,uint32_t param_2);
void nitrox_SaveSingleMute(uint32_t param_1,uint32_t param_2);
void nitrox_InitAdminSystem(void);
void nitrox_ClearExpiredBans(void);
void nitrox_ClearExpiredMutes(void);
void nitrox_SetAdminPointers(int param_1,int param_2);
uint32_t nitrox_GetAdminLevel(int param_1,int param_2);
void nitrox_SetAdminPermissions(int param_1);
void nitrox_SetLevelPermissions(int param_1);
bool nitrox_CheckPermission(int param_1,int param_2);
bool nitrox_CheckCommandPermission(int param_1,int param_2);

#endif

