#ifndef NITMOD_UNKNOWN_H
#define NITMOD_UNKNOWN_H

/* Unnamed or unclassified Ghidra functions */

#include "nitmod_types.h"
#include "nitmod_globals.h"

void unk_func_00021be0(void);
void renameWalkTrigger_isra_170(uint32_t param_1,int param_2,int *param_3);
void __x86_get_pc_thunk_bx(void);
void __x86_get_pc_thunk_cx(void);
uint32_t SkillForClass(int param_1);
void ConcatArgs(int param_1);
void __fastAddPointToBounds(float *param_1,float *param_2,float *param_3);
void DoClientThinks(int param_1);
void P_WorldEffects(int param_1);
void PushBot(int *param_1,int param_2);
uint32_t ReadyToConstruct(int param_1,int param_2,int param_3);
void WolfFindMedic(uint32_t *param_1);
void BodyUnlink(uint32_t *param_1);
void AddExtraSpawnAmmo(int param_1,int param_2);
AddWeaponToPlayer_constprop_8(int param_1,int param_2,uint32_t param_3,uint32_t param_4);
uint32_t SpotWouldTelefrag(int param_1);
int SelectNearestDeathmatchSpawnPoint(float *param_1);
int SelectRandomDeathmatchSpawnPoint(void);
void SelectSpawnPoint(float *param_1,uint32_t *param_2,uint32_t *param_3);
uint32_t SelectSpectatorSpawnPoint(uint32_t *param_1,uint32_t *param_2);
void InitBodyQue(void);
void limbo(int param_1,int param_2);
uint64_t TeamCount(int param_1,int param_2);
uint64_t PickTeam(int param_1);
AddWeaponToPlayer(int param_1,int param_2,uint32_t param_3,uint32_t param_4,int param_5);
void AddMedicTeamBonus(int param_1);
void SetWolfSpawnWeapons_part_5(int param_1);
void SetWolfSpawnWeapons(int param_1,int param_2);
int GetIPLength(char *param_1);
bool CompareIPNoPort(char *param_1,char *param_2);
uint32_t IsFakepConnection(int param_1,char *param_2,char *param_3,uint32_t param_4);
bool IsValidIP(byte *param_1);
void respawn(int param_1);
void reinforce(int param_1);
void Censor_Force_Suicide(int param_1);
uint32_t CheatsOk(int param_1);
void DecolorString(char *param_1,char *param_2);
void SanitizeString(char *param_1,char *param_2,int param_3);
void ExecGive(int param_1,byte *param_2,char *param_3,char *param_4);
uint32_t Do_Activate_f(uint32_t *param_1,int param_2);
SetTeam(uint32_t *param_1,uint32_t param_2,int param_3,int param_4,int param_5,int param_6);
void StopFollowing(uint32_t *param_1);
void SetPlayerSpawn(int param_1,uint param_2,int param_3);
int SortStats(int *param_1,int *param_2);
void body_die(int param_1);
void AddScore(int param_1,int param_2);
void AddKillScore(int param_1,int param_2);
void TossClientItems(int param_1);
void GibEntity(int param_1,int param_2);
uint IsHeadShotWeapon(uint32_t param_1);
bool IsLegShot(uint32_t *param_1,float *param_2,float *param_3,uint32_t param_4);
bool IsArmShot(int param_1,uint32_t param_2,float *param_3,uint32_t param_4);
bool CanDamage(uint8_t *param_1,uint32_t param_2);
void RespawnItem(int param_1);
void FinishSpawningItem(uint32_t *param_1);
uint32_t AddToClip(int param_1,int param_2,int param_3,int param_4);
void Fill_Clip(int param_1,int param_2);
bool Add_Ammo(int param_1,int param_2,int param_3,int param_4);
void AddMagicAmmo(int param_1,uint32_t param_2);
uint32_t Pickup_Powerup(int param_1,int param_2);
uint32_t Pickup_Health(int param_1,int param_2);
void dropWeapon(uint32_t *param_1,uint32_t param_2,uint32_t param_3,uint32_t param_4);
int Drop_Item(int *param_1,uint32_t *param_2,float param_3,int param_4);
uint SortRanks(int *param_1,int *param_2);
char * strcut(char *param_1,char *param_2,int param_3);
void bani_clearmapxp(void);
void bani_storemapxp(void);
void bani_getmapxp(void);
void SendScoreboardMessageToAllClients(void);
void MoveClientToIntermission(int param_1);
void FindIntermissionPoint(void);
void BeginIntermission(void);
void ExitLevel(void);
void LogExit_part_6(uint32_t param_1);
uint32_t LogExit(uint32_t param_1);
void CheckIntermissionExit(void);
bool ScoreIsTied(void);
void CheckExitRules(void);
void CalculateRanks(int param_1);
void CheckWolfMP(void);
void CheckVote(void);
void InitCensorStructure(void);
void InitCensorNamesStructure(void);
void InitSkillLevelStructure(int param_1);
void CheckCvars(void);
uint32_t vmMain(uint32_t param_1,int param_2,uint32_t param_3,uint32_t param_4);
bool IsClass(int param_1,int param_2);
uint EntHasAdren(int param_1);
void firetrail_use(int param_1);
void use_corona(int param_1);
void InitShooter_Finish(int param_1);
void constructiblemarker_setup(int param_1);
void locateCamera(int param_1);
void dlight_finish_spawning(uint32_t *param_1);
void landmine_setup(uint32_t *param_1);
void shutoff_dlight(int param_1);
void use_spotlight(int param_1);
void locateMaster(int param_1);
void use_dlight(int param_1);
void TeleportPlayer(int param_1,uint32_t *param_2,uint32_t param_3);
void spotlight_finish_spawning(int param_1);
void InitShooter(int param_1,uint32_t param_2);
void clamp_playerbehindgun(int param_1,int param_2);
void clamp_hweapontofirearc(int param_1,float *param_2);
void Flak_Animate(int param_1);
long double AngleDifference(float param_1,float param_2);
char * stristr(char *param_1,char *param_2);
uint FindClientByName(char *param_1);
void __x86_get_pc_thunk_dx(void);
void Homing_Missile_Think(int param_1);
void Destabilize_Missile(int param_1);
void Guided_Missile_Think(int param_1);
void DynaSink(int param_1);
void DynaFree_part_3(int param_1);
void DynaFree(int param_1);
uint32_t CheckForSmoke_part_4(uint32_t param_1,uint32_t param_2);
void LandminePostThink(int param_1);
void Landmine_Check_Ground(uint32_t *param_1);
int fire_flamechunk(uint32_t *param_1,uint32_t *param_2,float *param_3);
void LandMineTrigger(int param_1);
void LandMinePostTrigger(int param_1);
uint32_t CheckForSmoke(uint32_t param_1,uint32_t param_2);
uint32_t sEntWillTriggerMine(int param_1,int param_2);
int fire_grenade(uint32_t *param_1,uint32_t *param_2,float *param_3,int param_4);
int fire_rocket(uint32_t *param_1,uint32_t *param_2,float *param_3,int param_4);
int fire_flamebarrel(uint32_t *param_1,uint32_t *param_2,float *param_3);
void fire_mortar(uint32_t *param_1,uint32_t *param_2,float *param_3);
void BecomeExplosion(int param_1);
void info_limbo_camera_setup(int param_1);
void Static_Pain(int param_1,int param_2);
void use_invisible_user(int param_1,int param_2);
void finishSpawningKeyedMover(int param_1);
void Blocked_DoorRotate(int param_1,int param_2);
void Reached_TrinaryMover(int param_1);
void Reached_Train(int param_1);
void Reached_Train_rotating(int param_1);
void Blocked_Door(int param_1,int param_2);
void Reached_BinaryMover(int param_1);
void ReturnToPos1Rotate(int param_1);
void GotoPos3(int param_1);
void ReturnToPos1(int param_1);
void ReturnToPos2(int param_1);
void SetMoverState(int param_1,uint32_t param_2,uint32_t param_3);
void MatchTeam(int param_1,uint32_t param_2,uint32_t param_3);
void MatchTeamReverseAngleOnSlaves(int param_1,uint32_t param_2,uint32_t param_3);
bool IsBinaryMoverBlocked(int param_1,int param_2,int param_3);
void InitMover(int param_1);
void InitMoverRotate(int param_1);
uint32_t findNonAIBrushTargeter(int param_1);
void Door_reverse_sounds(int param_1);
void DoorSetSounds(int param_1,uint32_t param_2);
void SpawnPlatTrigger(int param_1);
void ThrowDebris(void);
void InitExplosive(int param_1);
void InitConstructible(int param_1);
void Psparks_think(void);
void flippy_table_animate(void);
void DropToFloorG(uint32_t *param_1);
void DropToFloor(uint32_t *param_1);
void PGUNsparks_use(int param_1);
void OilSlick_remove_think(int param_1);
void dust_angles_think(int param_1);
void sparks_angles_think(int param_1);
void smokedust_use(int param_1);
void locker_tall_think(int param_1);
void dust_use(int param_1);
void crate_animate(int param_1);
void flippy_table_use(int *param_1,int param_2);
void touch_props_box_32(uint32_t *param_1,int param_2);
void touch_props_box_48(uint32_t *param_1,int param_2);
void touch_props_box_64(uint32_t *param_1,int param_2);
void touch_crate_64(uint32_t *param_1,int param_2);
void moveit(uint32_t *param_1,float param_2,float param_3);
void Psmoke_think(int param_1);
void propExplosionLarge(uint32_t *param_1);
void propExplosion(uint32_t *param_1);
void InitProp(int param_1);
uint32_t Prop_Touch(uint32_t *param_1,int param_2,uint32_t param_3);
void Prop_Check_Ground(uint32_t *param_1);
void Spawn_Shard(int param_1,int param_2,uint32_t param_3,int param_4);
void crate_die(int param_1,uint32_t param_2);
void Just_Got_Thrown(uint32_t *param_1);
void Prop_Break_Sound(int param_1);
void barrel_smoke(int param_1);
void smoker_think(int param_1);
void OilParticles_think(int param_1);
void Delayed_Leak_Think(int param_1);
bool validOilSlickSpawnPoint(uint32_t *param_1,uint32_t *param_2);
void OilSlick_remove(uint32_t *param_1);
void init_locker(int param_1);
void mountedmg42_fire(int param_1);
int GetFieldIndex(uint32_t param_1);
uint32_t FieldExists(uint32_t param_1);
uint32_t GetFieldType(uint32_t param_1);
void jP_BuildEndgameStats(void);
void InitServerEntities(void);
uint32_t * GetServerEntity(int param_1);
uint32_t * GetFreeServerEntity(void);
uint32_t * CreateServerEntity(int param_1);
int * FindServerEntity(int param_1,int param_2,uint32_t param_3);
void CreateMapServerEntities(void);
void InitialServerEntitySetup(void);
uint32_t StringToFilter(char *param_1,uint32_t *param_2);
void PrintMaxLivesGUID(void);
void AddIP(int param_1,char *param_2);
void AddMaxLivesBan(char *param_1);
void AddMaxLivesGUID(uint32_t param_1);
uint32_t ConsoleChat(int param_1);
bool ConsoleCommand(void);
void dllEntry(uint32_t param_1);
uint32_t PASSFLOAT(uint32_t param_1);
void smoke_think(int param_1);
void smoke_toggle(int param_1);
void smoke_init(int param_1);
void checkpoint_use_think(int param_1);
void checkpoint_think(int param_1);
int Team_TouchEnemyFlag(uint32_t *param_1,int param_2,int param_3);
void team_wolf_objective_use(int param_1);
void objective_Register(int param_1);
void checkpoint_touch(int param_1,int param_2);
void checkpoint_use(int param_1,int param_2,int param_3);
void checkpoint_spawntouch(int param_1,int param_2);
void Team_InitGame(void);
int OtherTeam(int param_1);
char * TeamName(int param_1);
void PrintMsg(int param_1,char *param_2);
bool OnSameTeam(int param_1,int param_2);
void Team_FragBonuses(int param_1,uint32_t param_2,int param_3);
void Team_ResetFlag(int param_1);
uint32_t Team_TouchOurFlag(int param_1,int param_2,uint32_t param_3);
void Team_ResetFlags(void);
void Team_ReturnFlagSound(int param_1,uint32_t param_2,int param_3);
void Team_ReturnFlag(int param_1,int param_2);
void Team_DroppedFlagThink(int param_1);
uint32_t Pickup_Team(int param_1,int param_2);
int FindFarthestObjectiveIndex(float *param_1);
int SelectRandomTeamSpawnPoint(uint32_t param_1,int param_2,int param_3,int param_4);
void TeamplayInfoMessage(int param_1);
void CheckTeamStatus(void);
void multi_wait(int param_1);
int hurt_use(int param_1);
int removeprotection_use(int param_1);
void hurt_think(int param_1);
void removeprotection_think(int param_1);
void AimAtTarget(int param_1);
void heal_touch(int param_1,int param_2);
void constructible_indicator_think(int param_1);
void removeprotection_touch(int param_1,int param_2);
void hurt_touch(int param_1,int param_2);
void explosive_indicator_think(int param_1);
void ammo_touch(int param_1,int param_2);
void InitTrigger(int param_1);
void multi_trigger(int param_1,int param_2);
void AddRemap(uint32_t param_1,uint32_t param_2,uint32_t param_3);
uint32_t * BuildShaderStateConfig(void);
uint8_t * vtos(float *param_1);
uint8_t * vtosf(float *param_1);
bool infront(int param_1,int param_2);
void DebugLine(float *param_1,float *param_2,uint32_t param_3);
void MagicSink(int param_1);
void artilleryThink(int param_1);
void artilleryGoAway(int param_1);
void artilleryThink_real(int param_1);
void artilleryHintThink(int param_1);
void HandleEntsThatBlockConstructible_constprop_7(uint32_t param_1,int *param_2);
void AddLean(int param_1,float *param_2);
uint32_t jP_UnDoChargeCost(int param_1,uint32_t param_2,float param_3);
uint32_t jP_DoChargeCost(int param_1,float param_2);
uint32_t ReviveEntity(uint32_t *param_1,uint32_t *param_2);
int EntsThatRadiusCanDamage(float *param_1,float param_2,int param_3);
void AutoBuildConstruction(int *param_1);
uint32_t Engineer_MG42(int param_1,int param_2);
void artillerySpotterThink(uint32_t *param_1);
void SnapVectorTowards(float *param_1,float *param_2);
void EmitterCheck(int param_1,int param_2,int param_3);
void Bullet_Endpos_Pattern(uint32_t param_1,uint32_t param_2,float param_3,float *param_4);
void Bullet_Endpos(int param_1,float param_2,float *param_3);
void ThrowKnife(int param_1);
bool jP_CheckDisguise(int param_1);
uint8_t ClampChar(int param_1);
int ClampShort(int param_1);
int DirToByte(float *param_1);
void ByteToDir(uint param_1,uint32_t *param_2);
uint32_t ColorBytes3(float param_1,float param_2,float param_3);
uint32_t ColorBytes4(float param_1,float param_2,float param_3,float param_4);
void NormalizeColor(float *param_1,float *param_2);
uint32_t PlaneFromPoints(float *param_1,float *param_2,float *param_3,float *param_4);
void vectoangles(float *param_1,float *param_2);
void AnglesToAxis(float *param_1,float *param_2);
void AxisClear(uint32_t *param_1);
void AxisCopy(uint32_t *param_1,uint32_t *param_2);
void ProjectPointOnPlane(float *param_1,float *param_2,float *param_3);
void MakeNormalVectors(float *param_1,float *param_2,float *param_3);
void VectorRotate(float *param_1,float *param_2,float *param_3);
long double LerpAngle(float param_1,float param_2,float param_3);
void LerpPosition(float *param_1,float *param_2,float param_3,float *param_4);
void AngleSubtract(float param_1,float param_2);
void AnglesSubtract(float *param_1,float *param_2,float *param_3);
long double AngleMod(float param_1);
long double AngleNormalize2Pi(float param_1);
long double AngleNormalize360(float param_1);
uint AngleNormalizeInt(uint param_1);
long double AngleNormalize180(float param_1);
long double AngleDelta(float param_1,float param_2);
void SetPlaneSignbits(float *param_1);
long double RadiusFromBounds(float *param_1,float *param_2);
void ClearBounds(uint32_t *param_1,uint32_t *param_2);
void AddPointToBounds(float *param_1,float *param_2,float *param_3);
bool PointInBounds(float *param_1,float *param_2,float *param_3);
bool VectorCompare(float *param_1,float *param_2);
void VectorNormalize(float *param_1);
void VectorNormalizeFast(float *param_1);
long double VectorNormalize2(float *param_1,float *param_2);
void _VectorMA(float *param_1,float param_2,float *param_3,float *param_4);
long double _DotProduct(float *param_1,float *param_2);
void _VectorSubtract(float *param_1,float *param_2,float *param_3);
void _VectorAdd(float *param_1,float *param_2,float *param_3);
void _VectorCopy(uint32_t *param_1,uint32_t *param_2);
void _VectorScale(float *param_1,float param_2,float *param_3);
void CrossProduct(float *param_1,float *param_2,float *param_3);
long double VectorLength(float *param_1);
long double VectorLengthSquared(float *param_1);
long double Distance(float *param_1,float *param_2);
long double DistanceSquared(float *param_1,float *param_2);
void VectorInverse(float *param_1);
void Vector4Scale(float *param_1,float param_2,float *param_3);
void MatrixMultiply(float *param_1,float *param_2,float *param_3);
void AngleVectors(float *param_1,float *param_2,float *param_3,float *param_4);
void PerpendicularVector(float *param_1,float *param_2);
void RotatePointAroundVector(float *param_1,float *param_2,float *param_3,float param_4);
void RotateAroundDirection(float *param_1,float param_2);
void GetPerpendicularViewVector(float *param_1,float *param_2,float *param_3,float *param_4);
void ProjectPointOntoVector(float *param_1,float *param_2,float *param_3,float *param_4);
void ProjectPointOntoVectorBounded(float *param_1,float *param_2,float *param_3,float *param_4);
long double DistanceFromLineSquared(float *param_1,float *param_2,float *param_3);
long double DistanceFromVectorSquared(float *param_1,float *param_2,float *param_3);
long double vectoyaw(float *param_1);
void AxisToAngles(int param_1,float *param_2);
long double VectorDistance(float *param_1,float *param_2);
long double VectorDistanceSquared(float *param_1,float *param_2);
void SkipBracedSection_Depth(int *param_1,int param_2);
void SkipBracedSection(int *param_1);
void SkipRestOfLine(uint32_t *param_1);
void Parse1DMatrix(uint32_t param_1,uint param_2,int param_3);
void Parse2DMatrix(uint32_t param_1,int param_2,int param_3,int param_4);
void Parse3DMatrix(uint32_t param_1,int param_2,int param_3,int param_4,int param_5);
void va(char *param_1);
void tv(uint32_t param_1,uint32_t param_2,uint32_t param_3);
uint32_t encode64(byte *param_1,char *param_2,int param_3);
void decode64(int param_1);
uint32_t FileExists(uint32_t param_1);
uint32_t need_escape(byte *param_1);
byte * escape_string(byte *param_1);
void unescape_string(char *param_1);
uint32_t INTHandler(void);
void installcrashhandler(void);
void restorecrashhandler(void);
void installinthandler(void);
void linux_siginfo(int param_1,int param_2);
void handler(uint32_t param_1);
void linux_backtrace(int param_1);
void CrashHandler(int param_1,int param_2,uint32_t param_3);
void EnableStackTrace(void);
void DisableStackTrace(void);
int GeoIP_addr_to_num(int param_1);
uint8_t * GeoIP_seek_record(int param_1,uint param_2);
void GeoIP_open(void);
void GeoIP_close(void);
uint32_t _et_trap_FS_Write(uint32_t param_1);
uint32_t _et_FindSelf(int param_1);
uint32_t _et_G_PlayerCount(uint32_t param_1);
uint32_t _et_G_Print(uint32_t param_1);
uint32_t _et_RegisterModname(int param_1);
uint32_t _et_trap_FS_FOpenFile(uint32_t param_1);
uint32_t _et_trap_FS_FCloseFile(uint32_t param_1);
uint32_t _et_trap_FS_Read(uint32_t param_1);
uint32_t _et_trap_Cvar_Get(uint32_t param_1);
uint32_t _et_G_XP_Set(uint32_t param_1);
uint32_t _et_G_AdminLevelName(uint32_t param_1);
uint32_t _et_G_AddEvent(uint32_t param_1);
uint32_t _et_trap_UnlinkEntity(uint32_t param_1);
uint32_t _et_trap_LinkEntity(uint32_t param_1);
void _et_G_EntitiesFree(void);
uint32_t _et_G_FreeEntity(uint32_t param_1);
uint32_t _et_G_Spawn(uint32_t param_1);
uint32_t _et_G_LoseSkillPoints(uint32_t param_1);
uint32_t _et_G_AddSkillPoints(uint32_t param_1);
uint32_t _et_ClientIsFlooding(uint32_t param_1);
uint32_t _et_G_Damage(uint32_t param_1);
uint32_t _et_trap_Milliseconds(uint32_t param_1);
uint32_t _et_G_ClientSound(uint32_t param_1);
uint32_t _et_G_Sound(uint32_t param_1);
uint32_t _et_G_globalSound(uint32_t param_1);
uint32_t _et_G_ModelIndex(uint32_t param_1);
uint32_t _et_G_SoundIndex(uint32_t param_1);
uint32_t _et_trap_FS_Rename(uint32_t param_1);
uint32_t _et_Q_CleanStr(uint32_t param_1);
uint32_t _et_Info_ValueForKey(uint32_t param_1);
uint32_t _et_Info_SetValueForKey(uint32_t param_1);
uint32_t _et_Info_RemoveKey(uint32_t param_1);
uint32_t _et_trap_SetUserinfo(uint32_t param_1);
uint32_t _et_trap_GetUserinfo(uint32_t param_1);
uint32_t _et_ClientNumberFromString(uint32_t param_1);
uint32_t _et_ClientUserinfoChanged(uint32_t param_1);
uint32_t _et_G_Say(uint32_t param_1);
uint32_t _et_trap_SendServerCommand(uint32_t param_1);
uint32_t _et_trap_DropClient(uint32_t param_1);
uint32_t _et_trap_SendConsoleCommand(uint32_t param_1);
uint32_t _et_trap_SetConfigstring(uint32_t param_1);
uint32_t _et_trap_GetConfigstring(uint32_t param_1);
uint32_t _et_trap_Cvar_Set(uint32_t param_1);
uint32_t _et_trap_Argv(uint32_t param_1);
uint32_t _et_trap_Argc(uint32_t param_1);
uint32_t _et_ConcatArgs(uint32_t param_1);
uint32_t _et_FindMod(uint32_t param_1);
uint32_t _et_G_GetSpawnVar(uint32_t param_1);
void LOG(char *param_1);
uint32_t _et_G_LogPrint(uint32_t param_1);
uint32_t _et_IPCSend(int param_1);
uint8_t * _et_gentity_getfield(int param_1,uint32_t param_2);
void _et_gentity_getvec3(uint32_t param_1,float *param_2);
void _et_gentity_setvec3(uint32_t param_1,float *param_2);
uint32_t _et_G_SetSpawnVar(uint32_t param_1);
uint32_t _et_G_TempEntity(uint32_t param_1);
void _et_gentity_gettrajectory(uint32_t param_1,uint32_t *param_2);
void _et_gentity_settrajectory(uint32_t param_1,uint32_t *param_2);
uint32_t _et_gentity_set(uint32_t param_1);
void _et_gentity_getweaponstats(uint32_t param_1,uint32_t *param_2);
uint32_t _et_gentity_get(uint32_t param_1);
void SHA1Reset(uint32_t *param_1);
void SHA1ProcessMessageBlock(uint *param_1);
int SHA1Input(int param_1,uint8_t *param_2,int param_3);
uint64_t SHA1Result(int param_1);
void SHA1PadMessage(int param_1);
uint8_t * in_word_set(byte *param_1,uint param_2);
uint32_t putVarint64(byte *param_1,uint param_2,uint param_3);
uint64_t findElementWithHash(uint *param_1,byte *param_2,uint *param_3);
int unixFileLock(int param_1,uint32_t param_2);
uint32_t nolockCheckReservedLock(uint32_t param_1,uint32_t *param_2);
uint32_t nolockLock(void);
uint32_t nolockUnlock(void);
uint32_t dotlockCheckReservedLock(int param_1,uint *param_2);
void unixShmBarrier(void);
uint8_t * posixIoFinderImpl(void);
uint8_t * nolockIoFinderImpl(void);
uint8_t * dotlockIoFinderImpl(void);
int databaseIsUnmoved(int param_1);
uint32_t getPageError(int param_1,uint32_t param_2,uint32_t *param_3);
ulonglong cellSizePtr(int param_1,int param_2);
int cellSizePtrNoPayload(uint32_t param_1,int param_2);
uint64_t finalDbSize(int param_1,uint param_2,int param_3);
uint16_t computeCellSize(int param_1,int param_2);
uint cachedCellSize(int param_1,int param_2);
longlong doubleToInt64(double param_1);
uint64_t memIntValue(int param_1);
uint32_t memjrnlSync(void);
uint32_t memjrnlFileSize(int param_1,uint32_t *param_2);
uint32_t incrAggDepth(int param_1,char *param_2);
uint32_t heightOfSelect(int param_1,int *param_2);
void exprSetHeight(int param_1);
bool gatherSelectWindowsSelectCallback(int param_1,int param_2);
void setDoNotMergeFlagOnCopy(int *param_1);
uint32_t selectSrcCount(int param_1,int param_2);
uint32_t renameUnmapExprCb(int *param_1,int param_2);
uint32_t renameTableExprCb(int *param_1,char *param_2);
void recomputeColumnsNotIndexed(int param_1);
bool pragmaVtabEof(int param_1);
uint32_t pragmaVtabRowid(int param_1,uint32_t *param_2);
void selectPopWith(int *param_1,int param_2);
void disableTerm(int *param_1,int *param_2);
uint32_t exprUsesSrclistSelectCb(void);
uint whereLoopCheaperProperSubset(int param_1,int param_2);
uint * whereLoopFindLesser(uint *param_1,uint *param_2);
void noopStepFunc(void);
void noopValueFunc(void);
uint keywordCode(byte *param_1,uint param_2,uint *param_3);
void identPut(int param_1,int *param_2,byte *param_3);
uint32_t getToken(int *param_1);
uint32_t memjrnlRead(int param_1,uint32_t *param_2,uint param_3,uint param_4,int param_5);
uint8_t * unixNextSystemCall(uint32_t param_1,char *param_2);
uint8_t * unixGetSystemCall(uint32_t param_1,char *param_2);
int getDigits(byte *param_1,char *param_2);
void unixGetpagesize(void);
int robust_ftruncate(uint32_t param_1,uint32_t param_2,uint32_t param_3);
int unixGetLastError(void);
uint32_t unixCheckReservedLock(int param_1,uint *param_2);
void posixOpen(char *param_1,int param_2,uint32_t param_3);
int unixRead(int param_1,uint32_t *param_2,uint param_3,uint param_4,int param_5);
uint32_t unixCurrentTimeInt64(uint32_t param_1,longlong *param_2);
int unixSleep(uint32_t param_1,int param_2);
void unixDlClose(uint32_t param_1,uint32_t param_2);
void unixDlSym(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void unixDlOpen(uint32_t param_1,uint32_t param_2);
int binCollFunc(uint32_t param_1,size_t param_2,void *param_3,size_t param_4,void *param_5);
int rtrimCollFunc(uint32_t param_1,size_t param_2,void *param_3,size_t param_4,void *param_5);
void getCellInfo(int param_1);
int readSuperJournal(int *param_1,char *param_2,uint param_3);
uint32_t memRealValue(int param_1);
uint32_t robustFchown(uint32_t param_1,uint32_t param_2,uint32_t param_3);
uint unixDeviceCharacteristics(int param_1);
uint32_t unixUnfetch(int param_1,uint32_t param_2,uint32_t param_3,int param_4);
uint32_t unixAccess(uint32_t param_1,uint32_t param_2,int param_3,uint *param_4);
void setSectorSize(int param_1);
int allocSpace_part_138(int *param_1,int param_2,uint param_3,int param_4);
uint32_t selectWindowRewriteSelectCb(int param_1,int param_2);
uint32_t impliesNotNullRow(int param_1,uint8_t *param_2);
uint32_t exprSrcCount(int param_1,char *param_2);
uint32_t exprIdxCover(int param_1,char *param_2);
isDupColumn_isra_180(int *param_1,int *param_2,int param_3,int param_4,int *param_5,int param_6);
uint32_t exprColumnFlagUnion(int param_1,char *param_2);
uint32_t checkConstraintExprNode(int param_1,char *param_2);
uint32_t pragmaVtabBestIndex(int param_1,int *param_2);
byte exprUsesSrclistCb(int param_1,char *param_2);
uint32_t exprNodeIsDeterministic(int param_1,char *param_2);
uint32_t resolveRemoveWindowsCb(uint32_t param_1,int param_2);
void computeYMD_part_280(uint *param_1);
void computeJD_part_281(longlong *param_1);
uint32_t unixSetSystemCall(uint32_t param_1,char *param_2,uint8_t *param_3);
char * columnTypeImpl(int param_1,char *param_2);
uint32_t parseHhMmSs(int param_1,int param_2);
uint32_t dotlockUnlock(int param_1,uint param_2);
uint32_t unixFileSize(int param_1,int *param_2);
byte unk_func_0012bb9b(byte *param_1);
uint64_t findElementWithHash_constprop_705(uint *param_1,byte *param_2);
int unixSectorSize(int param_1);
uint32_t unixCurrentTime(uint32_t param_1,double *param_2);
uint32_t recomputeColumnsUsedExpr(int param_1,char *param_2);
void applyNumericAffinity(longlong *param_1,int param_2);
void invokeProfileCallback(int *param_1,int param_2);
uint32_t setupLookaside(int param_1,int *param_2,uint param_3,int param_4);
void rowSetTreeToList(int param_1,int *param_2,int *param_3);
bool exprExistsToInIter(uint32_t *param_1,uint32_t *param_2);
void measureAllocationSize(int param_1,uint param_2);
void renameWalkWith_isra_274(int *param_1,int *param_2);
uint32_t renameUnmapSelectCb(int *param_1,int param_2);
uint32_t renameTableSelectCb(int *param_1,int param_2);
void computeYMD_HMS(uint *param_1);
int rowSetNDeepTree(int *param_1,int param_2);
uint * rowSetEntrySort(uint *param_1);
void updateRangeAffinityStr(char *param_1,int param_2,int param_3);
uint32_t exprNodeIsConstant(int param_1,byte *param_2);
int dotlockLock(int param_1,uint8_t param_2);
uint32_t unixWrite(int param_1,int param_2,uint param_3,uint param_4,int param_5);
uint64_t getIntArg(int *param_1);
void srclistRenumberCursors_constprop_602(int param_1,int param_2,int *param_3);
uint patternCompare(byte *param_1,byte *param_2,byte *param_3,uint param_4);
void whereLoopOutputAdjust(int param_1,uint *param_2,short param_3);
int dupedExprSize(char *param_1,uint param_2);
uint subjournalPageIfRequired(int param_1);
uint32_t unixShmLock(int param_1,int param_2,int param_3,byte param_4);
uint32_t pragmaVtabDisconnect(int param_1);
uint32_t memjrnlClose(int param_1);
int nocaseCollatingFunc(uint32_t param_1,int param_2,byte *param_3,int param_4,byte *param_5);
uint32_t analysisLoader(int param_1,uint32_t param_2,int *param_3);
int unixLock(int param_1,int param_2);
void unsetJoinExpr(char *param_1,int param_2);
readJournalHdr(int param_1,int param_2,uint param_3,int param_4,uint *param_5,uint *param_6);
void statAccumDestructor(int *param_1);
int dbMallocRawFinish(int param_1,uint param_2,int param_3);
uint32_t whereIndexExprTransColumn(int param_1,char *param_2);
int exprINAffinity_isra_322(int param_1,int param_2);
int autoIncBegin(int *param_1,int param_2,int param_3);
triggerStepAllocate(int *param_1,uint8_t param_2,uint32_t *param_3,byte *param_4,int param_5);
uint32_t memjrnlTruncate(int param_1,uint param_2,int param_3);
uint32_t resizeIndexObject_part_318(int param_1,int param_2,int param_3);
void resolveP2Values(int param_1,int *param_2);
void agginfoFree(uint32_t param_1,int param_2);
uint32_t * dbReallocFinish(int param_1,uint32_t *param_2,uint param_3,int param_4);
uint32_t growOpArray_isra_291(int param_1);
uint32_t growOp3(int param_1);
uint32_t integrityCheckResultRow(int param_1);
uint32_t whereLoopResize_part_319(int param_1,int param_2,int param_3);
void resizeResolveLabel_isra_289(int *param_1,uint32_t *param_2,int param_3);
void releaseMemArray_part_283(uint param_1,int param_2);
uint apiHandleError(int param_1,uint param_2);
void last_insert_rowid(int *param_1);
void total_changes(int *param_1);
void changes(int *param_1);
void signFunc(int *param_1,uint32_t param_2,uint32_t *param_3);
int out2PrereleaseWithClear(int param_1);
void out2Prerelease_isra_285(int param_1,int param_2);
void callFinaliser(int param_1,int param_2);
void strAccumFinishRealloc(int *param_1);
int * withDup(int param_1,int *param_2);
char * exprDup_constprop_678(uint32_t param_1,char *param_2,int param_3);
char * exprDup_constprop_677(uint32_t param_1,char *param_2);
uint32_t propagateConstantExprRewrite(int param_1,char *param_2);
char * exprDup(uint32_t param_1,char *param_2,int param_3,int *param_4);
int * enlargeAndAppend(int *param_1,uint32_t *param_2,int *param_3);
explainAppendTerm(int param_1,int param_2,int param_3,int param_4,int param_5,uint8_t *param_6);
uint32_t * tokenExpr(int *param_1,uint8_t param_2,uint32_t *param_3,uint param_4);
uint64_t exprSelectUsage(uint32_t param_1,int param_2);
createAggContext_isra_305(uint32_t *param_1,uint32_t *param_2,uint param_3);
void row_numberStepFunc(int param_1);
void last_valueInvFunc(int param_1);
void countStep(int param_1,int param_2,int *param_3);
void countInverse(int param_1,int param_2,int *param_3);
void row_numberValueFunc(int *param_1);
void sumInverse(int param_1,uint32_t param_2,int *param_3);
void countFinalize(int *param_1);
void sumStep(int param_1,uint32_t param_2,int *param_3);
void totalFinalize(int *param_1);
void dense_rankStepFunc(int param_1);
void cume_distInvFunc(int param_1);
void percent_rankInvFunc(int param_1);
void ntileInvFunc(int param_1);
void avgFinalize(int *param_1);
void cume_distStepFunc(int param_1);
void percent_rankStepFunc(int param_1);
void cume_distValueFunc(int *param_1);
void rankStepFunc(int param_1);
void rankValueFunc(int *param_1);
void dense_rankValueFunc(uint32_t *param_1);
void percent_rankValueFunc(int *param_1);
void ntileValueFunc(int *param_1);
longlong localtimeOffset_isra_470(int param_1,uint32_t *param_2,uint32_t *param_3);
void absFunc(int *param_1,uint32_t param_2,uint32_t *param_3);
void sumFinalize(uint32_t *param_1);
void ntileStepFunc(int param_1,uint32_t param_2,uint32_t *param_3);
void zeroblobFunc(int *param_1,uint32_t param_2,uint32_t *param_3);
void setPragmaResultColumnNames(int *param_1,int param_2);
void last_valueValueFunc(int *param_1);
void nth_valueFinalizeFunc(int *param_1);
void last_valueFinalizeFunc(int *param_1);
void first_valueFinalizeFunc(int *param_1);
void minMaxValue(int *param_1);
void minMaxFinalize(int *param_1);
void sourceidFunc(int *param_1);
void versionFunc(int *param_1);
void typeofFunc(int *param_1,uint32_t param_2,int *param_3);
void compileoptiongetFunc(int *param_1,uint32_t param_2,uint32_t *param_3);
uint32_t computeNumericType(uint *param_1);
uint numericType(int param_1);
void groupConcatValue(int *param_1);
uint32_t pragmaVtabColumn(int *param_1,int *param_2,int param_3);
void statInit(int *param_1,uint32_t param_2,uint32_t *param_3);
void groupConcatFinalize(int *param_1);
void freeP4FuncCtx(int param_1,uint32_t *param_2);
void exprListDeleteNN_constprop_687(int *param_1);
void clearSelect_constprop_688(int param_1);
void upsertDelete_constprop_651(int *param_1);
void deleteTable_constprop_697(int *param_1);
void clearSelect(uint32_t param_1,int param_2,int param_3);
void exprListDeleteNN(int param_1,int *param_2);
void upsertDelete(uint32_t param_1,int *param_2);
void whereInfoFree(uint32_t param_1,int param_2);
uint32_t agginfoPersistExprCb(int *param_1,char *param_2);
int * exprListAppendList(uint32_t param_1,int *param_2,int *param_3,int param_4);
int whereClauseInsert(uint32_t *param_1,int param_2,ushort param_3);
void deleteTable(int param_1,int *param_2);
uint32_t * yy_destructor(int param_1,uint16_t param_2,int *param_3);
void freeP4Mem(int param_1,uint32_t *param_2);
void freeP4(int param_1,uint32_t param_2,int param_3);
void codeReal(int *param_1,char *param_2,int param_3,uint32_t param_4);
void codeApplyAffinity_isra_340(uint32_t param_1,int param_2,int param_3,char *param_4);
void renameReloadSchema(int *param_1,int param_2,uint16_t param_3);
void returnSingleText(int *param_1,int param_2);
uint32_t whereLoopInsert(int *param_1,uint *param_2);
uint32_t * printfTempBuf(int *param_1,uint param_2,int param_3);
uint valueToText(uint *param_1,byte param_2);
uint32_t valueBytes(int param_1);
void groupConcatInverse(int param_1,int param_2,int *param_3);
uint32_t getTextArg(int *param_1);
void statPush(int *param_1,uint32_t param_2,uint32_t *param_3);
void hexFunc(int *param_1,uint32_t param_2,int *param_3);
void lengthFunc(int *param_1,uint32_t param_2,int *param_3);
void printfFunc(int *param_1,int param_2,int param_3);
void substrFunc(int *param_1,int param_2,int *param_3);
void upperFunc(int *param_1,uint32_t param_2,int *param_3);
void lowerFunc(int *param_1,uint32_t param_2,int *param_3);
void likeFunc(int *param_1,int param_2,int *param_3);
void compileoptionusedFunc(int *param_1);
void unicodeFunc(int *param_1);
void replaceFunc(int *param_1,uint32_t param_2,int *param_3);
void trimFunc(int *param_1,int param_2,int *param_3);
void groupConcatStep(int *param_1,int param_2,int *param_3);
void minmaxStep(int *param_1,uint32_t param_2,int *param_3);
void minmaxFunc(int *param_1,int param_2,int *param_3);
void nullifFunc(int *param_1,uint32_t param_2,uint32_t *param_3);
uint applyAffinity(double *param_1,char param_2,byte param_3);
void unixDlError(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void statGet(int param_1,uint32_t param_2,uint32_t *param_3);
void quoteFunc(int *param_1,uint32_t param_2,int *param_3);
uint32_t freeSpace(int param_1,uint param_2,ushort param_3);
int pageFindSlot(int param_1,int param_2,uint32_t *param_3);
void verifyDbFile(int param_1);
void errlogFunc(uint32_t param_1,uint32_t param_2,uint32_t *param_3);
int robust_open(uint32_t param_1,uint param_2,uint param_3);
unixLogErrorAtLine(uint32_t param_1,uint32_t param_2,uint8_t *param_3,uint32_t param_4);
int unixLockSharedMemory(int param_1,int param_2);
void dropCell_part_439(int param_1,int param_2,uint param_3,int *param_4);
uint32_t defragmentPage(int param_1,int param_2);
int ptrmapGet(int *param_1,uint param_2,char *param_3,uint *param_4);
int getOverflowPage(int *param_1,uint param_2,int *param_3,uint *param_4);
int readDbPage(int param_1);
accessPayload_constprop_589(int param_1,uint param_2,uint param_3,uint32_t *param_4);
int saveCursorPosition_part_490(char *param_1);
int saveCursorsOnList(byte *param_1,int param_2,byte *param_3);
int saveCursorsOnList_constprop_588(byte *param_1);
int moveToChild(int param_1,uint param_2);
getAndInitPage_constprop_562(int *param_1,uint param_2,int *param_3,uint32_t param_4);
int moveToRoot(byte *param_1);
void zeroPage(uint8_t *param_1,uint param_2);
int unixUnlock(int param_1,int param_2);
uint32_t nolockClose(uint16_t *param_1);
int moveToLeftmost(int param_1);
uint unixRandomness(uint32_t param_1,uint param_2,time_t *param_3);
uint32_t unixClose(uint16_t *param_1);
int accessPayloadChecked(char *param_1,uint32_t param_2,uint32_t param_3);
int handleMovedCursor(int param_1);
uint32_t dotlockClose(uint16_t *param_1);
uint32_t unixSync(int param_1);
void unixShmPurge(int param_1);
uint32_t unixShmUnmap(int param_1,int param_2);
bindText(int *param_1,int param_2,int param_3,uint32_t param_4,void *param_5,char param_6);
uint32_t unixDelete(uint32_t param_1,uint8_t *param_2,uint param_3);
uint32_t unixMapfile_part_408(int param_1,uint param_2,int param_3);
int unixFetch(int param_1,uint param_2,int param_3,uint param_4,int *param_5);
uint32_t openDirectory(uint32_t param_1,int *param_2);
void pageReinit(int param_1);
uint32_t unixTruncate(int param_1,uint param_2,int param_3);
void checkAppendMsg(int param_1,uint32_t param_2);
void checkPtrmap(int *param_1,uint param_2,char param_3,uint param_4);
int checkTreePage(int *param_1,uint param_2,uint *param_3,uint param_4,uint param_5);
void corruptSchema(int *param_1,uint32_t *param_2,char *param_3);
renameEditSql(int *param_1,int *param_2,char *param_3,char *param_4,int param_5);
valueFromExpr_constprop_623(int param_1,byte *param_2,char param_3,char param_4,int *param_5);
codeInteger_isra_380(uint32_t param_1,uint param_2,byte *param_3,int param_4,uint32_t param_5);
void addModuleArgument(int *param_1,uint32_t *param_2,int param_3);
notValidImpl_isra_388(uint32_t param_1,uint param_2,uint32_t param_3,uint8_t *param_4);
uint32_t havingToWhereExprCb(int *param_1,char *param_2);
uint32_t fixSelectCb(int param_1,int param_2);
uint32_t fixExprCb(int param_1,char *param_2);
whereLoopAddVirtual(uint32_t *param_1,uint param_2,uint param_3,uint param_4,uint param_5);
void parserDoubleLinkSelect(int *param_1,char *param_2);
int attachWithToSelect(uint32_t param_1,int param_2,int *param_3);
int * parserAddExprIdListTerm(int *param_1,uint32_t *param_2,int param_3,int param_4);
uint32_t isAlterableTable_isra_401(int *param_1,byte *param_2,uint *param_3);
void selectAddSubqueryTypeInfo(uint32_t param_1,int param_2);
char * substExpr(int *param_1,char *param_2);
void substExprList(uint32_t param_1,int *param_2);
pushDownWhereTerms(uint32_t param_1,int param_2,char *param_3,int param_4,int param_5);
multiSelectCollSeq_isra_425(uint32_t param_1,uint32_t *param_2,int param_3,int param_4);
void constInsert(uint32_t *param_1,int param_2,uint32_t param_3);
void findConstInWhere(uint32_t param_1,char *param_2);
uint32_t * multiSelectOrderByKeyInfo_constprop_603(int *param_1,int param_2);
whereRangeVectorLen_isra_424(uint32_t param_1,int param_2,int param_3,int param_4,int *param_5);
uint32_t convertCompoundSelectToSubquery(uint32_t param_1,char *param_2);
uint32_t whereUsablePartialIndex(int param_1,int param_2,int param_3,char *param_4);
void whereApplyPartialIndexConstraints(char *param_1,uint32_t param_2,int param_3);
uint32_t exprNodeIsConstantOrGroupBy(uint32_t *param_1,int param_2);
uint32_t whereIndexExprTransNode(int param_1,uint16_t *param_2);
byte selectWindowRewriteExprCb(uint32_t *param_1,byte *param_2);
uint32_t analyzeAggregate(int param_1,char *param_2);
resolveOrderGroupBy(uint32_t *param_1,int param_2,int *param_3,char *param_4);
int * whereScanNext(uint32_t *param_1);
void whereScanInitIndexExpr(int param_1);
int whereLoopAddBtreeIndex(uint32_t *param_1,int param_2,int param_3,short param_4);
uint32_t resolveSelectStep(int *param_1,int param_2);
exprMightBeIndexed2(int param_1,uint param_2,uint param_3,uint32_t *param_4,int param_5);
int whereLoopAddBtree(int *param_1,uint param_2,uint param_3);
uint32_t wherePathSolver(int *param_1,short param_2);
uint32_t gatherSelectWindowsCallback(int param_1,char *param_2);
int unixFullPathname(uint32_t param_1,char *param_2,int param_3,char *param_4);
void randomFunc(int *param_1);
uint32_t unixGetTempname(int param_1,uint8_t *param_2);
uint32_t pragmaVtabOpen(uint32_t param_1,uint32_t *param_2);
uint32_t resolveExprStep(int param_1,byte *param_2);
void loadExt(int *param_1,int param_2);
uint32_t isDate(int *param_1,int param_2,int *param_3,uint *param_4);
void strftimeFunc(int *param_1,int param_2,int param_3);
void datetimeFunc(int *param_1,uint32_t param_2,uint32_t param_3);
void timeFunc(int *param_1,uint32_t param_2,uint32_t param_3);
void dateFunc(int *param_1,uint32_t param_2,uint32_t param_3);
void juliandayFunc(int *param_1,uint32_t param_2,uint32_t param_3);
void roundFunc(int *param_1,int param_2,uint32_t *param_3);
void ctimestampFunc(int *param_1);
void cdateFunc(int *param_1);
void ctimeFunc(int *param_1);
void first_valueStepFunc(int param_1,uint32_t param_2,uint32_t *param_3);
void nth_valueStepFunc(int param_1,uint32_t param_2,uint32_t *param_3);
void instrFunc(int *param_1,uint32_t param_2,int *param_3);
void randomBlob(int *param_1,uint32_t param_2,uint32_t *param_3);
int memjrnlWrite(int *param_1,uint32_t *param_2,uint param_3,uint param_4,int param_5);
int unixOpen(int param_1,int *param_2,uint32_t *param_3,uint param_4,uint *param_5);
uint32_t unixFileControl(int param_1,uint32_t param_2,uint *param_3);
int unixShmMap(int param_1,int param_2,int param_3,int param_4,uint32_t *param_5);
int writeJournalHdr(int param_1);
int syncJournal(int param_1,int param_2);
backupOnePage_isra_479(int *param_1,int *param_2,uint param_3,int param_4,int param_5);
void backupUpdate(int param_1,uint param_2,uint32_t param_3);
codeEqualityTerm(int *param_1,int *param_2,int *param_3,uint param_4,uint param_5,int param_6);
int exprCodeVector(int *param_1,char *param_2,uint32_t *param_3);
void computeLimitRegisters(int param_1,int param_2,uint32_t param_3);
void codeExprOrVector(uint32_t param_1,char *param_2,int param_3,int param_4);
int exprAnalyze(int param_1,int *param_2,int param_3);
void reindexTable_part_527(int *param_1,int param_2,byte *param_3);
void reindexDatabases(int *param_1,uint32_t param_2);
void codeExprOrVector_constprop_594(uint32_t param_1,char *param_2,uint32_t param_3);
uint multiSelect(int *param_1,byte *param_2,int param_3);
uint32_t findBtree(uint32_t param_1,int param_2,uint32_t param_3);
int lockBtree(int *param_1);
int getPageMMap(int param_1,uint param_2,uint32_t *param_3,byte param_4);
int getPageNormal(int param_1,uint param_2,uint32_t *param_3,byte param_4);
void detachFunc(int *param_1);
char * allocateCursor(int param_1,int param_2,int param_3,char param_4,char param_5);
int newDatabase_part_486(int param_1);
uint allocateBtreePage(int *param_1,int *param_2,uint *param_3,uint param_4,char param_5);
void ptrmapPut(int *param_1,uint param_2,char param_3,uint param_4,int *param_5);
void ptrmapPutOvflPtr_isra_499(int param_1,uint *param_2,uint param_3,int *param_4);
int setChildPtrmaps(char *param_1);
void copyNodeContent_part_500(int param_1,uint8_t *param_2,int *param_3);
relocatePage(int *param_1,int param_2,byte param_3,int param_4,uint param_5,int param_6);
int autoVacuumCommit(int param_1);
int clearCell(int param_1,int param_2,int param_3);
void freePage_part_501(uint8_t *param_1,int *param_2);
uint balance(char *param_1);
int clearDatabasePage(int param_1,uint param_2,int param_3,int *param_4);
void charFunc(int param_1,int param_2,int param_3);
void last_valueStepFunc(int param_1,uint32_t param_2,int *param_3);
uint openDatabase(uint32_t param_1,uint32_t *param_2,uint param_3);
uint32_t pragmaVtabClose(int param_1);
void renameParseCleanup(uint32_t *param_1);
void attachFunc(int *param_1);
uint32_t selectExpander(int *param_1,int param_2);
int renameResolveTrigger(int *param_1);
void destroyRootPage(int *param_1,int param_2,int param_3);
openStatTable(int *param_1,int param_2,uint32_t param_3,int param_4,uint32_t param_5);
void analyzeDatabase(int *param_1,int param_2);
void analyzeTable(int *param_1,uint32_t *param_2,uint32_t *param_3);
renameTestSchema(int param_1,uint32_t param_2,int param_3,uint32_t param_4,uint32_t param_5);
void dropColumnFunc(int *param_1);
void renameTableTest(int *param_1,uint32_t param_2,int param_3);
void renameTableFunc(int *param_1,uint32_t param_2,int param_3);
int pragmaVtabFilter(int *param_1,uint32_t param_2,uint32_t param_3,int param_4,int param_5);
uint32_t pragmaVtabNext(int param_1);
int execSql(int param_1,int *param_2);
uint32_t execSqlF(int param_1,uint32_t param_2,uint32_t param_3);
int MaxFragHolder(void);
int MaxSpreeHolder(void);
int MaxRSpreeHolder(void);
uint8_t * AllocBan(uint32_t param_1);
uint8_t * AllocMute(uint32_t param_1);
uint32_t * AllocUser(void);
uint32_t * AllocLevel(void);
uint32_t GetUserPointer(int param_1);
void f_call(uint32_t param_1,uint32_t *param_2);
void f_Ccall(int param_1,uint32_t *param_2);
uint32_t str_upper(uint32_t param_1);
uint32_t str_reverse(uint32_t param_1);
uint32_t str_sub(uint32_t param_1);
uint32_t str_rep(uint32_t param_1);
int writer(UI *ui,UI_STRING *uis);
uint32_t str_len(uint32_t param_1);
void gfind_nodef(uint32_t param_1);
ushort match_class(int param_1,int param_2);
uint32_t str_lower(uint32_t param_1);
int str_byte(uint32_t param_1);
uint32_t gmatch(uint32_t param_1);
uint32_t str_dump(uint32_t param_1);
uint32_t str_char(uint32_t param_1);
int push_captures(int *param_1,int param_2,int param_3);
uint32_t str_format(uint32_t param_1);
bool matchbracketclass(uint param_1,uint param_2,uint param_3);
void max_expand(int param_1,uint param_2,byte *param_3,int param_4);
byte * match(int param_1,byte *param_2,byte *param_3);
uint32_t str_gsub(uint32_t param_1);
uint32_t gmatch_aux(uint32_t param_1);
uint32_t str_find_aux_constprop_5(uint32_t param_1);
void str_match(void);
int str_find_aux(uint32_t param_1,int param_2);
void str_find(void);
void DumpString(int param_1,uint32_t *param_2);
void DumpFunction(int param_1,uint32_t *param_2);
int addk(int *param_1,uint32_t param_2,int *param_3);
void patchlistaux(int *param_1,uint param_2,int param_3,uint param_4,int param_5);
void discharge2reg(int *param_1,int *param_2,uint param_3);
void exp2reg(int *param_1,int *param_2,int param_3);
uint jumponcond(int *param_1,int *param_2,int param_3);
void codearith(int *param_1,uint param_2,int *param_3,int *param_4);
void codecomp(int *param_1,uint param_2,int param_3,int *param_4,int *param_5);
void reallymarkobject(int param_1,int param_2);
int propagatemark(int param_1);
int cleartable(int param_1);
int * sweeplist_constprop_3(int param_1,int *param_2);
void markroot_isra_2(int *param_1);
uint32_t ll_require(uint32_t param_1);
uint32_t ll_module(uint32_t param_1);
uint32_t loader_preload(uint32_t param_1);
char * findfile(uint32_t param_1,uint32_t param_2,uint32_t param_3);
uint32_t ll_seeall(uint32_t param_1);
uint32_t gctm(uint32_t param_1);
uint32_t ll_loadfunc_isra_3(uint32_t param_1,uint32_t param_2);
uint32_t loader_Croot(uint32_t param_1);
uint32_t ll_loadlib(uint32_t param_1);
uint32_t loader_Lua(uint32_t param_1);
uint32_t loader_C(uint32_t param_1);
uint symbexec(int param_1,int param_2,uint param_3);
char * getobjname(int param_1,int param_2,uint param_3,int *param_4);
int mainposition(int param_1,double *param_2);
void resize(uint32_t param_1,int param_2,int param_3,int param_4);
uint8_t * newkey(uint32_t param_1,int param_2,double *param_3);
void f_parser(int param_1,uint32_t *param_2);
void resume(int param_1,int param_2);
uint call_orderTM(int param_1,uint32_t *param_2,uint32_t *param_3,uint32_t param_4);
Arith(int param_1,double *param_2,double *param_3,double *param_4,uint32_t param_5);
uint32_t ipairsaux(uint32_t param_1);
uint32_t generic_reader(uint32_t param_1,uint32_t param_2,uint32_t *param_3);
int auxresume(int param_1,int param_2,uint32_t param_3);
void save(int param_1,uint8_t param_2);
void inclinenumber(uint *param_1);
void read_numeral(uint *param_1,uint32_t param_2);
void read_long_string(uint *param_1,uint32_t *param_2,uint param_3);
uint llex(uint *param_1,int *param_2);
void hookf(uint32_t param_1,int *param_2);
void open_func(int param_1,int *param_2);
void close_func(int param_1);
void indexupvalue_isra_6(int *param_1,int param_2,uint *param_3,uint *param_4);
pushclosure_isra_8(int *param_1,uint32_t *param_2,int *param_3,uint32_t *param_4);
void new_localvar(int param_1,int param_2,int param_3);
void parlist(int param_1);
uint32_t singlevaraux(int *param_1,int param_2,uint32_t *param_3,int param_4);
void singlevar(int param_1,uint32_t *param_2);
void chunk(int param_1);
void body(int param_1,uint32_t param_2,int param_3,int param_4);
void block(int param_1);
void body_constprop_12(int param_1,uint32_t param_2,int param_3);
int subexpr(int param_1,uint32_t *param_2,uint param_3);
void recfield_isra_11(int param_1,int *param_2,int *param_3);
void constructor(int param_1,uint32_t *param_2);
void funcargs(int param_1,uint32_t *param_2);
void primaryexp(int param_1,uint32_t param_2);
void assignment(int param_1,int *param_2,int param_3);
uint32_t setn(uint32_t param_1);
uint32_t tremove(uint32_t param_1);
uint32_t tinsert(uint32_t param_1);
uint32_t foreach(uint32_t param_1);
uint32_t maxn(uint32_t param_1);
uint32_t getn(uint32_t param_1);
uint32_t foreachi(uint32_t param_1);
uint32_t tconcat(uint32_t param_1);
void auxsort(uint32_t param_1,int param_2,int param_3);
uint32_t sort(uint32_t param_1);
uint32_t getS(uint32_t param_1,uint32_t *param_2,int *param_3);
uint32_t panic(uint32_t param_1);
void * l_alloc(uint32_t param_1,void *param_2,uint32_t param_3,size_t param_4);
int * getF(uint32_t param_1,int *param_2,size_t *param_3);
uint32_t math_rad(uint32_t param_1);
uint32_t math_floor(uint32_t param_1);
uint32_t math_deg(uint32_t param_1);
uint32_t math_ceil(uint32_t param_1);
uint32_t math_abs(uint32_t param_1);
uint32_t math_tan(uint32_t param_1);
uint32_t math_tanh(uint32_t param_1);
uint32_t math_sqrt(uint32_t param_1);
uint32_t math_sin(uint32_t param_1);
uint32_t math_sinh(uint32_t param_1);
uint32_t math_randomseed(uint32_t param_1);
uint32_t math_min(uint32_t param_1);
uint32_t math_max(uint32_t param_1);
uint32_t math_random(uint32_t param_1);
uint32_t math_pow(uint32_t param_1);
uint32_t math_modf(uint32_t param_1);
uint32_t math_log(uint32_t param_1);
uint32_t math_log10(uint32_t param_1);
uint32_t math_ldexp(uint32_t param_1);
uint32_t math_frexp(uint32_t param_1);
uint32_t math_fmod(uint32_t param_1);
uint32_t math_exp(uint32_t param_1);
uint32_t math_cos(uint32_t param_1);
uint32_t math_cosh(uint32_t param_1);
uint32_t math_atan(uint32_t param_1);
uint32_t math_atan2(uint32_t param_1);
uint32_t math_asin(uint32_t param_1);
uint32_t math_acos(uint32_t param_1);
uint32_t os_setlocale(uint32_t param_1);
uint32_t os_rename(uint32_t param_1);
uint32_t os_getenv(uint32_t param_1);
void os_exit(uint32_t param_1);
uint32_t os_execute(uint32_t param_1);
uint32_t os_difftime(uint32_t param_1);
uint32_t os_clock(uint32_t param_1);
uint32_t os_tmpname(uint32_t param_1);
uint32_t os_date(uint32_t param_1);
uint32_t os_remove(uint32_t param_1);
uint32_t os_time(uint32_t param_1);
void PrintConstant_isra_0(int param_1,int param_2);
void f_luaopen(int param_1);
void close_state(int param_1);
void callallgcTM(int param_1);
uint32_t io_noclose(uint32_t param_1);
bool read_line(uint32_t param_1,FILE *param_2);
uint32_t io_tostring(uint32_t param_1);
uint32_t io_type(uint32_t param_1);
bool read_chars(uint32_t param_1,FILE *param_2,uint param_3);
uint32_t io_readline(uint32_t param_1);
uint32_t g_write(uint32_t param_1,FILE *param_2,int param_3);
void io_write(uint32_t param_1);
uint32_t io_pclose(uint32_t param_1);
uint32_t io_gc(uint32_t param_1);
void f_write(uint32_t param_1);
uint32_t io_open(uint32_t param_1);
uint32_t f_lines(uint32_t param_1);
uint32_t io_fclose(uint32_t param_1);
uint32_t f_flush(uint32_t param_1);
uint32_t io_flush(uint32_t param_1);
uint32_t f_seek(uint32_t param_1);
uint32_t io_input(uint32_t param_1);
void io_close(uint32_t param_1);
uint32_t f_setvbuf(uint32_t param_1);
uint32_t io_popen(uint32_t param_1);
uint32_t io_tmpfile(uint32_t param_1);
int g_read(uint32_t param_1,FILE *param_2,int param_3);
void io_read(uint32_t param_1);
void f_read(uint32_t param_1);
uint32_t io_lines(uint32_t param_1);
uint32_t io_output(uint32_t param_1);
uint32_t LoadString(uint32_t *param_1);
int LoadFunction(int *param_1,int param_2);
int _weaponBotToGame(int param_1);
uint32_t _chooseSecWeap(gentity_s *param_1,int param_2,int param_3);
uint32_t _choosePriWeap(gentity_s *param_1,int param_2,int param_3);
void UpdateGoalEntity(void);
void DeleteMapGoal(char *param_1);
void _GetEntityTeam(gentity_s *param_1);
int _GetEntityClass(gentity_s *param_1);
uint32_t InFieldOfVision(float *param_1,float param_2,float *param_3);
int stat64(char *__file,stat64 *__buf);
int fstat64(int __fd,stat64 *__buf);
int lstat64(char *__file,stat64 *__buf);

#endif

