#ifndef NITMOD_SQLITE_H
#define NITMOD_SQLITE_H

/* Embedded SQLite */

#include "nitmod_types.h"
#include "nitmod_globals.h"

void renameColumnElistNames(int param_1,int *param_2,int *param_3,uint32_t param_4);
void renameColumnIdlistNames(int param_1,int *param_2,int *param_3,uint32_t param_4);
uint32_t fkParentIsModified(int param_1,int param_2,int param_3,int param_4);
uint sqlite3DefaultRowEst(int param_1);
void sqlite3ExprAnalyzeAggregates(uint32_t param_1,int param_2);
void setAllPagerFlags_part_190(int param_1);
sqlite3JournalOpen(int param_1,uint32_t param_2,uint32_t *param_3,uint param_4,int param_5);
uint32_t sqlite3PcacheMakeClean(uint32_t *param_1);
void renumberCursors(int param_1,int param_2,int param_3,int param_4);
void estimateIndexWidth(int param_1);
uint32_t btreeSetHasContent_isra_310(uint32_t param_1,int *param_2,uint param_3);
uint getSafetyLevel(byte *param_1,int param_2,byte param_3);
sqlite3VtabOverloadFunction(int param_1,uint32_t *param_2,uint32_t param_3,char *param_4);
sqlite3AllocateIndexObject(int param_1,short param_2,int param_3,uint32_t *param_4);
void sqlite3VdbeAppendP4_constprop_621(int *param_1,uint32_t param_2);
uint32_t functionDestroy_isra_234(uint32_t param_1,int *param_2,uint32_t param_3);
byte * sqlite3VdbeAddOpList_isra_302(int param_1,int param_2,byte *param_3);
windowReadPeerValues_isra_299(int param_1,int param_2,uint32_t param_3,int param_4);
int exprTableRegister(uint32_t param_1,int param_2,int param_3,short param_4);
uint32_t sqlite3VdbeAppendP4(int *param_1,int param_2,uint32_t param_3);
void finalizeAggFunctions_isra_293(uint32_t param_1,int *param_2,int *param_3);
void windowAggFinal_isra_298(int param_1,int param_2,uint8_t *param_3,int param_4);
returnSingleInt(int *param_1,uint32_t param_2,uint32_t param_3,uint32_t param_4);
void windowCheckValue(int param_1,uint32_t param_2,int param_3);
int pageFreeArray_isra_361(int param_1,int param_2,int param_3,int *param_4,int *param_5);
void sqlite3RowidConstraint(uint32_t *param_1,uint32_t param_2,uint32_t *param_3);
bool windowExprGtZero_isra_442(int param_1,int param_2);
void substSelect(uint32_t param_1,int param_2,int param_3);
void autoIncrementEnd(int *param_1);
void resetAccumulator(int *param_1,int param_2);
uint sqlite3FkOldmask_part_398(uint32_t param_1,int param_2);
void exprRowColumn(uint32_t param_1,short param_2);
bool xferCompatibleIndex(int param_1,int param_2);
uint sqlite3AuthReadCol(int *param_1,uint32_t param_2,uint32_t param_3,int param_4);
void sqlite3ExprCodeCopy(int *param_1,int param_2,uint32_t param_3);
void sqlite3ExprCodeFactorable(int *param_1,int param_2,uint32_t param_3);
void sqlite3ComputeGeneratedColumns(int param_1,int param_2,int param_3);
void windowReturnOneRow(int *param_1);
int windowCodeOp(int *param_1,int param_2,int param_3,int param_4);
void updateAccumulator(int *param_1,uint8_t *param_2,int *param_3,uint8_t *param_4);
uint64_t invalidateTempStorage(int *param_1,uint32_t param_2,uint32_t param_3);
sqlite3FkCheck(int *param_1,uint32_t *param_2,int param_3,int param_4,int param_5,int param_6);
sqlite3UpsertDoUpdate(int param_1,int *param_2,int param_3,int param_4,int param_5,int param_6);
int * getRowTrigger(int *param_1,int *param_2,int param_3,int param_4);
uint32_t sqlite3MemSize(int param_1);
uint sqlite3MemRoundup(int param_1);
uint32_t sqlite3MemInit(void);
void sqlite3MemShutdown(void);
uint32_t sqlite3_release_memory(void);
longlong sqlite3_msize(int param_1);
uint8_t sqlite3_str_errcode(int param_1);
uint32_t sqlite3_str_length(int param_1);
uint32_t sqlite3_str_value(int param_1);
uint sqlite3Utf8Read(int *param_1);
void sqlite3Dequote(byte *param_1);
int sqlite3_stricmp(byte *param_1,byte *param_2);
int sqlite3_strnicmp(byte *param_1,byte *param_2,int param_3);
uint32_t sqlite3Atoi64(byte *param_1,uint *param_2,uint param_3,byte param_4);
int sqlite3LogEst(uint param_1,uint param_2);
int sqlite3VListNumToName(int param_1,int param_2);
uint sqlite3BitvecTestNotNull(uint *param_1,int param_2);
uint32_t pcache1Pagecount(int param_1);
void pcache1Rekey(int param_1,int param_2,uint param_3,uint param_4);
uint32_t pagerUnlockDb(int param_1,uint32_t param_2);
void sqlite3PagerSetFlags(int param_1,uint param_2);
uint32_t sqlite3_database_file_object(int param_1);
uint * walChecksumBytes(int param_1,uint *param_2,int param_3,int *param_4,int *param_5);
uint32_t sqlite3_enable_shared_cache(uint32_t param_1);
int btreeGetPage(int *param_1,int param_2,int *param_3,uint32_t param_4);
uint32_t sqlite3BtreeSetCacheSize(int *param_1,int param_2);
int sqlite3BtreeSecureDelete(uint32_t *param_1,int param_2);
uint32_t sqlite3_backup_remaining(int param_1);
uint32_t sqlite3_backup_pagecount(int param_1);
void sqlite3NoopDestructor(void);
void sqlite3VdbeExplainPop(int param_1);
void sqlite3VdbeUsesBtree(int *param_1,int param_2);
void sqlite3VdbeFrameMemDel(int *param_1);
bool sqlite3_expired(int param_1);
uint8_t sqlite3_value_subtype(int param_1);
uint8_t sqlite3_value_type(int param_1);
bool sqlite3_value_nochange(int param_1);
ushort sqlite3_value_frombind(int param_1);
void sqlite3_result_subtype(int *param_1,uint8_t param_2);
uint32_t sqlite3_user_data(int param_1);
uint32_t sqlite3_context_db_handle(int *param_1);
bool sqlite3_vtab_nochange(int *param_1);
int sqlite3_get_auxdata(int param_1,int param_2);
uint32_t sqlite3_aggregate_count(int param_1);
uint16_t sqlite3_column_count(int param_1);
uint16_t sqlite3_data_count(int param_1);
int sqlite3_bind_parameter_count(int param_1);
uint32_t sqlite3_db_handle(uint32_t *param_1);
byte sqlite3_stmt_readonly(int param_1);
byte sqlite3_stmt_isexplain(int param_1);
uint sqlite3_stmt_busy(int param_1);
uint32_t sqlite3_next_stmt(int param_1,int param_2);
uint32_t sqlite3_sql(int param_1);
uint32_t sqlite3_blob_bytes(uint32_t *param_1);
void vdbeSorterExtendFile(int param_1,int *param_2,uint param_3,int param_4);
uint32_t sqlite3WalkerDepthIncrease(int param_1);
void sqlite3WalkerDepthDecrease(int param_1);
uint32_t sqlite3ExprWalkNoop(void);
uint32_t sqlite3SelectWalkNoop(void);
uint32_t sqlite3SelectWalkFail(int param_1);
bool sqlite3ExprCanBeNull(byte *param_1);
uint32_t renameColumnExprCb(int *param_1,char *param_2);
uint32_t sqlite3_set_authorizer(int param_1,int param_2,uint32_t param_3);
uint32_t sqlite3_cancel_auto_extension(int param_1);
uint32_t renumberCursorsCb(int param_1,char *param_2);
uint8_t sqlite3_vtab_on_conflict(int param_1);
bool sqlite3_keyword_name(uint param_1,int *param_2,uint *param_3);
uint32_t sqlite3_keyword_count(void);
bool sqlite3_keyword_check(void);
int sqlite3GetToken(byte *param_1,uint32_t *param_2);
bool sqlite3_complete(byte *param_1);
char * sqlite3_libversion(void);
uint8_t * sqlite3_libversion_number(void);
uint32_t sqlite3_threadsafe(void);
uint32_t sqlite3_db_mutex(int param_1);
uint32_t sqlite3_db_release_memory(int param_1);
uint64_t sqlite3_last_insert_rowid(int param_1);
void sqlite3_set_last_insert_rowid(int param_1,uint32_t param_2,uint32_t param_3);
uint32_t sqlite3_changes(int param_1);
uint32_t sqlite3_total_changes(int param_1);
uint32_t sqlite3_busy_handler(int param_1,uint32_t param_2,uint32_t param_3);
void sqlite3_progress_handler(int param_1,int param_2,uint32_t param_3,uint32_t param_4);
uint32_t sqlite3_trace(int param_1,int param_2,uint32_t param_3);
uint32_t sqlite3_trace_v2(int param_1,int param_2,int param_3,uint32_t param_4);
uint32_t sqlite3_profile(int param_1,int param_2,uint32_t param_3);
uint32_t sqlite3_commit_hook(int param_1,uint32_t param_2,uint32_t param_3);
uint32_t sqlite3_update_hook(int param_1,uint32_t param_2,uint32_t param_3);
uint32_t sqlite3_rollback_hook(int param_1,uint32_t param_2,uint32_t param_3);
uint32_t sqlite3_wal_autocheckpoint(int param_1,int param_2);
uint32_t sqlite3_wal_hook(int param_1,uint32_t param_2,uint32_t param_3);
uint32_t sqlite3_system_errno(int param_1);
uint32_t sqlite3_limit(int param_1,uint param_2,int param_3);
uint32_t sqlite3_collation_needed(int param_1,uint32_t param_2,uint32_t param_3);
uint32_t sqlite3_collation_needed16(int param_1,uint32_t param_2,uint32_t param_3);
uint8_t sqlite3_get_autocommit(int param_1);
void sqlite3_thread_cleanup(void);
uint32_t sqlite3_extended_result_codes(int param_1,int param_2);
void sqlite3_filename_database(int param_1);
uint8_t * sqlite3_compileoption_get(uint param_1);
uint8_t * sqlite3_sourceid(void);
void sqlite3_interrupt(int param_1);
void pcacheSortDirtyList(uint8_t *param_1);
int pager_truncate(int param_1,uint param_2);
void pcache1Shutdown(void);
uint32_t pcache1Init(void);
walMerge(int param_1,uint32_t *param_2,int param_3,int *param_4,int *param_5,uint32_t *param_6);
void sqlite3BitvecClear(uint *param_1,int param_2,uint *param_3);
uint sqlite3VdbeSerialGet(byte *param_1,uint param_2,uint *param_3);
uint32_t sqlite3GetInt32(byte *param_1,uint *param_2);
char * sqlite3_uri_parameter(char *param_1,char *param_2);
char * sqlite3_uri_key(char *param_1,int param_2);
char * sqlite3_filename_journal(char *param_1);
int sqlite3BlobCompare(int *param_1,int *param_2);
void sqlite3BtreeGetMeta(int *param_1,int param_2,uint *param_3);
void sqlite3MemFree(int param_1);
void sqlite3OsSync_part_1(int *param_1,uint32_t param_2);
uint sqlite3DbMallocSize(int param_1,uint param_2);
void sqlite3_free(int param_1);
void sqlite3_free_filename(int param_1);
int sqlite3AtoF_part_9(byte *param_1,double *param_2,uint param_3,byte param_4);
uint32_t sqlite3VdbeMemNumerify(double *param_1);
uint32_t sqlite3PutVarint_part_10(byte *param_1,uint param_2,int param_3);
uint32_t sqlite3GetVarint(byte *param_1,uint *param_2);
uint32_t sqlite3GetVarint32(byte *param_1,uint *param_2);
int sqlite3LogEstAdd(short param_1,short param_2);
int pagerLockDb_part_42(int param_1,int param_2);
walUnlockExclusive_isra_83_part_84(int *param_1,uint32_t param_2,uint32_t param_3);
void btreeParseCellPtr(int param_1,byte *param_2,uint *param_3);
void btreeParseCellPtrIndex(int param_1,int param_2,uint *param_3);
uint32_t sqlite3VdbeIntValue(uint64_t *param_1);
long double sqlite3VdbeRealValue(double *param_1);
uint sqlite3WalkSelect(int *param_1,int param_2);
uint walkExpr(int param_1,int param_2);
uint32_t sqlite3WalkExprList(uint32_t param_1,int *param_2);
longlong walkWindowList(uint32_t param_1,int param_2,int param_3);
uint16_t sqlite3ExprIsConstant(int param_1);
bool sqlite3ExprReferencesUpdatedColumn(int param_1,uint32_t param_2,int param_3);
longlong sqlite3IsRowid(byte *param_1);
void sqlite3ReleaseTempReg_part_165(int param_1,uint32_t param_2);
int sqlite3GetTempRange(int param_1,int param_2);
int sqlite3TableColumnToStorage(int param_1,short param_2);
int sqlite3ColumnIndex_isra_192(uint32_t *param_1,short *param_2,byte *param_3);
void sqlite3SelectPrep_part_198(void);
longlong sqlite3TriggerList_isra_199(int param_1,uint param_2,uint32_t *param_3);
uint32_t sqlite3WindowExtraAggFuncDepth(int param_1,char *param_2);
char * sqlite3ErrStr(uint param_1);
bool sqliteDefaultBusyCallback(int *param_1,int param_2);
uint32_t sqlite3_busy_timeout(int param_1,int param_2);
int sqlite3Malloc(uint param_1,int param_2);
int sqlite3Realloc(int param_1,uint param_2,int param_3);
uint32_t * pcache1Alloc(uint param_1);
void sqlite3OomFault_part_242(int param_1);
void sqlite3VtabMakeWritable(int *param_1,int param_2);
uint32_t sqlite3_value_pointer(uint32_t *param_1,char *param_2);
uint32_t sqlite3DecOrHexToI64(char *param_1,uint *param_2);
uint32_t sqliteErrorFromPosixError_constprop_549(int param_1);
void sqlite3SelectPrep_constprop_601(int *param_1,int param_2);
byte sqlite3ExprAffinity(byte *param_1);
byte sqlite3CompareAffinity(uint32_t param_1,byte param_2);
int sqlite3FindTable(int param_1,int param_2,byte *param_3);
int sqlite3FindTable_constprop_572(int param_1,int param_2);
bool sqlite3FkRequired_isra_187_constprop_564(int param_1,int param_2);
int sqlite3IndexAffinityStr(int param_1,int param_2);
void pagerFixMaplimit(int param_1);
int vdbePmaReadBlob_part_328(uint *param_1,uint param_2,uint *param_3);
void sqlite3ExprAnalyzeAggList(uint32_t param_1,int *param_2);
uint32_t walIndexTryHdr(int param_1,uint32_t *param_2);
void walIndexWriteHdr(int param_1);
int btreeInvokeBusyHandler(int param_1);
void sqlite3SelectPrep(int *param_1,int param_2);
void sqlite3ReleaseTempRange_part_167(int param_1,int param_2);
char * sqlite3_errstr(uint param_1);
uint32_t sqlite3_db_config(int param_1,int param_2,int param_3,uint *param_4,uint32_t param_5);
int sqlite3_bind_parameter_name(int param_1,int param_2);
bool renameColumnSelectCb(uint32_t param_1,int param_2);
long double sqlite3_value_double(double *param_1);
int sqlite3PagerSync(int param_1,uint32_t param_2);
int * vdbeMergeEngineNew(int param_1);
int * pcacheFetchFinishWithInit(int param_1,int param_2,int *param_3);
int * sqlite3PagerLookup_isra_266(int *param_1,uint32_t param_2);
uint sqlite3BitvecSet(uint *param_1,int param_2);
void walWriteToLog(int param_1,int param_2,uint param_3,uint param_4,int param_5);
uint32_t sqlite3ExprIdToTrueFalse(uint8_t *param_1);
int vdbeSorterOpenTempFile(int *param_1,int param_2,int param_3,uint32_t *param_4);
uint32_t sqlite3_bind_parameter_index(int param_1,char *param_2);
uint pagerAddPageToRollbackJournal(int param_1);
int btreePageLookup(int *param_1,int param_2);
uint walIndexPageRealloc(int param_1,int param_2,int *param_3);
void walCleanupHash(int param_1);
void btreeParseCellPtrNoPayload(uint32_t param_1,int param_2,uint *param_3);
void sqlite3SrcListAssignCursors(int param_1,int *param_2);
void walRestartHdr(int param_1,int param_2);
uint sqlite3VdbeBooleanValue(double *param_1,uint param_2);
uint8_t vdbeSorterSort_isra_278_part_279(int param_1,int *param_2,int *param_3);
void sqlite3PcacheMakeDirty(int param_1);
void sqlite3PcacheTruncate(int *param_1,uint param_2);
void pager_reset(int param_1);
void sqlite3OomFault(int param_1);
void sqlite3BitvecDestroy(int param_1);
char sqlite3_value_numeric_type(uint64_t *param_1);
void sqlite3PcacheDrop(uint32_t *param_1);
uint32_t sqlite3_value_int(uint64_t *param_1);
uint32_t sqlite3_value_int64(uint64_t *param_1);
void sqlite3PcacheRelease(uint32_t *param_1);
void sqlite3PagerUnrefNotNull(int param_1);
int sqlite3FindIndex(int param_1,byte *param_2);
uint32_t sqlite3VdbeMemIntegerify(uint64_t *param_1);
void sqlite3PcacheMove(uint32_t *param_1,uint32_t param_2);
void btreeReleaseAllCursorPages(int param_1);
void sqlite3_strglob(void);
void sqlite3_strlike(uint32_t param_1,uint32_t param_2,uint32_t param_3);
uint sqlite3ExprIsInteger(char *param_1,int *param_2);
uint sqlite3HashInsert_constprop_704(uint *param_1,byte *param_2);
uint sqlite3HashInsert(uint *param_1,byte *param_2,uint param_3);
uint64_t sqlite3_uri_int64(uint32_t param_1,uint32_t param_2,uint param_3,int param_4);
void pcache1TruncateUnsafe(int param_1,uint param_2);
void pcache1Truncate(int param_1,uint param_2);
uint16_t * sqlite3MallocZero_constprop_667(void);
uint32_t * sqlite3MallocZero(uint param_1,int param_2);
void pcache1ResizeHash_isra_263(uint *param_1,int *param_2);
int pager_end_transaction(int *param_1,int param_2,int param_3);
uint32_t sqlite3ExprImpliesNonNullRow(char *param_1);
int sqlite3FindDbName(int param_1,byte *param_2);
uint sqlite3_txn_state(int param_1,int param_2);
uint sqlite3_db_readonly(int param_1,int param_2);
uint32_t sqlite3_db_filename(int param_1,int param_2);
void pager_unlock(int param_1);
char * sqlite3ExprSimplifiedAndOr_part_159(char *param_1);
char * sqlite3_filename_wal(char *param_1);
uint32_t pagerOpenSavepoint(int param_1,int param_2);
walDecodeFrame(int param_1,uint *param_2,uint *param_3,uint *param_4,uint *param_5);
void sqlite3HashClear(uint32_t *param_1);
sqlite3IsShadowTableOf_part_345(uint32_t param_1,uint32_t *param_2,byte *param_3);
void sqlite3_free_table(int param_1);
bool sqlite3_uri_boolean(uint32_t param_1,uint32_t param_2,int param_3);
void sqlite3OsCloseFree(int *param_1);
uint32_t sqlite3_compileoption_used(byte *param_1);
uint16_t * sqlite3SchemaGet(int param_1,uint32_t *param_2);
void sqlite3SetJoinExpr(char *param_1,uint32_t param_2);
void sqlite3DbFree(int param_1,uint32_t *param_2);
void pcache1Free(uint32_t *param_1);
int * pcache1FetchStage2(int *param_1,uint param_2,int param_3);
int pcache1Fetch(int param_1,uint param_2,int param_3);
int sqlite3PagerSetPagesize(int param_1,uint *param_2,int param_3);
uint32_t pcache1Unpin(int *param_1,int param_2,int param_3);
void pcache1EnforceMaxPage(int *param_1);
void pcache1Cachesize(int *param_1,int param_2);
void pcache1Shrink(int *param_1);
int * pcache1Create(int param_1,int param_2,int param_3);
uint32_t * sqlite3DbMallocRawNN(int param_1,uint param_2,int param_3);
byte * sqlite3NameFromToken(uint32_t param_1,uint32_t *param_2);
sqlite3SrcListIndexedBy_isra_313(uint32_t param_1,int *param_2,uint32_t *param_3);
sqlite3SrcListAppend_constprop_600(uint32_t param_1,uint32_t *param_2,uint32_t *param_3);
sqlite3ParserAddCleanup_isra_245(int *param_1,uint32_t *param_2,void *param_3,uint32_t param_4);
uint32_t * sqlite3ExprAlloc_constprop_675(int param_1,uint8_t param_2);
uint32_t * sqlite3DbStrNDup(int param_1,uint32_t *param_2,uint param_3,int param_4);
uint32_t * sqlite3ValueNew(int param_1);
uint32_t * sqlite3KeyInfoAlloc(int param_1,int param_2,int param_3);
uint32_t * sqlite3DbMallocZero(int param_1,uint param_2,int param_3);
void sqlite3_set_auxdata(int param_1,int param_2,int param_3,void *param_4);
int * sqlite3VdbeAllocUnpackedRecord(int param_1);
int vdbeSorterListToPMA(int param_1,uint32_t *param_2);
void sqlite3RowSetInsert(uint32_t *param_1,uint param_2,uint param_3);
void sqlite3RenameTokenMap_part_260(int *param_1,uint32_t param_2,uint32_t *param_3);
uint32_t * sqlite3Expr_constprop_618(int param_1,uint8_t param_2);
uint32_t * sqlite3ExprAlloc_constprop_676(int param_1,int param_2,int *param_3);
char * sqlite3DbStrDup(int param_1,char *param_2);
uint32_t * sqlite3Expr_constprop_617(int param_1,char *param_2);
uint32_t * sqlite3Expr(int param_1,int param_2,char *param_3);
void sqlite3DbFreeNN(int param_1,uint32_t *param_2);
uint sqlite3_str_reset(uint32_t param_1,uint *param_2);
void sqlite3KeyInfoUnref(int *param_1);
void sqlite3CloseSavepoints(int param_1);
uint sqlite3DbRealloc(int param_1,uint param_2,uint param_3,int param_4);
void sqlite3ChangeCookie_isra_296(int param_1,int param_2);
int * sqlite3GetVdbe_part_292(int *param_1);
void sqlite3SetHasNullFlag(int *param_1,uint32_t param_2,uint32_t param_3);
void sqlite3VdbeEndCoroutine(int param_1,uint32_t param_2);
void sqlite3CollapseDatabaseArray(int param_1);
sqlite3FindCollSeq_part_342(int param_1,byte param_2,char *param_3,int param_4);
sqlite3FindFunction(int param_1,byte *param_2,int param_3,byte param_4,char param_5);
void sqlite3VdbeResolveLabel(int param_1,uint param_2);
void sqlite3VtabUnlock(int param_1);
void sqlite3TableLock(int *param_1,int param_2,int param_3,char param_4,int param_5);
void vdbeMemClearExternAndSetNull(int *param_1);
void vdbeMemClear(int param_1);
void sqlite3VdbeMemRelease(int param_1);
void sqlite3_result_zeroblob(int *param_1,int param_2);
uint32_t sqlite3_clear_bindings(int param_1);
void sqlite3_value_free(int param_1);
void sqlite3ValueFree(int param_1);
uint32_t sqlite3_transfer_bindings(int param_1,int param_2);
uint32_t sqlite3_result_zeroblob64(int *param_1,uint param_2,uint param_3);
void sqlite3ErrorFinish(int *param_1,uint param_2);
uint32_t sqlite3ApiExit(int param_1,int param_2);
void vdbeReleaseAndSetInt64(uint32_t *param_1,uint32_t param_2,uint32_t param_3);
void sqlite3_result_int(int *param_1,int param_2);
void sqlite3_result_int64(int *param_1,uint32_t param_2,uint32_t param_3);
void sqlite3_result_null(int *param_1);
void sqlite3_result_error_nomem(int *param_1);
uint32_t vdbeClrCopy(uint32_t *param_1,uint32_t *param_2,ushort param_3);
void sqlite3VdbeMemShallowCopy(uint32_t *param_1,uint32_t *param_2,ushort param_3);
void sqlite3ErrorFinish_constprop_642(int param_1);
void sqlite3ErrorFinish_constprop_643(int param_1);
uint8_t sqlite3_column_type(int *param_1,int param_2);
uint32_t * sqlite3_column_value(int *param_1,int param_2);
uint32_t sqlite3_column_int(int *param_1,int param_2);
uint64_t sqlite3_column_int64(int *param_1,int param_2);
long double sqlite3_column_double(int *param_1,int param_2);
void sqlite3ErrorFinish_constprop_644(int param_1);
void sqlite3_result_double(int *param_1,ulonglong param_2);
void sqlite3VtabUnlockList(int param_1);
int sqlite3VtabSavepoint(int param_1,int param_2,int param_3);
uint32_t sqlite3_str_finish(uint8_t *param_1);
int * sqlite3SrcListDup_constprop_682(int param_1,int *param_2);
uint32_t sqlite3SelectDup_constprop_681(int param_1,uint8_t *param_2);
uint32_t sqlite3SelectDup(int param_1,uint8_t *param_2,uint32_t param_3);
int * sqlite3ExprListDup(int param_1,int *param_2,uint32_t param_3);
int * sqlite3SrcListDup(int param_1,int *param_2,uint32_t param_3);
int * sqlite3ExprListDup_constprop_680(int param_1,int *param_2);
uint32_t * sqlite3WindowDup(int param_1,uint32_t param_2,int param_3);
uint sqlite3StrAccumEnlarge_part_286(int *param_1,uint param_2);
void sqlite3_str_appendchar(int param_1,uint param_2,uint8_t param_3);
void sqlite3_str_append(int param_1,uint32_t *param_2,uint param_3);
void sqlite3_str_append_constprop_674(int param_1,uint8_t *param_2);
void sqlite3_str_appendall(int param_1,char *param_2);
void sqlite3VdbeSetNumCols(int *param_1,int param_2);
uint64_t sqlite3WhereExprUsageNN(uint32_t *param_1,char *param_2);
uint64_t sqlite3WhereExprListUsage(uint32_t param_1,int *param_2);
void sqlite3ExprListSetName(int *param_1,int *param_2,int *param_3,int param_4);
uint32_t sqlite3VdbeMemGrow(int param_1,uint param_2,int param_3);
uint32_t sqlite3VdbeMemExpandBlob(uint *param_1);
uint32_t vdbeMemAddTerminator(int param_1);
uint32_t sqlite3_aggregate_context(int param_1);
int sqlite3VdbeMemMakeWriteable(uint *param_1);
uint32_t sqlite3VdbeMemTranslate(int param_1,char param_2);
uint32_t sqlite3VdbeChangeEncoding(int param_1,uint param_2);
uint32_t sqlite3VdbeMemCopy(uint32_t *param_1,uint32_t *param_2);
sqlite3VdbeMemSetStr(int param_1,char *param_2,uint param_3,byte param_4,void *param_5);
sqlite3VdbeMemSetStr_constprop_648(int param_1,char *param_2,uint param_3,void *param_4);
void sqlite3VdbeSetColName_part_433_constprop_599(void);
int sqlite3VdbeTransferError(int *param_1);
void sqlite3_result_error(int param_1);
void sqlite3_result_error_code(int *param_1,int param_2);
void sqlite3_result_text(int param_1,uint32_t param_2,uint32_t param_3,uint32_t param_4);
void sqlite3_result_text16le(int param_1,uint32_t param_2,uint32_t param_3,uint32_t param_4);
void sqlite3_result_text16be(int param_1,uint32_t param_2,uint32_t param_3,uint32_t param_4);
void sqlite3_result_blob(int param_1,uint32_t param_2,uint32_t param_3,uint32_t param_4);
void sqlite3_result_blob64(int param_1,uint32_t param_2,uint param_3,int param_4,void *param_5);
void sqlite3VdbeMakeReady(int *param_1,int param_2);
uint32_t sqlite3_result_value(int *param_1,uint32_t *param_2);
void sqlite3_result_error16(int *param_1,char *param_2,uint param_3);
void sqlite3VtabImportErrmsg_isra_348(int *param_1,int *param_2,int *param_3);
int vdbePmaReadVarint(uint *param_1);
uint32_t * sqlite3ExprAlloc(int param_1,int param_2,int *param_3,int param_4);
sqlite3ExprAddCollateToken(uint32_t param_1,char *param_2,int param_3,uint32_t param_4);
void sqlite3ExprAddCollateString(char *param_1);
int sqlite3BtreeSetPageSize(int *param_1,uint param_2,uint param_3,int param_4);
uint32_t sqlite3_file_control(int param_1,int param_2,int param_3,uint *param_4);
void sqlite3_result_error_toobig(int *param_1);
void sqlite3RowSetDelete(uint32_t *param_1);
void vdbeMergeEngineFree(int *param_1);
void sqlite3VdbeSorterReset(uint32_t param_1,int param_2);
uint vdbePmaReaderNext(uint *param_1);
uint vdbeMergeEngineStep(int *param_1,uint *param_2);
int vdbeMergeEngineLevel0(int param_1,int param_2,uint *param_3,uint32_t *param_4);
uint vdbeMergeEngineInit_isra_331(int param_1,int *param_2);
void pcache1Destroy(int *param_1);
void sqlite3ExprDeleteNN_constprop_686(char *param_1);
void sqlite3SrcListDelete_constprop_693(int *param_1);
void sqlite3SchemaClear(int param_1);
void sqlite3ResetAllSchemasOfConnection(int param_1);
void sqlite3_result_text16(int *param_1,char *param_2,uint param_3,void *param_4);
int pagerOpenWal(int *param_1);
int sqlite3PagerOpenWal(int param_1,uint32_t *param_2);
void sqlite3SrcListDelete(int param_1,int *param_2);
void sqlite3ExprDeleteNN(uint32_t param_1,char *param_2);
uint32_t sqlite3ExprListDelete(uint32_t param_1,int param_2);
void sqlite3ParserReset(int *param_1);
void sqlite3DeleteReturning(int param_1,int param_2);
sqlite3WindowAssemble_isra_314(int *param_1,int param_2,int param_3,int param_4,uint32_t *param_5);
void sqlite3WindowDelete(uint32_t param_1,int *param_2);
void sqlite3FreeIndex(uint32_t param_1,int param_2);
void sqlite3DeleteColumnNames_isra_253(uint32_t param_1,int *param_2,short *param_3);
void sqlite3WhereClauseClear(int param_1);
void sqlite3WhereEnd(int *param_1);
sqlite3UpsertNew(int param_1,int param_2,int param_3,int param_4,int param_5,int param_6);
uint * sqlite3ExprListAppend_isra_303(int param_1,uint *param_2,uint param_3);
void sqlite3AddCheckConstraint(int *param_1,int param_2,int param_3,int param_4);
void sqlite3WhereSplit(int param_1,char *param_2,char param_3);
uint32_t * sqlite3ExprListAppend_isra_303_constprop_685(uint32_t param_1,int param_2);
int * sqlite3UpsertDup(int param_1,int param_2);
void sqlite3WithDelete(uint32_t param_1,int *param_2);
void sqlite3DeleteTable(int param_1,int param_2);
uint32_t sqlite3_drop_modules(int param_1,uint32_t *param_2);
uint32_t sqlite3_create_module(int param_1,int *param_2,int param_3,int param_4);
int sqlite3_create_module_v2(int param_1,int *param_2,int param_3,int param_4,void *param_5);
void sqlite3DeleteTriggerStep(uint32_t param_1,int param_2);
void sqlite3DeleteTrigger_part_252(int param_1,int *param_2);
void sqlite3IdListDelete(int param_1,int *param_2);
uint * sqlite3IdListAppend(int *param_1,uint *param_2,uint32_t *param_3);
uint32_t sqlite3VdbeChangeToNoop_isra_284(int param_1,int *param_2,int param_3);
void sqlite3VdbeClearObject(int param_1,int param_2);
uint32_t sqlite3_db_status(int param_1,int param_2,uint *param_3,int *param_4,int param_5);
void sqlite3VdbeDelete(int *param_1);
int sqlite3_stmt_status(int *param_1,int param_2,int param_3);
void sqlite3VdbeChangeP4(int *param_1,int param_2,int param_3,int param_4);
void vdbeChangeP4Full(int *param_1,int param_2,char *param_3,uint param_4);
int sqlite3VdbeLoadString(int *param_1,uint32_t param_2,uint32_t param_3);
void sqlite3VdbeMultiLoad(int *param_1,int param_2,char *param_3);
void sqlite3TableAffinity(int *param_1,int param_2,int param_3);
sqlite3VdbeAddParseSchemaOp(int *param_1,uint32_t param_2,uint32_t param_3,uint16_t param_4);
int sqlite3PagerBegin(int param_1,int param_2,uint8_t param_3);
void sqlite3_str_vappendf(int param_1,byte *param_2,double *param_3);
void sqlite3_str_appendf(uint32_t param_1,uint32_t param_2);
sqlite3WhereExplainOneScan(uint32_t *param_1,int param_2,int param_3,ushort param_4);
void sqlite3UniqueConstraint(int *param_1,int param_2,uint32_t *param_3);
uint8_t * sqlite3VdbeExpandSql(int *param_1,char *param_2);
uint32_t sqlite3_expanded_sql(int param_1);
uint32_t sqlite3VdbeMemStringify(double *param_1,char param_2,char param_3);
int sqlite3_column_bytes16(int *param_1,int param_2);
int sqlite3ValueBytes_constprop_639(int *param_1);
int sqlite3_value_bytes16(int *param_1);
int sqlite3_value_bytes(int *param_1);
int sqlite3_column_bytes(int *param_1,int param_2);
uint32_t sqlite3ValueText_constprop_669(int param_1);
uint sqlite3_value_blob(uint *param_1);
uint32_t sqlite3_column_name(int *param_1,int param_2);
uint64_t sqlite3_column_decltype(int *param_1,int param_2);
uint sqlite3_column_blob(int *param_1,int param_2);
uint32_t sqlite3_value_text16(int param_1);
uint32_t sqlite3_value_text16be(int param_1);
uint32_t sqlite3_value_text16le(int param_1);
uint32_t sqlite3_column_text16(int *param_1,int param_2);
uint32_t vdbeCompareMemString(int param_1,int param_2,int param_3,uint8_t *param_4);
uint sqlite3MemCompare(double *param_1,double *param_2,int param_3);
uint64_t sqlite3_column_decltype16(int *param_1,int param_2);
uint32_t sqlite3_column_name16(int *param_1,int param_2);
uint32_t sqlite3_value_text(int param_1);
uint32_t sqlite3_column_text(int *param_1,int param_2);
uint32_t sqlite3VdbeMemCast(double *param_1,byte param_2,char param_3);
int sqlite3_snprintf(int param_1,int param_2,uint32_t param_3);
void sqlite3_log(uint32_t param_1,uint32_t param_2);
int btreeGetUnusedPage(int *param_1,int param_2,uint32_t *param_3,uint32_t param_4);
uint32_t btreeComputeFreeSpace(int param_1);
walLimitSize_isra_362(uint32_t *param_1,uint32_t *param_2,uint param_3,int param_4);
uint32_t sqlite3_vtab_config(int param_1,int param_2,uint8_t param_3);
sqlite3VdbeRecordCompareWithSkip(uint param_1,byte *param_2,int *param_3,int param_4);
void sqlite3VdbeRecordCompare(uint32_t param_1,uint32_t param_2,uint32_t param_3);
int vdbeRecordCompareInt(uint32_t param_1,byte *param_2,int param_3);
int vdbeRecordCompareString(int param_1,byte *param_2,int param_3);
uint32_t btreeCellSizeCheck(int param_1);
int sqlite3WalFindFrame(int param_1,int param_2,uint *param_3);
int walIndexAppend(int param_1,int param_2,int param_3);
int * sqlite3MemRealloc(int param_1,int param_2);
int * sqlite3MemMalloc(int param_1);
int sqlite3BtreeTripAllCursors(uint32_t *param_1,uint32_t param_2,int param_3);
uint32_t sqlite3_memory_used(void);
uint32_t sqlite3_memory_highwater(int param_1);
uint32_t sqlite3_status64(uint param_1,uint32_t *param_2,uint32_t *param_3,int param_4);
uint32_t vdbeUnbind(int *param_1,int param_2);
uint32_t sqlite3_status(uint param_1,uint32_t *param_2,uint32_t *param_3,int param_4);
int sqlite3VdbeMemFromBtreeZeroOffset(int param_1,uint param_2,int param_3);
uint32_t btreeInitPage(uint8_t *param_1);
char * sqlite3_errmsg(int param_1);
uint sqlite3_errcode(int param_1);
uint32_t sqlite3_extended_errcode(int param_1);
int sqlite3BtreeLast(char *param_1,uint32_t *param_2);
int sqlite3BtreeNext(char *param_1);
int btreeRestoreCursorPosition(char *param_1);
int btreePrevious(byte *param_1);
uint32_t sqlite3BtreePrevious(char *param_1);
int sqlite3VdbeFinishMoveto(int param_1);
int btreeNext(byte *param_1);
uint32_t sqlite3_bind_null(int *param_1,int param_2);
uint32_t sqlite3_bind_double(int *param_1,int param_2,ulonglong param_3);
uint32_t sqlite3_bind_int(int *param_1,int param_2,int param_3);
uint32_t sqlite3_bind_int64(int *param_1,int param_2,uint32_t param_3,uint32_t param_4);
uint32_t sqlite3_bind_zeroblob(int *param_1,int param_2,int param_3);
sqlite3_bind_pointer(int *param_1,int param_2,uint32_t param_3,uint8_t *param_4,void *param_5);
sqlite3_bind_text16(int *param_1,int param_2,int param_3,uint32_t param_4,void *param_5);
int sqlite3_bind_value(int param_1,int param_2,ulonglong *param_3);
uint32_t sqlite3_bind_blob(int *param_1,int param_2,int param_3,uint32_t param_4,void *param_5);
uint32_t sqlite3_bind_text(int *param_1,int param_2,int param_3,uint32_t param_4,void *param_5);
sqlite3_bind_blob64(int *param_1,int param_2,int param_3,uint param_4,int param_5,void *param_6);
uint32_t sqlite3_bind_zeroblob64(int *param_1,int param_2,uint param_3,uint param_4);
int sqlite3_vsnprintf(int param_1,int param_2,uint32_t param_3,uint32_t param_4);
uint8_t * sqlite3MPrintf(int param_1,uint32_t param_2);
void sqlite3VdbeError(int *param_1,uint32_t param_2);
uint32_t sqlite3VdbeCheckFk(int *param_1,int param_2);
void sqlite3ErrorMsg(int *param_1,uint32_t param_2);
sqlite3ExprFunctionUsable_isra_381(int *param_1,uint param_2,uint *param_3,uint32_t *param_4);
uint32_t sqlite3Savepoint(uint32_t *param_1,int param_2,uint32_t *param_3);
uint sqlite3TwoPartName(int *param_1,uint32_t *param_2,int param_3,int *param_4);
sqlite3ResolveOrderGroupBy_isra_385(int *param_1,int *param_2,int *param_3,uint32_t param_4);
bool sqlite3ResolveExprNames(int *param_1,int param_2);
uint32_t sqlite3ResolveExprListNames(int *param_1,int *param_2);
uint32_t * sqlite3PExpr(int *param_1,uint8_t param_2,int param_3,int param_4);
int sqlite3ExprAnd(int param_1,int param_2,int param_3);
void sqlite3AddColumn(int *param_1,uint32_t *param_2,uint32_t *param_3);
void sqlite3AddDefaultValue(int *param_1,int param_2,void *param_3,int param_4);
uint32_t * sqlite3AddGenerated(uint32_t *param_1,int param_2,uint32_t *param_3);
uint32_t sqlite3HasExplicitNulls(uint32_t param_1,int *param_2);
uint * sqlite3SrcListEnlarge(int *param_1,uint *param_2,uint param_3,int param_4);
uint32_t * sqlite3TriggerStepSrc(int *param_1,int param_2);
byte sqlite3JoinType(uint32_t param_1,int param_2,uint32_t param_3,int param_4);
sqlite3TriggersExist(int *param_1,int param_2,uint param_3,int *param_4,uint *param_5);
uint32_t sqlite3IsReadOnly(int *param_1,uint32_t *param_2,int param_3);
sqlite3FkLocateIndex(int param_1,int param_2,uint32_t *param_3,int *param_4,int *param_5);
void sqlite3ExprListCheckLength(int *param_1,int *param_2,uint32_t param_3);
void sqlite3AddReturning(int *param_1,int param_2);
void sqlite3WindowAttach(uint32_t param_1,int param_2,int param_3);
int * sqlite3WithAdd(int *param_1,int *param_2,int *param_3);
int * sqlite3GetCollSeq(int *param_1,uint8_t param_2,int *param_3,int param_4);
uint32_t * sqlite3LocateCollSeq(int *param_1,char *param_2);
void sqlite3AddCollateType(int param_1,uint32_t *param_2);
uint32_t * sqlite3ExprCollSeq(int *param_1,byte *param_2);
void sqlite3BinaryCompareCollSeq(uint32_t param_1,int param_2,int param_3);
sqlite3SelectAddColumnTypeAndCollation(int *param_1,int param_2,int param_3,uint8_t param_4);
void substSelect_constprop_606(uint32_t param_1,int param_2);
sqlite3KeyInfoFromExprList(int *param_1,int *param_2,int param_3,int param_4);
void sqlite3ExprCompareCollSeq(uint32_t param_1,int param_2);
char * sqlite3_vtab_collation(int *param_1,int param_2);
int * sqlite3KeyInfoOfIndex(int *param_1,int param_2);
void sqlite3VdbeSetP4KeyInfo(int param_1);
sqlite3OpenTable(int param_1,uint32_t param_2,uint32_t param_3,uint32_t *param_4,int param_5);
sqlite3OpenTable_constprop_616(int param_1,uint32_t param_2,uint32_t *param_3,int param_4);
sqlite3CheckObjectName(int *param_1,byte *param_2,uint32_t param_3,byte *param_4);
void sqlite3ExprAssignVarNumber(int *param_1,int param_2,uint param_3);
sqlite3SrcListAppendFromTerm_constprop_563(uint32_t param_1,uint32_t *param_2,int param_3);
sqlite3FkLocateIndex_constprop_576(int param_1,int param_2,uint32_t *param_3,int *param_4);
uint32_t * sqlite3PExpr_constprop_632(int *param_1,uint8_t param_2,int param_3);
int * sqlite3ExprListAppendVector(int *param_1,int *param_2,int *param_3,char *param_4);
uint32_t * sqlite3PExpr_constprop_633(int *param_1,uint8_t param_2,int param_3);
uint32_t sqlite3ExprCheckIN(int param_1,int param_2);
int * sqlite3PExprAddSelect(int *param_1,int param_2,int param_3);
sqlite3ExprFunction(int *param_1,int *param_2,uint32_t *param_3,int param_4);
sqlite3ResolveSelfReference_constprop_566(int *param_1,uint32_t *param_2,uint param_3,int param_4);
void sqlite3ErrorWithMsg(int *param_1,uint param_2,int param_3);
uint8_t * sqlite3_errmsg16(int param_1);
sqlite3_create_collation(int param_1,int param_2,byte param_3,uint32_t param_4,uint32_t param_5);
void sqlite3VdbeExplain(int *param_1,char param_2,uint32_t param_3);
sqlite3ExprCompare_part_446(uint32_t param_1,char *param_2,char *param_3,int param_4);
uint32_t sqlite3ExprCompare(int param_1,char *param_2,char *param_3,uint32_t param_4);
bool sqlite3ExprImpliesExpr(char *param_1,uint32_t param_2);
int sqlite3ExprCompare_constprop_622(int param_1,int param_2,uint32_t param_3);
int sqlite3ExprListCompare(int *param_1,int *param_2,uint32_t param_3);
int sqlite3WindowCompare_part_448(uint32_t param_1,int param_2,int param_3,int param_4);
uint32_t sqlite3_memory_alarm(void);
uint32_t sqlite3_os_end(void);
uint32_t sqlite3_enable_load_extension(int param_1,int param_2);
sqlite3_config(uint32_t param_1,uint32_t *param_2,int param_3,uint32_t *param_4,int param_5);
int sqlite3_initialize_part_471(void);
uint32_t sqlite3_initialize(void);
char * sqlite3_vfs_find(char *param_1);
uint64_t sqlite3_vfs_register(int param_1,int param_2);
uint64_t sqlite3_vfs_unregister(int param_1);
uint64_t sqlite3_soft_heap_limit64(uint param_1,int param_2);
uint64_t sqlite3_hard_heap_limit64(uint param_1,int param_2);
int sqlite3_malloc(uint param_1);
int sqlite3_malloc64(uint param_1,int param_2);
int walIndexReadHdr(int param_1,uint32_t *param_2);
uint32_t sqlite3_realloc(void);
uint32_t sqlite3_realloc64(void);
uint8_t * sqlite3_vmprintf(uint32_t param_1,uint32_t param_2);
void sqlite3_reset_auto_extension(void);
uint sqlite3_complete16(char *param_1);
void sqlite3_randomness_part_477(int param_1,uint8_t *param_2);
void sqlite3_randomness(int param_1,int param_2);
int sqlite3WalClose(int *param_1,uint32_t param_2,uint32_t param_3,int param_4);
sqlite3Checkpoint(int param_1,int param_2,int param_3,uint32_t param_4,uint32_t param_5);
uint32_t sqlite3WalDefaultHook(int param_1,int param_2,char *param_3,int param_4);
uint32_t sqlite3_wal_checkpoint(int param_1,char *param_2);
int sqlite3_sleep(int param_1);
uint32_t sqlite3_shutdown(void);
uint8_t * sqlite3_mprintf(uint32_t param_1);
uint32_t sqlite3LoadExtension(int *param_1,char *param_2,char *param_3,int *param_4);
sqlite3_load_extension(int param_1,uint32_t param_2,uint32_t param_3,uint32_t param_4);
uint32_t sqlite3NotPureFunc(int param_1);
uint32_t sqlite3_overload_function(int param_1,uint32_t param_2,uint32_t param_3);
void sqlite3InvalidFunction(int param_1);
int sqlite3_auto_extension(int param_1);
uint32_t * sqlite3_value_dup(uint32_t *param_1);
uint32_t * sqlite3_str_new(int param_1);
uint32_t * sqlite3ResultSetOfSelect(int *param_1,int param_2,char param_3);
uint32_t sqlite3ViewGetColumnNames(int *param_1,uint32_t *param_2);
uint32_t sqlite3_get_table_cb(int *param_1,int param_2,int param_3,int param_4);
void sqlite3_soft_heap_limit(uint param_1);
uint32_t sqlite3_os_init(void);
int pagerWriteLargeSector_isra_478(int param_1,uint *param_2);
int sqlite3PagerWrite(int param_1);
int pager_write_pagelist(int *param_1,int param_2);
int pager_playback(int *param_1,int param_2);
uint sqlite3PagerSharedLock(int *param_1);
uint sqlite3PagerSetJournalMode(int *param_1,uint param_2);
int pagerPlaybackSavepoint(int param_1,uint32_t *param_2);
uint sqlite3PagerRollback(int param_1);
void pagerUnlockAndRollback(int param_1);
uint sqlite3BtreeCommitPhaseTwo_part_485(int *param_1,int param_2);
void sqlite3PagerUnrefPageOne(int param_1);
uint32_t sqlite3PagerClose(int param_1,int param_2);
uint32_t sqlite3OpenTempDatabase(int *param_1);
void sqlite3CodeVerifySchemaAtToplevel(int param_1,int param_2);
void sqlite3BeginWriteOperation_constprop_568(int param_1,int param_2);
void sqlite3BeginWriteOperation(int param_1,byte param_2,int param_3);
void sqlite3CodeVerifyNamedSchema(int *param_1,byte *param_2);
sqlite3FindInIndex(int *param_1,int param_2,uint param_3,int *param_4,int param_5,int *param_6);
uint sqlite3Select(int *param_1,uint8_t *param_2,byte *param_3);
int sqlite3CodeSubselect(int param_1,char *param_2);
void sqlite3ExprIfTrue(int param_1,byte *param_2,int param_3,uint param_4);
void sqlite3ExprIfFalse(int param_1,byte *param_2,uint32_t param_3,uint param_4);
uint sqlite3ExprCodeTarget(int *param_1,char *param_2,uint param_3);
void sqlite3ExprCode(int param_1,int param_2);
void sqlite3FinishCoding(int *param_1);
int sqlite3ExprCodeRunJustOnce(int *param_1,int param_2,int param_3);
uint32_t ** sqlite3Vacuum(uint32_t ***param_1,int param_2,int param_3);
void sqlite3ExprCodeGeneratedColumn(int *param_1,int param_2,uint32_t param_3);
sqlite3ExprCodeGetColumnOfTable(int *param_1,int param_2,int param_3,int param_4,uint32_t param_5);
void sqlite3ExprCodeTemp(int param_1,char *param_2,int *param_3);
int sqlite3ExprCodeIN(int *param_1,int param_2,int param_3,int param_4);
sqlite3ExprCodeExprList(int param_1,int *param_2,int param_3,int param_4,byte param_5);
void sqlite3RefillIndex(int *param_1,uint32_t *param_2,int param_3);
int * sqlite3_backup_init(int param_1,uint32_t param_2,int param_3,uint32_t param_4);
int sqlite3BtreeRollback(int *param_1,int param_2,uint32_t param_3);
uint32_t sqlite3BtreeClose(uint32_t *param_1);
void sqlite3RollbackAll(int param_1,int param_2);
void sqlite3LeaveMutexAndCloseZombie(int *param_1);
int sqlite3_backup_finish(int *param_1);
uint32_t sqlite3Close(int param_1,int param_2);
void sqlite3_close(void);
void sqlite3_close_v2(void);
void sqlite3VdbeFreeCursor_isra_511(uint32_t param_1,char *param_2);
int sqlite3VdbeFrameRestore(int *param_1);
int sqlite3BtreeBeginTrans_constprop_580(int *param_1);
uint sqlite3BtreeBeginTrans(int *param_1,int param_2,uint *param_3);
void sqlite3BtreeUpdateMeta(uint32_t *param_1,int param_2,uint param_3);
int sqlite3BtreeSetVersion(int *param_1,int param_2);
int pager_incr_changecounter_isra_487(int param_1);
btreeOverwriteContent(uint32_t param_1,char *param_2,int param_3,int param_4,size_t param_5);
int btreeOverwriteCell(int param_1,int param_2);
int sqlite3BtreeSavepoint_part_493(int *param_1,int param_2,int param_3);
int vdbeCloseStatement(int *param_1,int param_2);
int btreeCreateTable(uint32_t *param_1,uint *param_2);
int sqlite3BtreeInsert(byte *param_1,uint32_t *param_2,uint param_3,int param_4);
int sqlite3BtreeDelete(char *param_1,byte param_2);
void sqlite3BtreeClearTable(uint32_t *param_1,int param_2,uint32_t param_3);
void sqlite3_open(void);
void sqlite3_open_v2(uint32_t param_1,uint32_t param_2,uint32_t param_3,uint32_t param_4);
uint sqlite3_open16(char *param_1,int *param_2);
int pagerWalFrames(int param_1,int param_2,uint param_3,int param_4);
uint pagerStress(int param_1,uint32_t *param_2);
int sqlite3_db_cacheflush(int param_1);
int sqlite3PagerCommitPhaseOne(int param_1,char *param_2,int param_3);
uint32_t sqlite3VdbeHalt(int *param_1);
uint sqlite3VdbeReset(int *param_1);
uint32_t sqlite3VdbeFinalize(int *param_1);
uint32_t sqlite3_blob_write(uint *param_1,uint32_t *param_2,uint param_3,uint param_4);
uint32_t sqlite3_blob_read(uint *param_1,uint32_t param_2,uint param_3,uint param_4);
uint32_t sqlite3_finalize(int *param_1);
uint32_t sqlite3_blob_close(int param_1);
uint32_t sqlite3_reset(int *param_1);
int sqlite3_backup_step(int *param_1,int param_2);
int sqlite3RunVacuum(int *param_1,int param_2,int param_3,int param_4);
uint sqlite3_step_part_530(int *param_1);
uint32_t sqlite3_step(int *param_1);
int sqlite3_exec(int param_1,byte *param_2,void *param_3,uint32_t param_4,int *param_5);
int sqlite3AnalysisLoad(int param_1,int param_2);
int sqlite3InitOne(int param_1,int param_2,int *param_3,uint32_t param_4);
int sqlite3Init(int param_1,uint32_t param_2);
int sqlite3ReadSchema(int *param_1);
int sqlite3LocateTable(int *param_1,uint param_2,int *param_3,int param_4);
void sqlite3LocateTableItem(int *param_1,int *param_2);
int sqlite3SrcListLookup(uint32_t *param_1,int param_2);
void sqlite3AlterBeginAddColumn(int *param_1,int param_2);
sqlite3Insert(int *param_1,int param_2,int param_3,int *param_4,uint param_5,int *param_6);
void sqlite3DeleteFrom_constprop_551(int *param_1,int param_2,int param_3);
sqlite3Pragma(int *param_1,uint32_t param_2,int *param_3,uint32_t param_4,int param_5);
void sqlite3Analyze(int *param_1,int param_2,int param_3);
void sqlite3_prepare(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void sqlite3_prepare_v2(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void sqlite3_prepare_v3(uint32_t param_1,uint32_t param_2,uint32_t param_3,uint param_4);
void sqlite3_prepare16(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void sqlite3_prepare16_v2(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void sqlite3_prepare16_v3(uint32_t param_1,uint32_t param_2,uint32_t param_3,uint param_4);
uint32_t sqlite3InitCallback(int *param_1,uint32_t param_2,int param_3);
void sqlite3NestedParse(int *param_1,uint32_t param_2);
void sqlite3DropTriggerPtr(int *param_1,uint32_t *param_2);
void sqlite3DropTable(int *param_1,int param_2,int param_3,int param_4);
void sqlite3AlterRenameTable(int *param_1,int param_2);
void sqlite3AlterFinishAddColumn(int *param_1,uint32_t *param_2);
void sqlite3AlterDropColumn(int *param_1,int param_2);
sqlite3AlterRenameColumn(int *param_1,int param_2,uint32_t param_3,uint32_t *param_4);
void sqlite3VtabFinishParse(int *param_1,int *param_2);
sqlite3CreateIndex_constprop_553(int *param_1,int *param_2,int param_3,int param_4,byte param_5);
void sqlite3EndTable(int *param_1,int *param_2,int *param_3,char param_4,int param_5);
sqlite3AddPrimaryKey(uint32_t *param_1,int *param_2,uint8_t param_3,int param_4,int param_5);
uint32_t sqlite3_declare_vtab(int param_1);
void renameColumnFunc(int *param_1,uint32_t param_2,int param_3);
uint32_t sqlite3_blob_reopen(uint *param_1,uint32_t param_2,uint32_t param_3);
uint32_t sqlite3_global_recover(void);
nitrox_SQLite_callback_CheckDBVersion(uint32_t param_1,uint32_t param_2,uint32_t *param_3);
nitrox_SQLite_callback_FindUserFast(uint32_t param_1,uint32_t param_2,uint32_t *param_3);
nitrox_SQLite_callback_TableExists(uint32_t param_1,uint32_t param_2,uint32_t *param_3);
uint32_t nitrox_SQLite_callback_GetMapRecords(uint32_t param_1,uint32_t param_2,int param_3);
nitrox_SQLite_callback_deletemail(uint32_t param_1,uint32_t param_2,uint32_t *param_3);
nitrox_SQLite_callback_loadsingleuser(uint32_t param_1,uint32_t param_2,uint32_t *param_3);
uint32_t nitrox_SQLite_callback_mails(uint32_t param_1,uint32_t param_2,uint32_t *param_3);
uint32_t nitrox_SQLite_callback_PrintMapRecords(uint32_t param_1,uint32_t param_2,int param_3);
uint32_t nitrox_SQLite_callback_users(uint32_t param_1,uint32_t param_2,uint32_t *param_3);
uint32_t nitrox_SQLite_callback_bans(uint32_t param_1,uint32_t param_2,uint32_t *param_3);
uint32_t nitrox_SQLite_callback_mutes(uint32_t param_1,uint32_t param_2,uint32_t *param_3);
void nitrox_SQLite_FatalError(void);
void nitrox_SQLite_InitUsersTable(void);
void nitrox_SQLite_LoadUsers(void);
void nitrox_SQLite_SaveUsers(uint32_t param_1);
void nitrox_SQLite_InitBansTable(void);
void nitrox_SQLite_LoadBans(void);
uint32_t nitrox_SQLite_FindBan(uint32_t param_1);
void nitrox_SQLite_SaveBans(uint32_t param_1);
void nitrox_SQLite_close(void);
void nitrox_SQLite_CheckDBVersion(void);
void nitrox_SQLite_init(void);
void nitrox_SQLite_InitMutesTable(void);
void nitrox_SQLite_LoadMutes(void);
uint32_t nitrox_SQLite_FindMute(uint32_t param_1);
void nitrox_SQLite_SaveMutes(uint32_t param_1);
uint32_t nitrox_SQLite_FindUserFastIndex(uint32_t param_1);
uint32_t nitrox_SQLite_FindUserFast(uint32_t param_1);
void nitrox_SQLite_InitMailsTable(void);
void nitrox_SQLite_MailTo(int param_1);
void nitrox_SQLite_FindMails(int param_1);
void nitrox_SQLite_DeleteMail(int param_1,uint32_t param_2);
void nitrox_SQLite_SaveBan(int param_1,int param_2);
void nitrox_SQLite_SaveMute(int param_1,int param_2);
uint32_t nitrox_SQLite_TableExists(uint32_t param_1);
void nitrox_SQLite_InitRecordsTable(void);
void nitrox_SQLite_UpdateMapFragsRecords(uint32_t param_1,uint32_t param_2);
void nitrox_SQLite_UpdateMapReviveSpreeRecords(uint32_t param_1,uint32_t param_2);
void nitrox_SQLite_UpdateMapSpreeRecords(uint32_t param_1,uint32_t param_2);
void nitrox_SQLite_SaveMapRecords(void);
void nitrox_SQLite_FindMapRecords(uint32_t param_1);
void nitrox_SQLite_GetMapRecords(uint32_t param_1);
uint32_t nitrox_SQLite_ClearMapRecords(uint32_t param_1);
void nitrox_SQLite_ClearAllMapRecords(void);
void nitrox_SQLite_LoadSingleUser(int param_1);
void nitrox_SQLite_ReloadUser(int param_1);
void nitrox_SQLite_SaveUser(int param_1,int param_2);
void nitrox_SQLite_MigrateUsers(uint32_t param_1,uint32_t param_2);

#endif

