#ifndef NITMOD_LUA_H
#define NITMOD_LUA_H

/* Embedded Lua VM and bindings */

#include "nitmod_types.h"
#include "nitmod_globals.h"

uint32_t G_LuaCall(int param_1,uint32_t param_2,uint32_t param_3,uint32_t param_4);
bool G_LuaGetNamedFunction(int param_1,uint32_t param_2);
uint32_t G_LuaStartVM(int param_1);
void G_LuaStopVM(int *param_1);
uint32_t G_LuaInit(void);
void G_LuaShutdown(void);
void G_LuaStatus(uint32_t param_1);
int G_LuaGetVM(int param_1);
void G_LuaHook_InitGame(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void G_LuaHook_ShutdownGame(uint32_t param_1);
void G_LuaHook_RunFrame(uint32_t param_1);
G_LuaHook_ClientConnect(uint32_t param_1,uint32_t param_2,uint32_t param_3,uint32_t param_4);
void G_LuaHook_ClientDisconnect(uint32_t param_1);
void G_LuaHook_ClientBegin(uint32_t param_1);
void G_LuaHook_ClientUserinfoChanged(uint32_t param_1);
uint32_t G_LuaHook_ClientCommand(uint32_t param_1,uint32_t param_2);
uint32_t G_LuaHook_ConsoleCommand(uint32_t param_1);
uint32_t G_LuaHook_UpgradeSkill(uint32_t param_1,uint32_t param_2);
uint32_t G_LuaHook_SetPlayerSkill(uint32_t param_1,uint32_t param_2);
void G_LuaHook_Print(uint32_t param_1);
G_LuaHook_Obituary(uint32_t param_1,uint32_t param_2,uint32_t param_3,uint32_t param_4);
uint32_t G_LuaHook_ReceivedGlobalStats(uint32_t param_1,uint32_t param_2);
uint32_t luaM_toobig(uint32_t param_1);
void luaM_realloc_(int param_1,uint32_t param_2,int param_3,int param_4);
void luaA_pushobject(int param_1,uint32_t *param_2);
uint32_t lua_checkstack(int param_1,int param_2);
void lua_xmove(int param_1,int param_2,int param_3);
void lua_setlevel(int param_1,int param_2);
uint32_t lua_atpanic(int param_1,uint32_t param_2);
void lua_newthread(int param_1);
int lua_gettop(int param_1);
void lua_settop(int param_1,int param_2);
void lua_remove(int param_1,int param_2);
void lua_insert(int param_1,int param_2);
void lua_replace(int param_1,int param_2);
void lua_pushvalue(int param_1,int param_2);
uint32_t lua_type(int param_1,int param_2);
char * lua_typename(uint32_t param_1,int param_2);
bool lua_iscfunction(int param_1,int param_2);
bool lua_isnumber(int param_1,int param_2);
bool lua_isstring(int param_1,int param_2);
bool lua_isuserdata(int param_1,int param_2);
uint32_t lua_rawequal(int param_1,int param_2,int param_3);
bool lua_equal(int param_1,int param_2,int param_3);
uint32_t lua_lessthan(int param_1,int param_2,int param_3);
long double lua_tonumber(int param_1,int param_2);
uint32_t lua_tointeger(int param_1,int param_2);
bool lua_toboolean(int param_1,int param_2);
int lua_tolstring(int param_1,int param_2,uint32_t *param_3);
uint32_t lua_objlen(int param_1,int param_2);
uint32_t lua_tocfunction(int param_1,int param_2);
int lua_touserdata(int param_1,int param_2);
uint32_t lua_tothread(int param_1,int param_2);
int lua_topointer(int param_1,int param_2);
void lua_pushnil(int param_1);
void lua_pushnumber(int param_1,uint64_t param_2);
void lua_pushinteger(int param_1,int param_2);
void lua_pushlstring(int param_1,uint32_t param_2,uint32_t param_3);
void lua_pushstring(int param_1,char *param_2);
void lua_pushvfstring(int param_1);
void lua_pushfstring(int param_1,uint32_t param_2);
void lua_pushcclosure(int param_1,uint32_t param_2,int param_3);
void lua_pushboolean(int param_1,int param_2);
void lua_pushlightuserdata(int param_1,uint32_t param_2);
bool lua_pushthread(int param_1);
void lua_gettable(int param_1,int param_2);
void lua_getfield(int param_1,int param_2,char *param_3);
void lua_rawget(int param_1,int param_2);
void lua_rawgeti(int param_1,int param_2,uint32_t param_3);
void lua_createtable(int param_1,uint32_t param_2,uint32_t param_3);
uint32_t lua_getmetatable(int param_1,int param_2);
void lua_getfenv(int param_1,int param_2);
void lua_settable(int param_1,int param_2);
void lua_setfield(int param_1,int param_2,char *param_3);
void lua_rawset(int param_1,int param_2);
void lua_rawseti(int param_1,int param_2,uint32_t param_3);
uint32_t lua_setmetatable(int param_1,int param_2);
uint32_t lua_setfenv(int param_1,int param_2);
void lua_call(int param_1,int param_2,int param_3);
void lua_pcall(int param_1,int param_2,int param_3,int param_4);
void lua_cpcall(int param_1,uint32_t param_2,uint32_t param_3);
void lua_load(uint32_t param_1,uint32_t param_2,uint32_t param_3,uint8_t *param_4);
void lua_dump(int param_1,uint32_t param_2,uint32_t param_3);
uint8_t lua_status(int param_1);
uint lua_gc(int param_1,uint32_t param_2,int param_3);
uint32_t lua_error(uint32_t param_1);
void lua_next(int param_1,int param_2);
void lua_concat(int param_1,int param_2);
uint32_t lua_getallocf(int param_1,uint32_t *param_2);
void lua_setallocf(int param_1,uint32_t param_2,uint32_t param_3);
int lua_newuserdata(int param_1,uint32_t param_2);
uint8_t * lua_getupvalue(int param_1,int param_2,int param_3);
uint8_t * lua_setupvalue(int param_1,int param_2,int param_3);
void luaS_resize(int param_1,int param_2);
uint32_t * luaS_newlstr(int param_1,uint32_t *param_2,uint param_3);
void luaS_newudata(int param_1,uint param_2,uint32_t param_3);
uint32_t luaopen_string(uint32_t param_1);
void luaK_code(int *param_1,uint32_t param_2,uint32_t param_3);
void luaK_nil(int *param_1,int param_2,int param_3);
uint luaK_jump(int *param_1);
void luaK_ret(int *param_1,int param_2,int param_3);
void luaK_getlabel(int param_1);
void luaK_patchlist(int *param_1,int param_2,int param_3);
void luaK_patchtohere(int *param_1,int param_2);
void luaK_concat(int *param_1,uint *param_2,uint param_3);
void luaK_checkstack(int *param_1,int param_2);
void luaK_reserveregs(int *param_1,int param_2);
int luaK_stringK(int *param_1,int param_2);
int luaK_numberK(int *param_1,uint64_t param_2);
void luaK_setreturns(int *param_1,int *param_2,int param_3);
void luaK_setoneret(int *param_1,int *param_2);
void luaK_dischargevars(int *param_1,int *param_2);
void luaK_exp2nextreg(int *param_1,int *param_2);
uint luaK_exp2anyreg(int *param_1,int *param_2);
void luaK_exp2val(int *param_1,int *param_2);
uint luaK_exp2RK(int *param_1,uint *param_2);
void luaK_storevar(int param_1,uint *param_2,int *param_3);
void luaK_self(int *param_1,int *param_2,int *param_3);
void luaK_goiftrue(int *param_1,uint32_t *param_2);
void luaK_indexed(int *param_1,uint32_t *param_2,uint *param_3);
void luaK_prefix(int *param_1,int param_2,int *param_3);
void luaK_infix(int *param_1,uint32_t param_2,uint *param_3);
void luaK_posfix(int *param_1,uint32_t param_2,int *param_3,int *param_4);
void luaK_fixline(int *param_1,uint32_t param_2);
void luaK_codeABC(int *param_1,uint param_2,int param_3,int param_4,int param_5);
void luaK_codeABx(int *param_1,uint param_2,int param_3,int param_4);
void luaK_setlist(int *param_1,int param_2,int param_3,int param_4);
int luaC_separateudata(int param_1,int param_2);
void luaC_callGCTM(int param_1);
void luaC_freeall(int param_1);
int luaC_step(int param_1);
void luaC_fullgc(int param_1);
void luaC_barrierf(int param_1,int param_2);
void luaC_barrierback(int param_1,int param_2);
void luaC_link(int param_1,uint32_t *param_2,uint8_t param_3);
void luaC_linkupval(int param_1,uint32_t *param_2);
uint32_t luaopen_package(uint32_t param_1);
uint32_t lua_sethook(int param_1,int param_2,int param_3,uint32_t param_4);
uint32_t lua_gethook(int param_1);
uint8_t lua_gethookmask(int param_1);
uint32_t lua_gethookcount(int param_1);
uint32_t lua_getstack(int param_1,int param_2,int param_3);
char * lua_getlocal(int param_1,int param_2,int param_3);
char * lua_setlocal(int param_1,int param_2,int param_3);
uint32_t lua_getinfo(int param_1,char *param_2,int param_3);
bool luaG_checkopenop(uint param_1);
uint64_t luaG_checkcode(void);
void luaG_errormsg(int param_1);
void luaG_runerror(int param_1,uint32_t param_2);
void luaG_typeerror(int param_1,uint param_2,uint32_t param_3);
uint32_t luaG_ordererror(uint32_t param_1,int param_2,int param_3);
void luaG_concaterror(int param_1,uint param_2,uint param_3);
void luaG_aritherror(int param_1,uint param_2,uint param_3);
void luaL_openlibs(uint32_t param_1);
void luaF_newCclosure(uint32_t param_1,int param_2,uint32_t param_3);
int luaF_newLclosure(uint32_t param_1,int param_2,uint32_t param_3);
void luaF_newupval(uint32_t param_1);
int * luaF_findupval(int param_1,uint param_2);
void luaF_freeupval(uint32_t param_1,int param_2);
void luaF_close(int param_1,uint param_2);
void luaF_newproto(uint32_t param_1);
void luaF_freeproto(uint32_t param_1,int param_2);
void luaF_freeclosure(uint32_t param_1,int param_2);
int luaF_getlocalname(int param_1,int param_2,int param_3);
uint32_t luaH_next(uint32_t param_1,int param_2,double *param_3);
int luaH_new(uint32_t param_1,int param_2,int param_3);
void luaH_free(uint32_t param_1,int param_2);
uint32_t * luaH_getnum(int param_1,int param_2);
uint32_t * luaH_getstr(int param_1,int param_2);
uint32_t * luaH_get(int param_1,double *param_2);
void luaH_setnum(uint32_t param_1,int param_2,int param_3);
void luaH_resizearray(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void luaH_set(uint32_t param_1,int param_2,double *param_3);
void luaH_setstr(uint32_t param_1,int param_2,int param_3);
uint luaH_getn(int param_1);
void luaD_seterrorobj(int param_1,int param_2,uint32_t *param_3);
uint32_t luaD_rawrunprotected(int param_1,void *param_2,uint32_t param_3);
void luaD_reallocstack(int param_1,int param_2);
void luaD_reallocCI(int param_1,int param_2);
void luaD_throw(int param_1,uint32_t param_2);
void luaD_growstack(int param_1,int param_2);
void luaD_callhook(int param_1,int param_2,uint32_t param_3);
int luaD_poscall(int param_1,uint32_t *param_2);
uint32_t luaD_precall(int param_1,int *param_2,int param_3);
void luaD_call(int param_1,uint32_t param_2,uint32_t param_3);
uint lua_resume(int param_1,int param_2);
uint32_t lua_yield(int param_1,int param_2);
int luaD_pcall(int param_1,uint32_t param_2,uint32_t param_3,int param_4,uint32_t param_5);
int luaD_protectedparser(int param_1,uint32_t param_2,uint32_t param_3);
void luaT_init(int param_1);
int luaT_gettm(int param_1,byte param_2,uint32_t param_3);
uint32_t * luaT_gettmbyobj(int param_1,int *param_2);
int * luaV_tonumber(int *param_1,int *param_2);
uint32_t luaV_tostring(uint32_t param_1,uint64_t *param_2);
void luaV_gettable(int param_1,int *param_2,uint32_t *param_3,uint32_t *param_4);
void luaV_settable(int param_1,int *param_2,uint32_t *param_3,int *param_4);
uint luaV_lessthan(int param_1,double *param_2,double *param_3);
bool luaV_equalval(int param_1,double *param_2,double *param_3);
void luaV_concat(int param_1,int param_2,int param_3);
void luaV_execute(int param_1,int param_2);
void luaB_yield(uint32_t param_1);
uint32_t luaB_corunning(uint32_t param_1);
uint32_t luaB_cocreate(uint32_t param_1);
uint32_t luaB_pairs(uint32_t param_1);
uint32_t luaB_next(uint32_t param_1);
uint32_t luaB_ipairs(uint32_t param_1);
uint32_t luaB_rawset(uint32_t param_1);
uint32_t luaB_rawget(uint32_t param_1);
void luaB_pcall(uint32_t param_1);
void luaB_xpcall(uint32_t param_1);
void luaB_error(uint32_t param_1);
int luaB_unpack(uint32_t param_1);
uint32_t luaB_type(uint32_t param_1);
int luaB_select(uint32_t param_1);
uint32_t luaB_tonumber(uint32_t param_1);
uint32_t luaB_setmetatable(uint32_t param_1);
uint32_t luaB_rawequal(uint32_t param_1);
uint32_t luaB_print(uint32_t param_1);
int luaB_dofile(uint32_t param_1);
uint32_t luaB_gcinfo(uint32_t param_1);
uint32_t luaB_collectgarbage(uint32_t param_1);
uint32_t luaB_load(uint32_t param_1);
uint32_t luaB_newproxy(uint32_t param_1);
uint32_t luaB_tostring(uint32_t param_1);
uint32_t luaB_getmetatable(uint32_t param_1);
void luaB_assert(uint32_t param_1);
uint32_t luaB_loadfile(uint32_t param_1);
uint32_t luaB_loadstring(uint32_t param_1);
uint32_t luaB_costatus(int param_1);
int luaB_auxwrap(uint32_t param_1);
int luaB_coresume(uint32_t param_1);
uint32_t luaB_cowrap(uint32_t param_1);
uint32_t luaB_getfenv(uint32_t param_1);
uint32_t luaB_setfenv(uint32_t param_1);
uint32_t luaopen_base(uint32_t param_1);
void luaX_init(uint32_t param_1);
uint32_t luaX_token2str(int param_1,int param_2);
void luaX_lexerror(int param_1,uint32_t param_2,int param_3);
void luaX_syntaxerror(int param_1,uint32_t param_2);
uint32_t luaX_newstring(int param_1,uint32_t param_2,uint32_t param_3);
void luaX_setinput(uint param_1,uint *param_2,uint param_3,uint param_4);
void luaX_next(int param_1);
void luaX_lookahead(int param_1);
uint32_t luaopen_debug(uint32_t param_1);
int luaY_parser(uint32_t param_1,uint32_t param_2,uint32_t param_3,char *param_4);
uint32_t luaopen_table(uint32_t param_1);
void luaL_where(uint32_t param_1,uint32_t param_2);
void luaL_error(uint32_t param_1,uint32_t param_2);
void luaL_argerror(uint32_t param_1,int param_2,uint32_t param_3);
void luaL_typerror(uint32_t param_1,int param_2,uint32_t param_3);
int luaL_checkoption(uint32_t param_1,uint32_t param_2,char *param_3,int *param_4);
bool luaL_newmetatable(uint32_t param_1,uint32_t param_2);
int luaL_checkudata(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void luaL_checkstack(uint32_t param_1,uint32_t param_2);
void luaL_checktype(uint32_t param_1,int param_2,int param_3);
void luaL_checkany(uint32_t param_1,uint32_t param_2);
int luaL_checklstring(uint32_t param_1,uint32_t param_2,uint32_t param_3);
char * luaL_optlstring(uint32_t param_1,uint32_t param_2,char *param_3,size_t *param_4);
long double luaL_checknumber(uint32_t param_1,uint32_t param_2);
long double luaL_optnumber(uint32_t param_1,uint32_t param_2,double param_3);
int luaL_checkinteger(uint32_t param_1,uint32_t param_2);
int luaL_optinteger(uint32_t param_1,uint32_t param_2,int param_3);
uint32_t luaL_getmetafield(uint32_t param_1,uint32_t param_2,uint32_t param_3);
uint32_t luaL_callmeta(uint32_t param_1,int param_2,uint32_t param_3);
char * luaL_findtable(uint32_t param_1,uint32_t param_2,char *param_3,uint32_t param_4);
void luaL_openlib(uint32_t param_1,int param_2,int *param_3,uint param_4);
void luaL_register(uint32_t param_1,int param_2,int *param_3);
int * luaL_prepbuffer(int *param_1);
void luaL_addlstring(int *param_1,uint8_t *param_2,int param_3);
void luaL_gsub(uint32_t param_1,char *param_2,char *param_3,char *param_4);
void luaL_addstring(int *param_1,char *param_2);
void luaL_pushresult(int *param_1);
void luaL_addvalue(int *param_1);
void luaL_buffinit(int param_1,int *param_2);
int luaL_ref(uint32_t param_1,int param_2);
void luaL_unref(uint32_t param_1,int param_2,int param_3);
uint32_t luaL_loadfile(uint32_t param_1,char *param_2);
void luaL_loadbuffer(uint32_t param_1,uint32_t param_2,uint32_t param_3,uint32_t param_4);
void luaL_loadstring(uint32_t param_1,char *param_2);
int luaL_newstate(void);
uint luaZ_fill(int *param_1);
uint luaZ_lookahead(int *param_1);
void luaZ_init(uint32_t param_1,uint32_t *param_2,uint32_t param_3,uint32_t param_4);
uint luaZ_read(uint *param_1,uint32_t *param_2,uint param_3);
uint32_t luaZ_openspace(uint32_t param_1,uint32_t *param_2,uint param_3);
uint32_t luaopen_math(uint32_t param_1);
uint32_t luaopen_os(uint32_t param_1);
void luaU_print(int param_1,int param_2);
uint luaO_int2fb(uint param_1);
uint luaO_fb2int(uint param_1);
int luaO_log2(uint param_1);
bool luaO_rawequalObj(double *param_1,double *param_2);
bool luaO_str2d(byte *param_1,double *param_2);
int luaO_pushvfstring(int param_1,char *param_2,int *param_3);
void luaO_pushfstring(uint32_t param_1,uint32_t param_2);
void luaO_chunkid(char *param_1,char *param_2,size_t param_3);
int luaE_newthread(int param_1);
void luaE_freethread(uint32_t param_1,int param_2);
uint32_t * lua_newstate(void *param_1,uint32_t param_2);
void lua_close(int param_1);
uint32_t luaopen_io(uint32_t param_1);
void luaU_undump(uint32_t param_1,uint32_t param_2,uint32_t param_3,char *param_4);
void luaU_header(uint32_t *param_1);

#endif

