#ifndef NITMOD_IMPORTS_H
#define NITMOD_IMPORTS_H

#include "nitmod_types.h"

/* libc / libstdc++ imports from the original .so PLT — do not compile stubs */

int getpagesize(void);
double ldexp(double __x,int __exponent);
int fputs(char *__s,FILE *__stream);
double fmod(double __x,double __y);
int * __errno_location(void);
void Bot_Interface_Update(void);
void Bot_Event_PostTriggerMine(void);
int sigemptyset(sigset_t *__set);
void KeyVals_SetEntity(void);
int sprintf(char *__s,char *__format,...);
void srand(uint __seed);
void Bot_TeamGameToBot(void);
long lrint(double __x);
__pid_t getpid(void);
lconv * localeconv(void);
int mkdir(char *__path,__mode_t __mode);
void ENTINDEX(gentity_s *param_1);
char * strerror(int __errnum);
int getsockname(int __fd,sockaddr *__addr,socklen_t *__len);
void __cxa_atexit(void);
void IsOmnibotLoaded(void);
int strcoll(char *__s1,char *__s2);
void KeyVals_SetString(KeyVals *this,char *param_1,char *param_2);
int memcmp(void *__s1,void *__s2,size_t __n);
void qsort(void *__base,size_t __nmemb,size_t __size,__compar_fn_t __compar);
char * inet_ntoa(in_addr __in);
void std_throw_bad_cast(void);
double asin(double __x);
void _EmplacedGunIsMountable(gentity_s *param_1);
void std_ios_base_ios_base(ios_base *this);
void __isoc99_fscanf(void);
void Bot_Interface_Shutdown(void);
void Bot_Event_EntityDeleted(void);
void Bot_Event_FireTeamDestroyed(void);
void __divdi3(void);
float sqrtf(float __x);
__sighandler_t signal(int __sig,__sighandler_t __handler);
int __xstat(int __ver,char *__filename,stat *__stat_buf);
void __gmon_start__(void);
void EntityFromHandle(void);
void CheckForMG42(gentity_s *param_1,char *param_2);
void * realloc(void *__ptr,size_t __size);
void Bot_Interface_ConsoleCommand(void);
double sinh(double __x);
void operator_delete(void *param_1);
void Bot_AddDynamiteGoal(void);
void __isoc99_sscanf(void);
int __xstat64(int __ver,char *__filename,stat64 *__stat_buf);
tm * localtime(time_t *__timer);
void SendDeferredGoals(void);
void Omnibot_strncpy(char *param_1,char *param_2,int param_3);
void std_ctype_char_M_widen_init(void);
void KeyVals_Reset(KeyVals *this);
double strtod(char *__nptr,char **__endptr);
char * strchr(char *__s,int __c);
int vsnprintf(char *__s,size_t __maxlen,char *__format,__gnuc_va_list __arg);
ssize_t recv(int __fd,void *__buf,size_t __n,int __flags);
char * getenv(char *__name);
void Omnibot_LoadLibrary(int param_1,char *param_2,char *param_3);
void * calloc(size_t __nmemb,size_t __size);
void Bot_Event_FireTeamCreated(void);
in_addr_t inet_addr(char *__cp);
int system(char *__command);
char * strncpy(char *__dest,char *__src,size_t __n);
int putchar(int __c);
void std_ios_base_Init_Init(Init *this);
ssize_t sendto(int __fd,void *__buf,size_t __n,int __flags,sockaddr *__addr,socklen_t __addr_len);
void Omnibot_LL(char *param_1);
void Bot_Event_ClientDisConnected(void);
double pow(double __x,double __y);
int listen(int __fd,int __n);
__off64_t lseek64(int __fd,__off64_t __offset,int __whence);
char * fgets(char *__s,int __n,FILE *__stream);
void Bot_Event_FireTeam_Proposal(void);
int rename(char *__old,char *__new);
void * memset(void *__s,int __c,size_t __n);
void HandleFromEntity(gentity_s *param_1);
void Bot_Interface_Init(void);
void Bot_Event_Death(void);
int _IO_getc(_IO_FILE *__fp);
double floor(double __x);
char * strrchr(char *__s,int __c);
void dlsym(void);
double modf(double __x,double *__iptr);
void Omnibot_Load_PrintMsg(char *param_1);
void KeyVals_SetKeyVal(KeyVals *this,char *param_1,obUserData_t *param_2);
void __moddi3(void);
void GetEntityCenter(void);
char * tmpnam(char *__s);
void INDEXENT(int param_1);
void Bot_Event_JoinedFireTeam(void);
double exp(double __x);
void Bot_Event_ChatMessage(void);
void Bot_Event_Healed(void);
int ungetc(int __c,FILE *__stream);
FILE * tmpfile(void);
int gettimeofday(timeval *__tv,__timezone_ptr_t __tz);
long strtol(char *__nptr,char **__endptr,int __base);
__int32_t ** __ctype_toupper_loc(void);
void free(void *__ptr);
int __lxstat64(int __ver,char *__filename,stat64 *__stat_buf);
void backtrace_symbols(void);
double atan(double __x);
void Bot_Event_LeftFireTeam(void);
void IsBot(gentity_s *param_1);
void Omnibot_Load_PrintErr(char *param_1);
void std_string_Rep_M_destroy(allocator *param_1);
void Bot_Event_RecievedAmmo(void);
float floorf(float __x);
int sigaction(int __sig,sigaction *__act,sigaction *__oact);
void dlerror(void);
int fflush(FILE *__stream);
float ceilf(float __x);
double sqrt(double __x);
int accept(int __fd,sockaddr *__addr,socklen_t *__addr_len);
int ioctl(int __fd,ulong __request,...);
int socket(int __domain,int __type,int __protocol);
ushort ** __ctype_b_loc(void);
int fseek(FILE *__stream,long __off,int __whence);
void Bot_Event_PreTriggerMine(void);
char * strsignal(int __sig);
void Bot_Event_AddWeapon(void);
int fclose(FILE *__stream);
void __umoddi3(void);
double tanh(double __x);
int _setjmp(__jmp_buf_tag *__env);
time_t mktime(tm *__tp);
int fsync(int __fd);
void Simple_EmplacedGunIsRepairable(gentity_s *param_1);
clock_t clock(void);
double acos(double __x);
void _TankIsMountable(gentity_s *param_1);
ulong strtoul(char *__nptr,char **__endptr,int __base);
size_t strlen(char *__s);
FILE * fopen(char *__filename,char *__modes);
double cos(double __x);
void Bot_Util_CheckForGoalEntity(void);
int unlink(char *__name);
void Bot_Event_TakeDamage(void);
FILE * freopen(char *__filename,char *__modes,FILE *__stream);
void Bot_Event_KilledSomeone(void);
char * setlocale(int __category,char *__locale);
void Bot_Event_FireTeam_Warn(void);
void clearerr(FILE *__stream);
int feof(FILE *__stream);
char * strcpy(char *__dest,char *__src);
long ftell(FILE *__stream);
void longjmp(__jmp_buf_tag *__env,int __val);
void Bot_WeaponGameToBot(void);
int printf(char *__format,...);
void std_locale_locale(locale *this);
void Omnibot_FixPath(char *param_1);
int bind(int __fd,sockaddr *__addr,socklen_t __len);
void KeyVals_SetInt(KeyVals *this,char *param_1,int param_2);
void Bot_Util_CheckForSuicide(void);
void Bot_Event_EntityCreated(gentity_s *param_1);
void KeyVals_GetKeyVal(KeyVals *this,char *param_1,obUserData_t *param_2);
void obUtilBotContentsFromGameContents(int param_1);
int strcasecmp(char *__s1,char *__s2);
void * operator_new(uint param_1);
void Bot_EntInvisibleBySmokeBomb(float *param_1,float *param_2);
void KeyVals_Set(KeyVals *this,char *param_1,obUserData_t *param_2);
int close(int __fd);
size_t fwrite(void *__ptr,size_t __size,size_t __n,FILE *__s);
double frexp(double __x,int *__exponent);
void std_ios_init(streambuf *param_1);
void Omnibot_FreeLibrary(void);
int fprintf(FILE *__stream,char *__format,...);
char * strstr(char *__haystack,char *__needle);
void Bot_Queue_EntityCreated(void);
time_t time(time_t *__timer);
void Bot_Event_Spectated(void);
double log10(double __x);
int setvbuf(FILE *__stream,char *__buf,int __modes,size_t __n);
char * strncat(char *__dest,char *__src,size_t __n);
int remove(char *__filename);
void std_string_M_mutate(uint param_1,uint param_2,uint param_3);
void * malloc(size_t __size);
void Bot_Interface_InitHandles(void);
void Omnibot_GetLibraryPath(void);
void KeyVals_KeyVals(KeyVals *this);
double atan2(double __y,double __x);
void OB_VA(void);
int fputc(int __c,FILE *__stream);
void obUtilBotSurfaceFromGameSurface(int param_1);
char * strtok(char *__s,char *__delim);
size_t strnlen(char *__string,size_t __maxlen);
void std_string_assign(string *param_1);
uint sleep(uint __seconds);
void Bot_Event_Revived(void);
void std_throw_logic_error(char *param_1);
void LineAABBIntersection(void);
void backtrace(void);
void std_string_assign(char *param_1,uint param_2);
void Bot_Event_RemoveWeapon(void);
void * memmove(void *__dest,void *__src,size_t __n);
__int32_t ** __ctype_tolower_loc(void);
char * strcat(char *__dest,char *__src);
void Bot_Event_ClientConnected(void);
double log(double __x);
void Bot_AddFallenTeammateGoals(void);
int __fxstat64(int __ver,int __fildes,stat64 *__stat_buf);
int setsockopt(int __fd,int __level,int __optname,void *__optval,socklen_t __optlen);
void UpdateMG42(gentity_s *param_1);
int rand(void);
int utimes(char *__file,timeval *__tvp);
void std_string_Rep_S_create(uint param_1,uint param_2,allocator *param_3);
tm * gmtime(time_t *__timer);
void * memchr(void *__s,int __c,size_t __n);
int strncmp(char *__s1,char *__s2,size_t __n);
int open64(char *__file,int __oflag,...);
int _IO_putc(int __c,_IO_FILE *__fp);
void __udivdi3(void);
char * strpbrk(char *__s,char *__accept);
void Bot_PlayerClassGameToBot(void);
void Bot_Event_VoiceMacro(void);
double tan(double __x);
size_t fread(void *__ptr,size_t __size,size_t __n,FILE *__stream);
void OB_ShowLastError(char *param_1,char *param_2);
size_t strftime(char *__s,size_t __maxsize,char *__format,tm *__tp);
void Omnibot_ErrorString(void);
double cosh(double __x);
size_t strcspn(char *__s,char *__reject);
double sin(double __x);
hostent * gethostbyname(char *__name);
void Bot_Util_AllowPush(void);
void Bot_Event_InviteFireTeam(void);
void UpdateGoalEntity(void);
ssize_t recvfrom(int __fd,void *__buf,size_t __n,int __flags,sockaddr *__addr,socklen_t *__addr_len);
void _Unwind_Resume(void);
int ferror(FILE *__stream);
int strcmp(char *__s1,char *__s2);
void dlopen(void);
void __cxa_finalize(void);
void exit(int __status);
double difftime(time_t __time1,time_t __time0);
void backtrace_symbols_fd(void);
void Bot_Event_FireWeapon(void);
void _GetEntityName(void);
void Bot_Event_ResetWeapons(void);
void sincos(double __x,double *__sinx,double *__cosx);
void dlclose(void);
void Vector_Length(Vector *this);
void Bot_Util_SendTrigger(void);
void GetMG42s(void);

#endif
