#ifndef NITMOD_SPAWN_H
#define NITMOD_SPAWN_H

/* Map entity spawn (SP_*), triggers, props */

#include "nitmod_types.h"
#include "nitmod_globals.h"

void alarmbox_updateparts(int param_1,int param_2);
void alarmbox_use(int param_1,int param_2);
void alarmbox_die(int param_1);
void alarmbox_finishspawning(int param_1);
void SP_alarm_box(int param_1);
void SP_info_player_deathmatch(int param_1);
void SP_info_player_checkpoint(int param_1);
void SP_info_player_start(int param_1);
void SP_info_player_intermission(void);
void Use_Item(int param_1);
void Touch_Item_Auto(int param_1,uint32_t *param_2);
void Touch_Item(int param_1,uint32_t *param_2);
void mg42_use(uint32_t *param_1,int param_2);
void misc_spawner_use(int param_1);
void Use_Shooter(int param_1);
void mg42_die(uint32_t *param_1,uint32_t param_2,int param_3);
void mg42_spawn(int param_1);
void misc_firetrails_think(int param_1);
void misc_spawner_think(int param_1);
void mg42_touch(uint32_t *param_1,int param_2);
void mg42_think(uint32_t *param_1);
void SP_info_camp(int param_1);
void SP_info_null(int param_1);
void SP_info_notnull(int param_1);
void SP_misc_teleporter_dest(void);
void SP_misc_gamemodel(int param_1);
void SP_misc_vis_dummy(int param_1);
void SP_misc_vis_dummy_multiple(int param_1);
void SP_misc_portal_surface(int param_1);
void SP_misc_portal_camera(int param_1);
void SP_shooter_mortar(int param_1);
void SP_shooter_rocket(int param_1);
void SP_shooter_grenade(int param_1);
void SP_corona(int param_1);
void SP_dlight(int param_1);
void mg42_fire(uint32_t *param_1);
void mg42_track(int param_1,int param_2);
void mg42_stopusing(uint32_t *param_1);
void SP_mg42(int param_1);
void SP_misc_spawner(int param_1);
void SP_misc_firetrails(int param_1);
void SP_misc_constructiblemarker(int param_1);
void SP_misc_landmine(int param_1);
void SP_misc_commandmap_marker(int param_1);
void Touch_Plat(int param_1,int param_2);
void Think_BeginMoving(int param_1);
void Think_BeginMoving_rotating(int param_1);
void Use_Static(int param_1);
void Use_Func_Rotate(int param_1);
void func_explosive_spawn(int param_1);
void func_constructible_spawn(int param_1);
void func_brushmodel_delete(uint32_t param_1);
void target_effect(int param_1,uint32_t param_2);
void target_explosion_use(int param_1,uint32_t param_2,uint32_t param_3);
void func_explosive_use(int param_1,uint32_t param_2);
void func_constructible_use(int param_1);
void func_constructiblespawn(uint32_t *param_1);
void Think_SetupTrainTargets(int param_1);
void Think_SetupTrainTargets_rotating(int param_1);
void func_explosive_touch(int param_1,uint32_t param_2);
void func_explosive_alert(int param_1);
void Think_MatchTeam(int param_1);
void Think_SpawnNewDoorTrigger(int param_1);
void Use_TrinaryMover(int param_1,int param_2,int param_3);
void Use_BinaryMover(int param_1,uint32_t param_2,uint32_t param_3);
void Touch_DoorTrigger(int param_1,int param_2);
void Touch_PlatCenterTrigger(int param_1,int param_2);
void Touch_Button(int param_1,int param_2);
void SP_func_door(int param_1);
void SP_func_plat(int param_1);
void SP_func_button(int param_1);
void SP_path_corner(int param_1);
void SP_path_corner_2(int param_1);
void SP_info_train_spline_main(int param_1);
void SP_info_limbo_camera(int param_1);
void SP_func_train(int param_1);
void SP_func_train_rotating(int param_1);
void SP_func_leaky(int param_1);
void SP_func_static(int param_1);
void SP_func_rotating(int param_1);
void SP_func_bobbing(int param_1);
void SP_func_pendulum(int param_1);
void SP_func_door_rotating(int param_1);
void SP_target_effect(int param_1);
void SP_target_explosion(int param_1);
void SP_func_explosive(int param_1);
void SP_func_invisible_user(int param_1);
void func_constructible_underconstructionthink(int param_1);
void SP_func_constructible(int param_1);
void SP_func_brushmodel(int param_1);
void SP_func_debris(int param_1);
void props_bench_die(int param_1);
void Props_Barrel_Touch(void);
void props_crate32x64_die(int param_1);
void props_58x112tablew_die(int param_1);
void props_snowGenerator_use(int param_1);
void props_decoration_animate(int param_1);
void props_locker_endrattle(int param_1);
void props_locker_use(int param_1);
void props_locker_pain(int param_1);
void props_locker_tall_die(int param_1);
void Use_DamageInflictor(void);
void props_flippy_blocked(int param_1,int param_2);
void props_flamethrower_use(int param_1);
void props_flamethrower_init(int param_1);
void props_flamethrower_think(int param_1);
void props_bench_think(int param_1);
void props_crate32x64_think(int param_1);
void props_58x112tablew_think(int param_1);
void props_castlebed_animate(int param_1);
void props_castlebed_touch(int *param_1,int param_2);
void props_snowGenerator_think(int param_1);
void Use_props_decoration(int param_1);
void Props_Barrel_Pain(uint32_t *param_1);
void props_locker_death(uint32_t *param_1);
void props_castlebed_die(int param_1);
void props_radio_die(uint32_t *param_1);
void Props_Barrel_Think(uint32_t *param_1);
void Props_Barrel_Animate(uint32_t *param_1);
void props_radio_dieSEVEN(uint32_t *param_1,int param_2);
void Props_Chair_Animate(int param_1);
void SP_props_box_32(int param_1);
void SP_props_box_48(int param_1);
void SP_props_box_64(int param_1);
void SP_props_sparks(int param_1);
void SP_props_gunsparks(int param_1);
void SP_SmokeDust(int param_1);
void SP_Dust(int param_1);
void SP_Props_Bench(int param_1);
void SP_Props_Radio(int param_1);
void SP_Props_RadioSEVEN(int param_1);
void SP_Props_Locker_Tall(int param_1);
void Props_TurnLightsOff(int param_1);
void Props_Activated(int param_1);
void Props_Chair_Think(uint32_t *param_1);
void Props_Chair_Touch(uint32_t *param_1,int param_2);
void Use_Props_Shard_Generator(int param_1);
void props_decoration_death(int param_1,uint32_t param_2);
void props_statue_death(int param_1,uint32_t param_2);
void Props_Chair_Die(int param_1,uint32_t param_2,uint32_t param_3,int param_4);
void Props_Barrel_Die(uint32_t *param_1,int param_2,uint32_t param_3,int param_4);
void props_touch(int param_1,uint32_t param_2);
void props_statue_touch(int param_1,uint32_t param_2);
void Props_Chair_Skyboxtouch(int param_1);
void SP_Props_Chair(int param_1);
void SP_Props_ChairHiback(int param_1);
void SP_Props_ChairSide(int param_1);
void SP_Props_ChateauChair(int param_1);
void SP_Props_ChairChat(int param_1);
void SP_Props_ChairChatArm(int param_1);
void SP_Props_DamageInflictor(int param_1);
void SP_props_shard_generator(int param_1);
void SP_Props_Desklamp(int param_1);
void SP_OilSlick(uint32_t *param_1);
void SP_OilParticles(void);
void SP_Props_Flamebarrel(int param_1);
void SP_crate_64(int param_1);
void SP_crate_32(int param_1);
void SP_Props_Crate32x64(int param_1);
void props_flippy_table_die(int param_1);
void SP_Props_Flipping_Table(int param_1);
void SP_Props_58x112tablew(int param_1);
void SP_props_castlebed(int param_1);
void SP_props_snowGenerator(int param_1);
void SP_props_decoration(int param_1);
void SP_props_decorBRUSH(int param_1);
void SP_props_decor_Scale(int param_1);
void SP_skyportal(int param_1);
void props_statue_blocked(uint32_t *param_1);
void props_statue_animate(int param_1);
void SP_props_statue(int param_1);
void SP_props_statueBRUSH(int param_1);
void props_locker_spawn_item(uint32_t *param_1);
void props_locker_mass(int param_1);
void SP_props_footlocker(int param_1);
void SP_props_flamethrower(int param_1);
void SP_script_mover(int param_1);
void SP_script_model_med(int param_1);
void SP_script_camera(int param_1);
void SP_script_multiplayer(int param_1);
void SP_func_fakebrush(int param_1);
void SP_worldspawn(void);
void target_rumble_use(int param_1);
void Use_Target_Lock(int param_1);
void Use_target_remove_powerups(uint32_t param_1,uint32_t param_2,int param_3);
void Think_Target_Delay(int param_1);
void Use_Target_Counter(int param_1,uint32_t param_2);
void Use_Target_Alarm(uint32_t param_1,uint32_t param_2);
void Use_Target_Delay(int param_1,uint32_t param_2,uint32_t param_3);
void Use_Target_Score(int param_1,uint32_t param_2,uint32_t param_3);
void Use_Target_Print(int param_1,uint32_t param_2,int param_3);
void misc_beam_think(int param_1);
void misc_beam_start(int param_1);
void target_laser_think(uint32_t *param_1);
void target_teleporter_use(int param_1,uint32_t param_2,int param_3);
void target_relay_use(int param_1,uint32_t param_2,int param_3);
void Use_target_fog(int param_1);
void target_script_trigger_use(int param_1,uint32_t param_2);
void target_rumble_think(int param_1);
void Use_Target_Give(int param_1,uint32_t param_2,int param_3);
void Use_Target_Speaker(int param_1,uint32_t param_2,uint32_t param_3);
void target_speaker_multiple(int param_1);
void target_laser_use(uint32_t *param_1,uint32_t param_2,int param_3);
void target_laser_start(uint32_t *param_1);
void SP_target_give(int param_1);
void SP_target_remove_powerups(int param_1);
void SP_target_delay(int param_1);
void SP_target_score(int param_1);
void SP_target_print(int param_1);
void SP_target_speaker(int param_1);
void SP_misc_beam(int param_1);
void target_laser_on(uint32_t *param_1);
void target_laser_off(int param_1);
void SP_target_laser(int param_1);
void SP_target_teleporter(int param_1);
void SP_target_relay(int param_1);
void target_kill_use(int param_1,uint32_t param_2,uint32_t param_3);
void SP_target_kill(int param_1);
void SP_target_position(int param_1);
void SP_target_location(uint32_t param_1);
void SP_target_fog(int param_1);
void SP_target_counter(int param_1);
void SP_target_autosave(uint32_t param_1);
void SP_target_lock(int param_1);
void SP_target_alarm(int param_1);
void SP_target_smoke(int param_1);
void SP_target_script_trigger(int param_1);
void SP_target_rumble(int param_1);
void Use_Team_Spawnpoint(int param_1);
void Use_Team_InitialSpawnpoint(int param_1);
void SP_team_CTF_redplayer(uint32_t param_1);
void SP_team_CTF_blueplayer(uint32_t param_1);
void SP_team_CTF_redspawn(int param_1);
void SP_team_CTF_bluespawn(int param_1);
void SP_team_CTF_greenspawn(int param_1);
void SP_team_WOLF_objective(int param_1);
void SP_team_WOLF_checkpoint(int param_1);
void trigger_heal_think(int param_1);
void trigger_ammo_think(int param_1);
void Touch_ObjectiveInfo(uint32_t param_1,int param_2);
void func_timer_think(int param_1);
void trigger_always_think(uint32_t param_1);
void Use_target_push(int param_1,uint32_t param_2,int param_3);
void trigger_heal_setup(int param_1);
void trigger_ammo_setup(int param_1);
void Touch_flagonly(int param_1,int param_2);
void Touch_flagonly_multiple(int param_1,int param_2);
void Think_SetupObjectiveInfo(uint32_t *param_1);
void trigger_teleporter_touch(int param_1,int param_2);
void func_timer_use(int param_1,uint32_t param_2,uint32_t param_3);
void Use_Multi(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Touch_Multi(int param_1,int param_2);
void SP_trigger_multiple(int param_1);
void SP_trigger_always(int param_1);
void trigger_push_touch(void);
void trigger_push_use(void);
void SP_trigger_push(void);
void SP_target_push(int param_1);
void SP_trigger_teleport(int param_1);
void SP_trigger_hurt(int param_1);
void SP_trigger_removeProtection(int param_1);
void SP_misc_cabinet_health(int param_1);
void SP_trigger_heal(int param_1);
void SP_misc_cabinet_supply(int param_1);
void SP_trigger_ammo(int param_1);
void SP_func_timer(int param_1);
void SP_trigger_once(int param_1);
void trigger_aidoor_stayopen(int param_1,int param_2);
void SP_gas(void);
void SP_trigger_flagonly(int param_1);
void SP_trigger_flagonly_multiple(int param_1);
void SP_trigger_objective_info(int param_1);
void SP_trigger_concussive_dust(uint32_t param_1);

#endif

