#ifndef NITMOD_GAME_H
#define NITMOD_GAME_H

/* Remaining G_* game logic */

#include "nitmod_types.h"
#include "nitmod_globals.h"

bool G_DoAntiwarp(int param_1);
void G_SetClientSound(int param_1);
void G_TouchTriggers(int param_1);
uint32_t G_SpectatorAttackFollow(uint32_t *param_1);
void G_SetIdentifyClient(int param_1);
void G_FallDamage(uint32_t *param_1,uint32_t param_2);
void G_RunClient(int param_1);
void G_AdjustSingleClientPosition_constprop_6(int param_1,int param_2);
bool G_AntilagSafe(int param_1);
int G_StoreClientPosition(int param_1);
void G_AdjustSingleClientPosition(int param_1,int param_2,int param_3);
void G_ReAdjustSingleClientPosition(int param_1);
void G_AdjustClientPositions(uint8_t *param_1,uint32_t param_2,int param_3);
void G_ResetMarkers(int param_1);
void G_AttachBodyParts(uint *param_1);
void G_DettachBodyParts(void);
int G_SwitchBodyPartEntity(uint32_t param_1,int param_2);
void G_HistoricalTraceBegin(uint8_t *param_1);
void G_HistoricalTraceEnd(uint8_t *param_1);
void G_TempTraceIgnoreBodies(void);
bool G_SkipCorrectionSafe(int param_1);
void G_PredictPmove(int param_1,uint32_t param_2);
void G_RemoveFromAllIgnoreLists(uint32_t param_1);
uint32_t G_RegisterCharacter(uint32_t param_1,int param_2);
void G_RegisterPlayerClasses(void);
void G_UpdateCharacter(int param_1);
void G_SetDefaultLevel_part_4(int param_1,int param_2);
void G_AddClassSpecificTools_part_3(int param_1);
void G_BodyDP(uint32_t *param_1);
void G_DropLimboHealth(int param_1);
uint32_t G_AddClassSpecificTools(uint32_t param_1);
int G_CountTeamMedics(int param_1,int param_2);
void G_SetDefaultLevel(int param_1);
int G_ComputeMaxLives(int param_1,int param_2);
void G_ShortcutSanitize_part_7(uint32_t param_1);
uint32_t G_CensorText(char *param_1,char *param_2);
void G_CensorPenalize(uint32_t *param_1);
void G_PlayDead(int param_1);
void G_TeamDamageStats(int param_1);
uint32_t G_SendScore_Add(uint32_t param_1,int param_2,char *param_3,uint param_4);
void G_SendScore(int param_1);
bool G_SendKD_Add(uint32_t param_1,int param_2,char *param_3,uint param_4);
void G_SendKD(int param_1);
uint32_t G_MatchOnePlayer(int *param_1,char *param_2,uint param_3);
void G_PlaySound_Cmd(void);
void G_PrivateMessage(uint8_t *param_1);
void G_DropItems(uint32_t *param_1);
uint G_ClassCount(int param_1,int param_2);
uint32_t G_IsClassDisabled(int param_1,int param_2,int param_3);
void G_TeamCountPlayers(void);
uint G_TeamCount(int param_1,int param_2);
void G_EntitySound(uint32_t *param_1,uint32_t param_2,uint32_t param_3);
void G_EntitySoundNoCut(uint32_t *param_1,uint32_t param_2,uint32_t param_3);
uint8_t * G_ShortcutSanitize(char *param_1);
uint8_t * G_Shortcuts(int param_1,uint32_t param_2);
void G_HQSay(int param_1,uint32_t param_2,uint32_t param_3,uint32_t param_4);
void G_Say(int param_1,int param_2,uint param_3,uint32_t param_4);
void G_VoiceTo(int param_1,int param_2,int param_3,uint32_t param_4,int param_5,float param_6);
void G_Voice(int param_1,int param_2,uint param_3,uint32_t param_4,char *param_5,int param_6);
void G_SendVoiceChat(int param_1,uint32_t param_2);
bool G_FindFreeComplainIP(int param_1,uint *param_2);
bool G_TankIsOccupied(int param_1);
uint32_t G_TankIsMountable(int param_1,int param_2,int param_3);
uint32_t G_UniformSteal_2(int param_1,int param_2);
uint32_t G_UniformSteal(int param_1,int param_2);
void G_ClassSteal_RemoveTools(int param_1);
uint32_t G_ClassSteal(int param_1,int param_2);
uint32_t G_PushPlayer(int param_1,int param_2);
uint32_t G_DragCorpse(int param_1,int param_2);
void G_LeaveTank(uint32_t *param_1,int param_2,int param_3);
void G_UpdateSpawnCounts(void);
void G_MakeReady(int param_1);
void G_MakeUnready(int param_1);
void G_CalcClientAccuracies(void);
void G_commands_cmd(int param_1);
void G_players_cmd(int param_1);
void G_scores_cmd(uint32_t param_1);
void G_statsall_cmd(int param_1);
void G_cheaters_cmd(uint32_t param_1);
void G_say_teamnl_cmd(int param_1);
void G_specinvite_cmd(int param_1,int param_2);
void G_speclock_cmd(int param_1,int param_2,int param_3);
void G_lock_cmd(int param_1,int param_2,int param_3);
void G_pause_cmd(int param_1,int param_2,int param_3);
void G_ready_cmd(int param_1,int param_2,int param_3);
void G_teamready_cmd(int param_1,int param_2);
uint32_t G_commandHelp(int param_1,uint32_t param_2,int param_3);
uint32_t G_commandCheck(uint32_t param_1,uint32_t param_2,int param_3);
uint32_t G_cmdDebounce(int param_1,uint32_t param_2);
void G_noTeamControls(int param_1);
void G_UpdateKillingSpree(int param_1,int param_2,int param_3);
void G_UpdateKillingSpreeForMapEnd(int param_1);
int G_BuildHead(uint32_t *param_1,int param_2);
int G_BuildLeg(int param_1);
void G_RailTrail(uint32_t param_1,uint32_t *param_2,float *param_3);
void G_RailBox(float *param_1,float *param_2,float *param_3,float *param_4,int param_5);
void G_AdjustedDamageVec(int param_1,float *param_2,float *param_3);
void G_configSet(uint param_1,int param_2);
uint32_t * G_FindFreeFireteam(void);
uint32_t G_GetFireteamTeam(int param_1);
int G_CountTeamFireteams(int param_1);
void G_UpdateFireteamConfigString(int *param_1);
uint32_t G_IsOnFireteam(int param_1,uint32_t *param_2);
uint32_t G_IsFireteamLeader(uint param_1,uint32_t *param_2);
uint32_t G_FindFreeFireteamIdent(int param_1);
void G_RegisterFireteam(uint param_1);
void G_AddClientToFireteam(uint param_1,uint param_2);
void G_RemoveClientFromFireteams(int param_1,int param_2,int param_3);
void G_InviteToFireTeam(uint param_1,uint param_2);
void G_DestroyFireteam(uint param_1);
void G_ApplyToFireTeam(uint param_1,int param_2);
void G_ProposeFireTeamPlayer(uint param_1,uint param_2);
void G_FireteamNumberForString(char *param_1,int param_2);
uint32_t * G_FindFreePublicFireteam(int param_1);
void G_SpawnItem(int param_1,int param_2);
void G_FlushItem(uint32_t *param_1,int param_2);
uint32_t G_ItemStick(int param_1,int param_2,float *param_3);
void G_BounceItem(int param_1,int param_2);
void G_RunItemProp(uint8_t *param_1,uint32_t *param_2);
void G_TestWater(int param_1,uint32_t *param_2);
uint32_t G_CheckForCabinetResupply(int param_1,int *param_2);
void G_RunItem(uint32_t *param_1);
uint G_SortMapsByzOrder(int *param_1,int *param_2);
uint32_t G_SnapshotCallback(int param_1,uint32_t param_2);
void G_Printf(char *param_1);
void G_DPrintf(char *param_1);
void G_Error(char *param_1);
void G_CheckForCursorHints(int param_1);
void G_SetTargetName(int param_1,char *param_2);
void G_FindTeams(void);
void G_RegisterCvars(void);
void G_UpdateInfo(void);
uint32_t G_ConfigParse_constprop_11(uint32_t param_1);
uint32_t G_LoadConfig(char *param_1,int param_2);
void G_mapvoteinfo_write(void);
void G_mapvoteinfo_read(void);
void G_GetRealTime(void);
void G_LogPrintf(char *param_1);
void G_ShutdownGame(uint32_t param_1);
void G_UpdateCvars(void);
void G_wipeCvars(void);
void G_CrashLogPrintf(char *param_1);
void G_RunThink(int *param_1);
uint32_t G_PositionEntityOnTag(int param_1,int param_2,uint32_t param_3);
uint32_t G_missileCamera(int param_1);
void G_DrawEntBBox(uint32_t *param_1);
void G_RunEntity_part_9(int *param_1,int param_2);
void G_TagLinkEntity(int param_1);
void G_RunEntity(int *param_1,int param_2);
void G_InitGame(uint32_t param_1,uint param_2,uint32_t param_3);
void G_RunFrame_part_10(int param_1);
uint32_t G_RunFrame(uint32_t param_1);
uint8_t * G_GetDateAndTime(void);
void G_delayPrint(int param_1);
void G_initMatch(void);
void G_loadMatchGame(void);
void G_printFull(uint32_t param_1,int param_2);
void G_globalSound(uint32_t param_1);
void G_spawnPrintf(int param_1,uint32_t param_2,uint32_t param_3);
void G_addStats(int param_1,int param_2,int param_3,int param_4);
void G_addStatsHeadShot(int param_1,int param_2);
uint32_t G_createStats(int param_1);
void G_deleteStats(int param_1);
void G_parseStats(char *param_1);
void G_printMatchInfo(int param_1);
void G_matchInfoDump(int param_1);
uint32_t G_checkServerToggle(uint8_t *param_1);
void G_statsPrint(int param_1,int param_2);
void G_resetRoundState(void);
void G_resetModeState(void);
uint8_t * G_Alloc(int param_1);
void G_InitMemory(void);
void G_InitTempTraceIgnoreEnts(void);
void G_ResetTempTraceIgnoreEnts(void);
void G_TempTraceIgnoreEntity(int param_1);
uint8_t * G_TempTraceIgnorePlayersAndBodies(void);
void G_MakePip(int param_1);
uint32_t G_FlingClient(int param_1,int param_2);
char G_GetEnemyPosition(int param_1,int param_2);
bool G_ConstructionBegun(int param_1);
bool G_ConstructionIsFullyBuilt(int param_1);
bool G_ConstructionIsPartlyBuilt(int param_1);
bool G_ConstructionIsDestroyable(int param_1);
int G_ConstructionForTeam(int param_1,int param_2);
int G_IsConstructible(int param_1,int param_2);
void G_BounceMissile(int param_1,int param_2);
void G_BurnTarget(int param_1,int *param_2,int param_3);
void G_FadeItems(int param_1,int param_2);
uint8_t * G_FindMissileBis(int param_1,int param_2);
void G_BlockThink(int param_1);
uint8_t * G_TestEntityPosition(uint32_t *param_1);
void G_TestEntityDropToFloor(uint32_t *param_1,float param_2);
void G_TestEntityMoveTowardsPos(uint32_t *param_1,uint32_t param_2);
bool G_TryPushingEntity(uint32_t *param_1,int *param_2,float *param_3,int param_4);
uint32_t G_MoverPush(int *param_1,float *param_2,float *param_3,uint32_t *param_4);
void G_MoverTeam(int param_1);
void G_RunMover(int param_1);
void G_TryDoor(int param_1,uint32_t param_2,uint32_t param_3);
void G_Activate(int param_1,uint32_t param_2);
uint32_t * G_AllocDebrisChunk(void);
void G_LinkDamageParents(void);
void G_LinkDebris(void);
void G_refPrintf_constprop_4(uint32_t param_1,char *param_2);
void G_refHelp_cmd(int param_1);
void G_refSpeclockTeams_cmd(uint32_t param_1,int param_2);
void G_refPrintf(int param_1,char *param_2);
void G_refAllReady_cmd(uint32_t param_1);
void G_refLockTeams_cmd(uint32_t param_1,int param_2);
void G_refPause_cmd(int param_1,int param_2);
void G_refPlayerPut_cmd(uint32_t param_1,int param_2);
void G_refRemove_cmd(uint32_t param_1);
void G_refWarmup_cmd(uint32_t param_1);
uint32_t G_refClientnumForName_part_1(uint32_t param_1,char *param_2);
uint32_t G_refClientnumForName(uint32_t param_1,char *param_2);
uint32_t G_refCommandCheck(int param_1,byte *param_2);
void G_ref_cmd(int param_1);
void G_ModifyTOI(int param_1);
void G_WriteClientSessionData(int param_1,int param_2);
void G_ClientSwap(int param_1);
void G_CalcRank(int param_1);
void G_ReadSessionData(int param_1);
void G_InitSessionData(int param_1,uint32_t param_2);
void G_InitWorldSession(void);
void G_WriteSessionData(uint32_t param_1);
int G_SpawnIntExt(char *param_1,char *param_2,long *param_3,uint32_t param_4,uint32_t param_5);
uint32_t G_CallSpawn(int param_1);
int G_NewString(char *param_1);
void G_ParseField(uint32_t param_1,char *param_2,int param_3);
int G_SpawnGEntityFromSpawnVars(void);
void G_AddSpawnVarToken(char *param_1);
uint32_t G_ParseSpawnVars(void);
void G_SpawnEntitiesFromString(void);
void G_ResetXP_part_1(int param_1);
void G_UpgradeSkill(int param_1,int param_2);
void G_LogTeamKill(int param_1,uint32_t param_2);
void G_LogRegionHit(int param_1,int param_2);
void G_PrintAccuracyLog(int param_1);
void G_SetPlayerScore(int param_1);
void G_SetPlayerSkill(int param_1,int param_2);
uint32_t G_LoseSkillPointsExt(int param_1,int param_2,float param_3);
void G_LoseSkillPoints(int param_1,int param_2,float param_3);
void G_XPDecay(int param_1,int param_2,int param_3);
void G_ResetXP(int param_1);
void G_AddSkillPoints(int param_1,int param_2,float param_3);
void G_LoseKillSkillPoints(int param_1,uint32_t param_2);
void G_DebugOpenSkillLog(void);
void G_DebugCloseSkillLog(void);
void G_DebugAddSkillLevel(int param_1,int param_2);
void G_DebugAddSkillPoints(int param_1,int param_2,float param_3,uint32_t param_4);
void G_AddKillSkillPoints(int param_1,int param_2,uint32_t param_3,int param_4,int param_5);
void G_AddKillSkillPointsForDestruction(int param_1,uint32_t param_2,int param_3);
void G_ReassignSkillLevel(uint32_t param_1);
bool G_HasFlakJacket(int param_1);
void G_Is_SV_Running(void);
bool G_FilterPacket(uint *param_1,char *param_2);
bool G_FilterMaxLivesIPPacket(char *param_1);
uint32_t G_FilterMaxLivesPacket(uint32_t param_1);
int G_GetPlayerByNum(int param_1);
int G_GetPlayerByName(uint32_t param_1);
void G_ClearXP(void);
void G_UpdateSvCvars(void);
uint32_t G_CvarUpdateSafe(int param_1,int param_2);
void G_teamReset(int param_1,int param_2);
void G_swapTeams(void);
void G_shuffleTeams(void);
bool G_checkReady(void);
uint32_t G_readyMatchState(void);
void G_verifyMatchState(int param_1);
uint32_t G_teamJoinCheck(uint param_1,int param_2);
void G_updateSpecLock(uint param_1,int param_2);
void G_swapTeamLocks(void);
void G_removeSpecInvite(uint param_1);
bool G_blockoutTeam(int param_1,uint param_2);
bool G_allowFollow(int param_1,uint param_2);
uint32_t G_desiredFollow(int param_1,uint param_2);
void G_PushMapEntityToBuffer(uint32_t param_1,uint32_t param_2,float *param_3);
void G_InitMapEntityData(void *param_1);
uint32_t G_FreeMapEntityData(int param_1,int param_2);
void G_AllocMapEntityData(int param_1);
int G_FindMapEntityData(int param_1,int param_2);
int G_FindMapEntityDataSingleClient(int param_1,int param_2,int param_3,int param_4);
void G_SetupFrustum(int param_1);
void G_SetupFrustum_ForBinoculars(int param_1);
bool G_VisibleFromBinoculars(uint32_t *param_1,int *param_2,float *param_3);
void G_ResetTeamMapData(void);
void G_UpdateTeamMapData_Construct(int param_1);
void G_UpdateTeamMapData_Tank(int param_1);
void G_UpdateTeamMapData_Destruct(int param_1);
void G_UpdateTeamMapData_Player(int param_1,int param_2,int param_3);
void G_UpdateTeamMapData_CommandmapMarker(int param_1);
void G_SendSpectatorMapEntityInfo(int param_1);
void G_SendMapEntityInfo(int param_1);
void G_UpdateTeamMapData(void);
void G_ConvertQtime(int *param_1);
void G_GetCurrentTime(void);
bool G_IsAllowedHeal(int param_1);
void G_SetConfigStringValue(uint32_t param_1,uint32_t param_2,uint32_t param_3);
bool G_LoadCampaignsFromFile(uint32_t param_1);
int G_FindConfigstringIndex_part_0(char *param_1,int param_2,int param_3,int param_4);
int G_FindConfigstringIndex_part_0_constprop_4(char *param_1);
int G_FindConfigstringIndex_part_0_constprop_5(char *param_1);
void G_InitRemappedShaders(void);
G_FindConfigstringIndex(char *param_1,uint32_t param_2,uint32_t param_3,uint32_t param_4);
void G_RemoveConfigstringIndex(char *param_1,int param_2,int param_3);
void G_ModelIndex(uint32_t param_1);
int G_SoundIndex(uint32_t param_1);
void G_SkinIndex(uint32_t param_1);
void G_ShaderIndex(uint32_t param_1);
uint32_t G_StringIndex(char *param_1);
void G_TeamCommand(int param_1,uint32_t param_2);
uint8_t * G_Find(int param_1,int param_2,uint32_t param_3);
uint8_t * G_FindByTargetnameFast(int param_1,uint32_t param_2,int param_3);
int G_PickTarget(int param_1);
bool G_AllowTeamsAllowed(int param_1,int param_2);
void G_UseEntity(int param_1,uint32_t param_2,int param_3);
void G_UseTargets(uint8_t *param_1,int param_2);
void G_SetMovedir(uint32_t *param_1,uint32_t *param_2);
void G_InitGentity(int *param_1);
int G_GentitiesAvailable(void);
int * G_Spawn(void);
int G_EntitiesFree(void);
void G_FreeEntity(uint32_t *param_1);
int G_TempEntity(float *param_1,int param_2);
int G_PopupMessage(uint32_t param_1);
void G_AddPredictableEvent(int param_1,uint32_t param_2,uint32_t param_3);
void G_AddEvent(uint32_t *param_1,int param_2,uint32_t param_3);
void G_Sound(int param_1,uint32_t param_2);
void G_ClientSound(int param_1,uint32_t param_2);
void G_AnimScriptSound(uint32_t param_1,uint32_t param_2,int param_3);
void G_SetOrigin(int param_1,uint32_t *param_2);
void G_SetAngle(int param_1,uint32_t *param_2);
void G_ProcessTagConnect(uint32_t *param_1,int param_2);
void G_SetEntState(uint32_t *param_1,int param_2);
uint32_t G_MapIsValidCampaignStartMap(void);
void G_ParseCampaigns(void);
int G_GetTeamFromEntity(uint8_t *param_1);
uint32_t G_Nextmap_v(int param_1,int param_2,int param_3,uint32_t param_4,int param_5);
uint32_t G_StartMatch_v(uint32_t param_1,int param_2,int param_3,uint32_t param_4,int param_5);
uint32_t G_Poll_v(int param_1,uint32_t param_2,int param_3,uint32_t param_4);
uint32_t G_NextCampaign_v_part_0(void);
int G_NextCampaign_v(int param_1,uint32_t param_2,int param_3);
uint32_t G_RestartCampaign_v_part_1(void);
int G_RestartCampaign_v(int param_1,uint32_t param_2,int param_3);
uint32_t G_Surrender_v_part_2(void);
uint32_t G_Surrender_v(int param_1,uint32_t param_2,int param_3,uint32_t param_4);
uint32_t G_Comp_v(int param_1,int param_2,int param_3,uint32_t param_4,int param_5);
uint32_t G_Pub_v(int param_1,int param_2,int param_3,uint32_t param_4,int param_5);
uint32_t G_ShuffleTeams_v(int param_1,int param_2,int param_3,uint32_t param_4,int param_5);
G_ShuffleTeams_NoRestart_v(int param_1,int param_2,int param_3,uint32_t param_4,int param_5);
uint32_t G_SwapTeams_v(int param_1,int param_2,int param_3,uint32_t param_4,int param_5);
uint32_t G_SwapTeamsRestart_v(int param_1,int param_2,int param_3,uint32_t param_4,int param_5);
uint32_t G_Campaign_v(int param_1,int param_2,int param_3,uint32_t param_4,int param_5);
uint32_t G_Map_v(int param_1,int param_2,int param_3,uint32_t param_4,int param_5);
int G_voteCmdCheck(uint32_t param_1,uint32_t param_2,uint32_t param_3,uint32_t param_4);
void G_customVoteLoad(void);
void G_voteHelp(int param_1,int param_2);
void G_voteFlags(void);
uint32_t G_voteDescription(int param_1,int param_2,int param_3);
int G_MapRestart_v(int param_1,uint32_t param_2,int param_3,uint32_t param_4,uint32_t param_5);
int G_MatchReset_v(int param_1,uint32_t param_2,int param_3,uint32_t param_4,uint32_t param_5);
G_Timelimit_v(int param_1,uint32_t param_2,int param_3,char *param_4,uint32_t param_5);
uint32_t G_Gametype_v(int param_1,uint32_t param_2,int param_3,char *param_4,uint32_t param_5);
G_Warmupfire_v(int param_1,uint32_t param_2,int param_3,char *param_4,uint32_t param_5);
uint32_t G_AntiLag_v(int param_1,int param_2,int param_3,char *param_4,uint32_t param_5);
uint32_t G_FriendlyFire_v(int param_1,int param_2,int param_3,char *param_4,uint32_t param_5);
uint32_t G_BalancedTeams_v(int param_1,int param_2,int param_3,char *param_4,uint32_t param_5);
void G_voteDisableMessage(uint32_t param_1,uint32_t param_2);
void G_playersMessage(uint32_t param_1);
void G_voteCurrentSetting(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void G_voteSetOnOff(uint32_t param_1,uint32_t param_2);
void G_voteSetValue(uint32_t param_1,uint32_t param_2);
void G_voteSetVoteString(uint32_t param_1);
void G_GametypeList(uint32_t param_1);
void G_voteSetBitFlag(uint32_t param_1,int param_2,uint32_t param_3,uint param_4);
void G_WarmupDamageTypeList(uint32_t param_1);
void G_IntermissionMapVote(int param_1);
void G_IntermissionMapList(int param_1);
void G_IntermissionVoteTally(int param_1);
bool G_AvailableArty(int param_1);
void G_AddArtyToCounters(int param_1);
void G_GlobalClientEvent(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void G_BurnMeGood(uint32_t *param_1,int param_2,int param_3);
uint32_t G_PlayerCanBeSeenByOthers(uint8_t *param_1);
void G_createClusterNade(int param_1,int param_2,int param_3);
uint8_t * G_GetDateAndTimeFileName(void);
uint8_t * G_SHA1(char *param_1);

#endif

