# Name artifacts by the actual target, never by the development host's wish.
function(nitmod_artifact_name base output_name output_suffix)
    if(EMSCRIPTEN)
        set(name "${base}.mp.wasm32")
        set(suffix ".so")
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
        if(CMAKE_SIZEOF_VOID_P EQUAL 8)
            # No Windows x64 engine filename is specified by the original
            # Nitmod package; keep host-test outputs visibly separate.
            set(name "${base}.host.windows64")
        else()
            set(name "${base}_mp_x86")
        endif()
        set(suffix ".dll")
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        set(name "${base}")
        set(suffix "_mac")
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        if(NITMOD_ARCH STREQUAL "i386" AND NOT CMAKE_SIZEOF_VOID_P EQUAL 4)
            message(FATAL_ERROR "i386 module name requires a 32-bit toolchain; use the Linux-i386 build driver")
        endif()
        set(name "${base}.mp.${NITMOD_ARCH}")
        set(suffix ".so")
    else()
        set(name "${base}.host.${CMAKE_SYSTEM_NAME}")
        set(suffix "${CMAKE_SHARED_MODULE_SUFFIX}")
    endif()
    set(${output_name} "${name}" PARENT_SCOPE)
    set(${output_suffix} "${suffix}" PARENT_SCOPE)
endfunction()
