# Configure-time policy, separate from the compiler probe for host tests.
function(nitmod_validate_linux_i386)
    if(NOT NITMOD_REQUIRE_LINUX_I386)
        return()
    endif()
    if(EMSCRIPTEN OR NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
        message(FATAL_ERROR "Strict i386 release build requires native Linux, not a host or WASM build")
    endif()
    if(NOT NITMOD_ARCH STREQUAL "i386")
        message(FATAL_ERROR "Strict i386 release build requires NITMOD_ARCH=i386")
    endif()
    if(NOT CMAKE_SIZEOF_VOID_P EQUAL 4)
        message(FATAL_ERROR "Strict i386 release build requires 32-bit pointers; check compiler and -m32 flags")
    endif()
endfunction()
