#ifndef ET_UI_UI_MISC_H
#define ET_UI_UI_MISC_H

/**
 * @file ui_ui_misc.h
 * @brief ui_misc
 *
 * Recovered from Enemy Territory ui.mp.i386.so
 * Original decompilation: Ghidra
 */

#include "ui_types.h"
#include "ui_globals.h"

void AddPointToBounds(float *param_1,float *param_2,float *param_3);
void AdjustFrom640(float *param_1,float *param_2,float *param_3,float *param_4);
long double AngleDelta(float param_1,float param_2);
long double AngleMod(float param_1);
long double AngleNormalize180(float param_1);
long double AngleNormalize2Pi(float param_1);
long double AngleNormalize360(float param_1);
uint AngleNormalizeInt(uint param_1);
void AngleSubtract(float param_1,float param_2);
void AngleVectors(float *param_1,float *param_2,float *param_3,float *param_4);
void AnglesSubtract(float *param_1,float *param_2,float *param_3);
void AnglesToAxis(float *param_1,float *param_2);
void AxisClear(uint32_t *param_1);
void AxisCopy(uint32_t *param_1,uint32_t *param_2);
void AxisToAngles(int param_1,float *param_2);
uint8_t * BindingFromName(uint32_t param_1);
int BindingIDFromName(uint32_t param_1);
void ByteToDir(uint param_1,uint32_t *param_2);
uint COM_BitCheck(int param_1,uint param_2);
void COM_BitClear(int param_1,uint param_2);
void COM_BitSet(int param_1,uint param_2);
int COM_Compress(char *param_1);
void COM_FixPath(char *param_1);
void COM_MatchToken(uint32_t param_1,char *param_2);
char * COM_SkipPath(char *param_1);
void COM_StripExtension(char *param_1,char *param_2);
void COM_StripFilename(char *param_1,char *param_2);
uint8_t ClampChar(int param_1);
int ClampShort(int param_1);
void ClearBounds(uint32_t *param_1,uint32_t *param_2);
void Com_Clamp(void);
void Com_DPrintf(char *param_1);
void Com_Error(uint32_t param_1,char *param_2);
void Com_Printf(char *param_1);
void Com_sprintf(char *param_1,size_t param_2,char *param_3);
void ConcatArgs(int param_1);
void Controls_GetConfig(void);
void Controls_SetConfig(int param_1);
void Controls_SetDefaults(int param_1);
void CrossProduct(float *param_1,float *param_2,float *param_3);
void Cui_WideRect(float *param_1);
long double Cui_WideX(float param_1);
long double Cui_WideXoffset(void);
int DirToByte(float *param_1);
long double Distance(float *param_1,float *param_2);
long double DistanceFromLineSquared(float *param_1,float *param_2,float *param_3);
long double DistanceFromVectorSquared(float *param_1,float *param_2,float *param_3);
long double DistanceSquared(float *param_1,float *param_2);
void Fade(uint *param_1,float *param_2,float param_3,int *param_4,int param_5,int param_6, float param_7);
uint32_t FileExists(uint32_t param_1);
void GetPerpendicularViewVector(float *param_1,float *param_2,float *param_3,float *param_4);
uint32_t Info_NextPair(uint32_t *param_1,char *param_2,char *param_3);
void Info_RemoveKey(char *param_1,char *param_2);
void Info_RemoveKey_Big(char *param_1,char *param_2);
void Info_RemoveKey_Big_part_1(char *param_1,char *param_2);
void Info_RemoveKey_part_0(char *param_1,char *param_2);
void Info_SetValueForKey(char *param_1,char *param_2,char *param_3);
void Info_SetValueForKey_Big(char *param_1,char *param_2,char *param_3);
bool Info_Validate(char *param_1);
char * Info_ValueForKey(char *param_1,char *param_2);
bool IsVisible(uint param_1);
void KeywordHash_Add(int param_1,uint32_t *param_2);
uint32_t * KeywordHash_Find(int param_1,char *param_2);
uint KeywordHash_Key(char *param_1);
long double LerpAngle(float param_1,float param_2,float param_3);
void LerpPosition(float *param_1,float *param_2,float param_3,float *param_4);
void MakeNormalVectors(float *param_1,float *param_2,float *param_3);
void MatrixMultiply(float *param_1,float *param_2,float *param_3);
void Menus_Activate(int param_1);
uint32_t * Menus_ActivateByName(uint32_t param_1,int param_2);
uint32_t Menus_AnyFullScreenVisible(void);
bool Menus_CaptureFuncActive(void);
void Menus_CloseAll(void);
void Menus_CloseByName(uint32_t param_1);
uint32_t * Menus_FindByName(uint32_t param_1);
void Menus_HandleOOBClick(int param_1,uint32_t param_2,int param_3);
void Menus_OpenByName(uint32_t param_1);
void Menus_ShowByName(uint32_t param_1);
uint32_t Nit_RemoveWordInString(char *param_1,char *param_2);
void PerpendicularVector(float *param_1,float *param_2);
uint32_t PlaneFromPoints(float *param_1,float *param_2,float *param_3,float *param_4);
bool PointInBounds(float *param_1,float *param_2,float *param_3);
void ProjectPointOnPlane(float *param_1,float *param_2,float *param_3);
void ProjectPointOntoVector(float *param_1,float *param_2,float *param_3,float *param_4);
void ProjectPointOntoVectorBounded(float *param_1,float *param_2,float *param_3,float *param_4);
char * Q_CleanDirName(char *param_1);
void Q_CleanStr(char *param_1);
int Q_PrintStrlen(char *param_1);
uint8_t * Q_StrReplace(uint *param_1,char *param_2,char *param_3);
long double Q_crandom(uint *param_1);
uint Q_fabs(uint param_1);
uint32_t Q_isBadDirChar(char param_1);
bool Q_isalpha(uint param_1);
bool Q_isalphanumeric(uint param_1);
bool Q_isforfilename(uint param_1);
bool Q_islower(int param_1);
bool Q_isnumeric(int param_1);
bool Q_isprint(int param_1);
bool Q_isupper(int param_1);
int Q_log2(int param_1);
void Q_rand(int *param_1);
uint Q_random(uint *param_1);
int Q_rsqrt(int param_1);
void Q_strcat(char *param_1,uint param_2,char *param_3);
int Q_stricmp(char *param_1,char *param_2);
int Q_stricmpn(char *param_1,char *param_2,int param_3);
char * Q_strlwr(char *param_1);
int Q_strncmp(char *param_1,char *param_2,int param_3);
void Q_strncpyz(char *param_1,char *param_2,int param_3);
char * Q_strrchr(char *param_1,char param_2);
char * Q_strupr(char *param_1);
long double RadiusFromBounds(float *param_1,float *param_2);
bool Rect_ContainsPoint(float *param_1,float param_2,float param_3);
void Rect_ToWindowCoords(float *param_1,float *param_2);
void RotateAroundDirection(float *param_1,float param_2);
void RotatePointAroundVector(float *param_1,float *param_2,float *param_3,float param_4);
void RotatePointAroundVertex (float *param_1,float param_2,float param_3,float param_4,float *param_5);
void Script_Abort(uint32_t param_1,uint32_t *param_2);
void Script_CheckAutoUpdate(void);
uint32_t Script_CheckProfile(uint32_t param_1);
void Script_ClearCvar(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_ClearFocus(void);
void Script_Close(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_CloseAll(void);
void Script_CloseAllOtherMenus(int param_1);
void Script_ConditionalHideShow(int param_1,uint32_t param_2,uint32_t param_3);
void Script_ConditionalOpen(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_ConditionalScript(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_CopyCvar(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_Exec(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_ExecNOW(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_ExecWolfConfig(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_FadeIn(int param_1,uint32_t param_2,uint32_t param_3);
void Script_FadeInMenu(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_FadeOut(int param_1,uint32_t param_2,uint32_t param_3);
void Script_FadeOutMenu(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_GetAutoUpdate(void);
void Script_Hide(int param_1,uint32_t param_2,uint32_t param_3);
void Script_Open(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_Orbit(int param_1,uint32_t param_2,uint32_t param_3);
void Script_Play(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_SetAsset(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_SetBackground(int param_1,uint32_t param_2,uint32_t param_3);
void Script_SetCvar(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_SetEditFocus(int param_1,uint32_t param_2,uint32_t param_3);
void Script_SetFocus(int param_1,uint32_t param_2,uint32_t param_3);
void Script_SetMenuFocus(int param_1,uint32_t param_2,uint32_t param_3);
void Script_SetPlayerHead(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_SetPlayerModel(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_Show(int param_1,uint32_t param_2,uint32_t param_3);
void Script_ToggleCvarBit(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_Transition(int param_1,uint32_t param_2,uint32_t param_3);
uint32_t Script_WriteProfile(uint32_t param_1);
void Script_playLooped(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Scroll_ListBox_AutoFunc(int *param_1);
void Scroll_ListBox_ThumbFunc(int *param_1);
void Scroll_Slider_ThumbFunc(int param_1);
void SetPlaneSignbits(float *param_1);
uint32_t SkillForClass(int param_1);
void SkipBracedSection(int *param_1);
void SkipBracedSection_Depth(int *param_1,int param_2);
void SkipRestOfLine(uint32_t *param_1);
char * String_Alloc(char *param_1);
void String_Report(void);
void ToWindowCoords(float *param_1,float *param_2,float *param_3);
void Tooltip_ComputePosition(int param_1);
void UI_AdjustFrom640(float *param_1,float *param_2,float *param_3,float *param_4);
uint8_t * UI_Alloc(int param_1);
uint8_t * UI_Argv(uint32_t param_1);
void UI_Campaign_f(void);
bool UI_CheckExecKey(int param_1);
void UI_ClampCvar(void);
uint32_t UI_ConsoleCommand(int param_1);
bool UI_CursorInRect(int param_1,int param_2,int param_3,int param_4);
uint8_t * UI_Cvar_VariableString(uint32_t param_1);
void UI_FillRect(float param_1,float param_2,float param_3,float param_4,uint32_t param_5);
void UI_ListCampaigns_f(void);
void UI_Load(void);
void UI_LoadArenas(void);
void UI_LoadNonIngame(void);
uint32_t UI_OutOfMemory(void);
void UI_PrintTime(uint32_t param_1,uint32_t param_2,int param_3);
void UI_RunMenuScript(void);
void UI_ServersSort(int param_1,int param_2);
void UI_SortArenas(uint32_t *param_1,uint32_t *param_2);
void UI_SortCampaigns(int param_1,int param_2);
void UI_StartServerRefresh(void);
void UI_Update(uint32_t param_1);
void UI_UpdateCvars(void);
void UI_UpdateScreen(void);
void Vector4Scale(float *param_1,float param_2,float *param_3);
bool VectorCompare(float *param_1,float *param_2);
long double VectorDistance(float *param_1,float *param_2);
long double VectorDistanceSquared(float *param_1,float *param_2);
void VectorInverse(float *param_1);
long double VectorLength(float *param_1);
long double VectorLengthSquared(float *param_1);
void VectorNormalize(float *param_1);
long double VectorNormalize2(float *param_1,float *param_2);
void VectorNormalizeFast(float *param_1);
void VectorRotate(float *param_1,float *param_2,float *param_3);
void WM_setItemPic(uint32_t param_1,uint32_t param_2);
void WM_setVisibility(uint32_t param_1,int param_2);
long double _DotProduct(float *param_1,float *param_2);
uint32_t _UI_GetActiveMenu(void);
void _UI_IsFullscreen(void);
void _UI_KeyEvent(uint32_t param_1,uint32_t param_2);
void _UI_MouseEvent(int param_1,int param_2);
void _UI_SetActiveMenu(uint32_t param_1);
void _VectorAdd(float *param_1,float *param_2,float *param_3);
void _VectorCopy(uint32_t *param_1,uint32_t *param_2);
void _VectorMA(float *param_1,float param_2,float *param_3,float *param_4);
void _VectorScale(float *param_1,float param_2,float *param_3);
void _VectorSubtract(float *param_1,float *param_2,float *param_3);
__int32_t ** __ctype_tolower_loc(void);
__int32_t ** __ctype_toupper_loc(void);
void __cxa_finalize(void);
void __gmon_start__(void);
void __x86_get_pc_thunk_bx(void);
void __x86_get_pc_thunk_cx(void);
double atan2(double __y,double __x);
void decode64(int param_1);
uint32_t encode64(byte *param_1,char *param_2,int param_3);
byte * escape_string(byte *param_1);
float floorf(float __x);
void frame_dummy(void);
void * memmove(void *__dest,void *__src,size_t __n);
uint32_t need_escape(byte *param_1);
void nitrox_AddPredictableDamage (uint32_t param_1,uint32_t param_2,uint32_t param_3,int param_4);
void nitrox_ClampFloat(float *param_1,float param_2,float param_3);
void nitrox_ClampInt(int *param_1,float param_2,float param_3);
void nitrox_stripLeadingSpaces(char *param_1);
int rand(void);
void sincos(double __x,double *__sinx,double *__cosx);
float sqrtf(float __x);
char * stpcpy(char *__dest,char *__src);
char * strchr(char *__s,int __c);
char * strstr(char *__haystack,char *__needle);
char * strtok(char *__s,char *__delim);
void tv(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void unescape_string(char *param_1);
void va(char *param_1);
void vectoangles(float *param_1,float *param_2);
long double vectoyaw(float *param_1);
uint vmMain(uint32_t param_1,int param_2,int param_3);
int vsnprintf(char *__s,size_t __maxlen,char *__format,__gnuc_va_list __arg);

#endif /* ET_UI_UI_MISC_H */
