#ifndef CGAME_CLIENT_H
#define CGAME_CLIENT_H

/* Miscellaneous client-game logic */

#include "nitmod_types.h"
#include "nitmod_globals.h"

uint32_t CG_RW_ParseViewType(uint32_t param_1,char *param_2,int param_3);
void CG_ContinueWeaponAnim(uint param_1);
void CG_GenerateTracemap(void);
int CG_EffectGust(void);
uint32_t CG_SnowParticleGenerate(float *param_1,float *param_2);
uint32_t CG_RainParticleGenerate(float *param_1,float *param_2,float param_3);
uint32_t CG_SnowParticleCheckVisible(float *param_1);
uint32_t CG_RainParticleCheckVisible(float *param_1);
void CG_SnowParticleRender(float *param_1);
void CG_RainParticleRender(float *param_1);
uint32_t CG_AtmosphericKludge(void);
void CG_EffectParse(uint32_t param_1);
uint32_t CG_RegisterCharacter(uint32_t param_1,int param_2);
int CG_CharacterForClientinfo(int param_1,int param_2);
void CG_CharacterForPlayerstate(int param_1);
void CG_RegisterPlayerClasses(void);
uint32_t CG_CommandCentreSpawnPointClick_part_3(void);
void CG_TransformToCommandMapCoord(float *param_1,float *param_2);
int CG_CurLayerForZ(int param_1);
void CG_TransformAutomapEntity(void);
bool CG_DisguiseMapCheck(int param_1);
uint32_t * CG_ScanForCommandCentreEntity(void);
uint32_t CG_CommandCentreLayersClick(void);
uint32_t CG_CommandCentreSpawnPointClick(void);
void CG_CommandCentreClick(int param_1);
void CG_CommandMap_SetHighlightText(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void CG_CommandMap_DrawHighlightText(void);
void CG_ToggleAutomap_f(void);
void CG_ResetMaxSpeed_f(void);
void CG_QuickMessage_f(void);
void CG_dumpStats_f(void);
void CG_ForceTapOut_f(void);
void CG_currentTime_f(void);
void CG_Viewpos_f(void);
void CG_autoRecord_f(void);
void CG_SayPlayerClass_f(void);
void CG_keyOn_f(void);
void CG_ResetTimer_f(void);
void CG_TimerSet_f(void);
void CG_SetWeaponCrosshair_f(void);
void CG_CPM_f(void);
void CG_UndoSpeaker_f(void);
void CG_ModifySpeaker_f(void);
void CG_AutomapZoomOut_f(void);
void CG_AutomapZoomIn_f(void);
void CG_SelectBuddy_f(void);
void CG_FTSayPlayerClass_f(void);
void CG_MessageSend_f(void);
void CG_StatsUp_f(void);
void CG_topshotsUp_f(void);
void CG_ScoresUp_f(void);
void CG_AutomapExpandDown_f(void);
void CG_AutomapExpandUp_f(void);
void CG_keyOff_f(void);
void CG_ClassMenu_f(void);
void CG_QuickFireteamAdmin_f(void);
void CG_topshotsDown_f(void);
void CG_ScoresDown_f(void);
void CG_StatsDown_f(void);
void CG_autoScreenShot_f(void);
void CG_vstrDown_f(void);
void CG_vstrUp_f(void);
void CG_TeamVoiceChat_f(void);
void CG_VoiceChat_f(void);
void CG_MessageMode_f(void);
void CG_DumpSpeaker_f(void);
void CG_EditSpeakers_f(void);
void CG_QuickFireteams_f(void);
void CG_BuddyVoiceChat_f(void);
void CG_Class_f(void);
void CG_QuickFireteamMessage_f(void);
void CG_wStatsDown_f(void);
void CG_wStatsUp_f(void);
void CG_toggleSpecHelp_f(void);
void CG_parseMapVoteListInfo(void);
void CG_parseMapVoteTally(void);
int CG_SortPlayersByXP(int *param_1,int *param_2);
void CG_TeamDebriefingMapWinner_Draw(void);
void CG_TeamDebriefingMapList_Draw(int param_1);
void CG_MapVoteList_Draw(int param_1);
void CG_TeamDebriefingOutcome_Draw(int param_1);
uint32_t CG_TeamDebriefingMapList_KeyDown(int param_1,int param_2);
uint32_t CG_MapVote_VoteButton_KeyDown(uint32_t param_1,int param_2);
uint32_t CG_MapVote_MultiVoteButton_KeyDown(int param_1,int param_2);
void CG_TeamDebriefingMapShot_Draw(int param_1);
uint32_t CG_MapVoteList_KeyDown(uint32_t param_1,int param_2);
int CG_TeamDebriefing_CalcXP_constprop_18(int param_1,int param_2);
void CG_PanelButtonsRender_Window(int param_1);
void CG_PanelButtonsRender_Button(int param_1);
void CG_MapVote_VoteButton_Draw(int param_1);
void CG_ChatPanel_Setup(void);
void CG_MapVote_SetSelectedMap(int param_1);
void CG_Debrieing_SetSelectedClient(int param_1);
int CG_TeamDebriefing_CalcXP(int param_1,int param_2,int param_3);
void CG_TeamDebriefingTeamSkillXP_Draw(int param_1);
void CG_TeamDebriefingTeamXP_Draw(int param_1);
void CG_PanelButtonsRender_Button_Ext(float *param_1,int param_2);
void CG_MapVote_MultiVoteButton_Draw(int param_1);
char * CG_Debreifing2_WinStringForTeam(int param_1);
void CG_Debreifing2_Maps_Draw(int param_1);
void CG_Debreifing2_MissionTitle_Draw(int param_1);
void CG_Debreifing2_Mission_Draw(int param_1);
void CG_Coronas_part_4(void);
char * CG_PickupItemText(int param_1);
char * CG_PickupItemTextShort(int param_1);
void CG_CenterPrint(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void CG_PrintAnnouncement(uint32_t param_1,uint32_t param_2,uint32_t param_3,int param_4);
void CG_ScanForCrosshairMine(int param_1);
void CG_ScanForCrosshairDynamite(uint32_t *param_1);
void CG_CheckForCursorHints(void);
int CG_CrosshairClientMaxHealth(void);
int CG_CalculateReinfTime_Float(int param_1);
int CG_CalculateReinfTime(int param_1);
void CG_ObjectivePrint(uint32_t param_1,uint32_t param_2);
bool CG_CheckDisguise(void);
int CG_ClassSkillForPosition(int param_1,int param_2);
void CG_StatsDebugAddText(byte *param_1);
void CG_BannerPrint(uint32_t param_1);
void CG_StartShakeCamera(float param_1);
void CG_ShakeCamera(void);
void CG_Coronas(void);
void CG_HorizontalPercentBar(float param_1,float param_2,float param_3,float param_4,float param_5);
void CG_TileClear(void);
uint32_t * CG_FadeColor(int param_1,int param_2);
void CG_ColorForHealth(uint32_t *param_1);
uint CG_BubbleTrail(float *param_1,float *param_2,uint32_t param_3,float param_4);
void CG_SpawnEffect(void);
void CG_LoseACC(int param_1,float *param_2,int param_3,uint32_t param_4,int param_5);
void CG_SparklerSparks(uint32_t *param_1,int param_2);
void CG_ProjectedSpotLight(float *param_1,float *param_2);
void CG_RumbleEfx(float param_1,float param_2);
uint32_t CG_SpawnSmokeSprite(int param_1,float param_2);
void CG_RenderSmokeGrenadeSmoke(int param_1,int param_2);
void CG_Bomb(int param_1);
void CG_Cabinet_part_6(int param_1,int param_2);
void CG_SetEntitySoundPosition(uint32_t *param_1);
void CG_ProcessEntity(int *param_1);
uint32_t CG_Cabinet(uint32_t param_1,uint param_2);
void CG_SetupCabinets(void);
void CG_BotDebugLine(uint32_t *param_1,uint32_t *param_2,uint32_t *param_3);
void CG_StartFootStepSound_isra_0_part_1(uint32_t *param_1,uint32_t param_2);
void CG_MortarImpact_part_2(int param_1,float *param_2);
void CG_PrecacheFXSounds(void);
void CG_Rubble(int param_1,uint32_t param_2,uint32_t param_3,int param_4);
void CG_Explode(int param_1,uint32_t param_2,uint32_t param_3,int param_4);
void CG_Effect(int param_1,float *param_2,float *param_3);
void CG_Shard(int param_1,uint32_t *param_2,float *param_3);
void CG_ShardJunk(uint32_t param_1,uint32_t *param_2,float *param_3);
void CG_Debris(int param_1,uint32_t *param_2,uint32_t *param_3);
void CG_MortarImpact(int param_1,float *param_2,int param_3,int param_4);
void CG_MortarMiss(int param_1,uint32_t *param_2);
uint32_t CG_GetGameSound(int param_1);
uint CG_SortFireTeam(int *param_1,int *param_2);
void CG_SortClientFireteam(void);
uint32_t CG_IsOnSameFireteam(int param_1,int param_2);
uint32_t CG_IsOnFireteam(int param_1);
int CG_IsFireTeamLeader(int param_1);
int CG_SortedFireTeamPlayerForPosition(int param_1);
uint8_t * CG_BuildSelectedFirteamString(void);
uint64_t CG_CountFireteamsByTeam_part_0(int param_1);
uint CG_CountFireteamsByTeam(int param_1);
int CG_CountPlayersSF(void);
int CG_CountPlayersNF(void);
void CG_ClearFlameChunks(void);
void CG_SpawnFlameChunk(int *param_1);
void CG_FreeFlameChunk(int *param_1);
void CG_MergeFlameChunks(int param_1,int *param_2);
void CG_MoveFlameChunk(int param_1);
void CG_UpdateFlamethrowerSounds(void);
void CG_DemoHelpDraw_part_1(void);
void CG_LoadingString(char *param_1);
void CG_ShowHelp_On(int *param_1);
void CG_ShowHelp_Off(int *param_1);
void CG_DemoClick(int param_1,int param_2);
void CG_GameStatsDraw(void);
void CG_TopShotsDraw(void);
void CG_DemoHelpDraw(void);
char * CG_getBindKeyName(uint32_t param_1,char *param_2,uint32_t param_3);
void CG_SpecHelpDraw(void);
bool CG_IsHeavyWeapon(int param_1);
float * CG_GetLocation(float *param_1);
char * CG_GetLocationMsg(float *param_1);
void CG_LoadLocations(void);
void CG_FreeLocalEntity(int *param_1);
uint8_t * CG_FindLocalEntity(int param_1,int param_2);
int * CG_AllocLocalEntity(void);
void CG_BloodTrail(int param_1);
void CG_FragmentBounceMark(int param_1,int param_2);
void CG_FragmentBounceSound(int param_1,int param_2);
void CG_ReflectVelocity(int param_1,int *param_2);
int CG_FeederCount(float param_1);
uint32_t CG_FeederItemImage(void);
void CG_FeederSelection(float param_1,int param_2);
char * CG_FeederItemText(float param_1,int param_2,int param_3,uint32_t *param_4);
long double CG_Cvar_Get(uint32_t param_1);
void CG_RunCinematicFrame(uint32_t param_1);
void CG_StopCinematic(uint32_t param_1);
void CG_RegisterSounds(void);
void CG_setClientFlags_part_0(void);
void CG_Error_constprop_3(void);
void CG_ConfigStringCopy(uint param_1,char *param_2,uint32_t param_3);
void CG_RegisterCvars(void);
void CG_UpdateCvars(void);
void CG_setClientFlags(void);
uint32_t CG_CrosshairPlayer(void);
void CG_Printf(char *param_1);
void CG_Error(char *param_1);
void CG_nameCleanFilename(byte *param_1,byte *param_2,uint param_3);
void CG_generateFilename(void);
int CG_findClientNum(char *param_1);
void CG_printConsoleString(uint32_t param_1);
void CG_LoadObjectiveData(void);
void CG_SetupDlightstyles(void);
int CG_ConfigString(uint param_1);
void CG_StartMusic(void);
void CG_QueueMusic(void);
void CG_LoadHudMenu(void);
void CG_AssetCache(void);
bool CG_execFile(uint32_t param_1);
uint32_t CG_BackupProfile(void);
void CG_RestoreProfile(void);
void CG_CheckExecKey(uint32_t param_1);
uint32_t CG_GetGameModel(int param_1);
void CG_GetRealTime(void);
void CG_WriteToLog(char *param_1);
void CG_FreeMarkPoly(int *param_1);
int * CG_AllocMark(void);
uint32_t CG_DescriptionForCampaign(void);
uint32_t CG_NameForCampaign(void);
uint32_t CG_FindCampaignInFile(uint32_t param_1,uint32_t param_2,int param_3);
uint32_t CG_FindArenaInfo(uint32_t param_1,uint32_t param_2,int param_3);
void CG_LocateCampaign(void);
void CG_LocateArena(void);
long double CG_GetValue(void);
void CG_MouseEvent(int param_1,int param_2);
void CG_EventHandling(int param_1,int param_2);
void CG_KeyEvent(uint32_t param_1,int param_2);
int CG_ClientNumFromName(uint32_t param_1);
void CG_GetTeamColor(uint32_t *param_1);
void CG_ClearParticles(void);
uint32_t CG_NewParticleArea(uint32_t param_1);
void CG_SnowLink(int param_1,int param_2);
void CG_OilSlickRemove(int param_1);
void CG_SwingAngles(float *param_1,int *param_2,float param_3,float param_4,float param_5,float param_6);
bool CG_EntOnFire(int *param_1);
bool CG_IsCrouchingAnim(uint32_t param_1,uint param_2);
void CG_RunLerpFrame(uint32_t param_1,int param_2,uint32_t *param_3,uint param_4,float param_5);
void CG_SetLerpFrameAnimationRate(int param_1,uint32_t param_2,int param_3,uint param_4);
void CG_RunLerpFrameRate_part_2(uint32_t param_1,int *param_2,int param_3,int *param_4,int param_5);
void CG_RunLerpFrameRate(uint32_t param_1,int *param_2,int param_3,int *param_4,int param_5);
void CG_ClearLerpFrameRate(int param_1,uint32_t param_2,uint32_t *param_3,uint param_4);
void CG_SetLerpFrameAnimationRateCorpse(int param_1,int param_2,uint param_3);
void CG_RunLerpFrameRateCorpse(uint32_t param_1,int *param_2,uint param_3,int param_4);
bool CG_WorldCoordToScreenCoordFloat(float *param_1,float *param_2,float *param_3);
void CG_WoundedPlayerFloatName(int *param_1,uint32_t param_2,int param_3);
void CG_AnimPlayerConditions(int param_1,int *param_2);
void CG_ResetPlayerEntity(uint32_t *param_1);
void CG_GetBleedOrigin(uint32_t *param_1,uint32_t *param_2,int param_3);
uint32_t CG_GetTag(int param_1,uint32_t param_2,float *param_3);
uint32_t CG_GetWeaponTag(int param_1,uint32_t param_2,float *param_3);
void CG_SetHudHeadLerpFrameAnimation(int param_1,int param_2,uint param_3);
void CG_ClearHudHeadLerpFrame(int param_1,uint32_t *param_2,uint param_3);
void CG_RunHudHeadLerpFrame(int param_1,uint32_t *param_2,uint param_3,float param_4);
void CG_CheckAmmo(void);
void CG_DamageFeedback(int param_1,int param_2,int param_3);
char * CG_TeamnameForNumber(int param_1);
void CG_Respawn(int param_1);
void CG_CheckPlayerstateEvents(int param_1,int param_2);
void CG_CheckChangedPredictableEvents(int param_1);
void CG_CheckLocalSounds(int param_1,int param_2);
uint8_t * CG_PB_FindFreePolyBuffer(int param_1,int param_2,int param_3);
void CG_PB_ClearPolyBuffers(void);
void CG_PB_RenderPolyBuffers(void);
void CG_UpdatePMLists(void);
uint32_t * CG_FindFreePMItem2(void);
uint32_t * CG_FindFreePMItem(void);
void CG_PMItemBigSound(int *param_1);
uint32_t CG_GetPMItemText(int param_1);
uint32_t CG_GetPMItemIcon(int param_1);
uint CG_SortPlayersByKD(int *param_1,int *param_2);
void CG_printFile_part_0(uint32_t param_1);
void CG_printFile(uint32_t param_1);
void CG_parseWeaponStats_cmd_constprop_5(void);
void CG_UpdateSkills(uint32_t param_1);
int CG_OIDInfoForEntityNum(int param_1);
void CG_SetConfigValues(void);
void CG_ShaderStateChanged(void);
void CG_LoadVoiceChats(void);
uint8_t * CG_VoiceChatListForClient(int param_1);
void CG_VoiceChat(int param_1);
uint32_t * CG_LocalizeServerCommand(char *param_1);
void CG_topshotsParse_cmd(void);
void CG_parseWeaponStatsGS_cmd(void);
void CG_parseWeaponStats_cmd(void *param_1);
void CG_wstatsParse_cmd(void);
void CG_parseBestShotsStats_cmd(int param_1,void *param_2);
void CG_parseTopShotsStats_cmd(int param_1,void *param_2);
void CG_scores_cmd(void);
void CG_dumpStats(void);
void CG_SpeakerEditor_NoiseEditFinish(int param_1);
void CG_SpeakerEditor_TargetnameEditFinish(int param_1);
void CG_SpeakerEditor_Back(int param_1);
void CG_SpeakerInfo_Text(int param_1);
void CG_SpeakerEditor_LocInfo(int param_1);
void CG_SpeakerEditor_RenderEdit(int param_1);
void CG_SpeakerEditor_RenderButton(int param_1);
void CG_SpeakerEditor_RenderDropdown(int param_1);
uint32_t CG_SpeakerEditor_Dropdown_KeyDown(uint32_t param_1,int param_2);
uint32_t CG_SpeakerEditor_Ok_KeyDown(uint32_t param_1,int param_2);
uint32_t CG_SpeakerEditor_Cancel_KeyDown(uint32_t param_1,int param_2);
uint32_t CG_SpeakerEditor_Delete_KeyDown(uint32_t param_1,int param_2);
void CG_SpeakerEditor_WaitEditFinish(int param_1);
void CG_SpeakerEditor_RandomEditFinish(int param_1);
void CG_SpeakerEditor_VolumeEditFinish(int param_1);
void CG_SpeakerEditor_RangeEditFinish(int param_1);
uint32_t CG_SpeakerEditor_NoiseEdit_KeyDown(int param_1,uint param_2);
uint32_t CG_SpeakerEditor_Looped_KeyUp(int param_1,int param_2);
uint32_t CG_SpeakerEditor_Broadcast_KeyUp(int param_1,int param_2);
uint32_t CG_SpeakerEditor_Cancel_KeyUp(int param_1,int param_2);
void CG_RenderScriptSpeakers(void);
void CG_UpdateBufferedSoundScripts(void);
uint32_t CG_SaveSpeakersToScript(void);
uint32_t CG_SpeakerEditor_Ok_KeyUp(int param_1,int param_2);
uint32_t CG_SpeakerEditor_Delete_KeyUp(int param_1,int param_2);
void CG_SetViewanglesForSpeakerEditor(void);
void CG_GetStrFromStrArray(char *param_1,int param_2);
void CG_SpeakerEditorDraw(void);
void CG_SpeakerEditor_KeyHandling(int param_1,int param_2);
void CG_SpeakerEditorMouseMove_Handling(int param_1,int param_2);
void CG_ActivateEditSoundMode(void);
void CG_DeActivateEditSoundMode(void);
void CG_ModifyEditSpeaker(void);
void CG_UndoEditSpeaker(void);
void CG_ToggleActiveOnScriptSpeaker(uint32_t param_1);
void CG_UnsetActiveOnScriptSpeaker(uint32_t param_1);
void CG_SetActiveOnScriptSpeaker(uint32_t param_1);
uint32_t CG_SpawnString(char *param_1,uint32_t param_2,uint32_t *param_3);
int CG_SpawnFloat(char *param_1,char *param_2,float *param_3);
int CG_SpawnInt(char *param_1,char *param_2,long *param_3);
int CG_SpawnVector(char *param_1,uint32_t param_2,int param_3);
int CG_SpawnVector2D(char *param_1,uint32_t param_2,int param_3);
void CG_LoadRankIcons(void);
void CG_ClearTrails(void);
int * CG_SpawnTrailJunc(int *param_1);
void CG_FreeTrailJunc(int *param_1);
void CG_KillTrail(uint32_t *param_1);
void CG_TestModel_f(void);
void CG_TestGun_f(void);
void CG_TestModelNextFrame_f(void);
void CG_TestModelPrevFrame_f(void);
void CG_TestModelNextSkin_f(void);
void CG_TestModelPrevSkin_f(void);
void CG_Letterbox(float param_1,float param_2,int param_3);
void CG_OffsetThirdPersonView(void);
void CG_KickAngles(void);
void CG_ZoomIn_f(void);
void CG_ZoomOut_f(void);
void CG_Zoom(void);
bool CG_CalcFov(void);
void CG_CalcViewValues(void);
char * CG_MustParse(uint32_t param_1,uint32_t param_2);
void CG_SetupFrustum(void);
bool CG_CullPoint(float *param_1);
bool CG_CullPointAndRadius(float *param_1,float param_2);
void CG_PanzerFaustEjectBrass(int param_1);
void CG_CalculateWeaponPosition(float *param_1,float *param_2);
void CG_RocketTrail(int param_1);
void CG_DynamiteTrail(int param_1);
void CG_GrenadeTrail(int param_1);
uint32_t CG_RW_ParseError(uint32_t param_1,char *param_2);
void CG_PyroSmokeTrail(uint32_t *param_1);
void CG_MachineGunEjectBrassNew(int param_1);
void CG_MachineGunEjectBrass(int param_1);
void CG_GetWindVector(float *param_1);
void CG_RegisterItemVisuals(int param_1);
uint64_t CG_GetPartFramesFromWeap(int param_1,int param_2,int param_3,int param_4,int param_5);
void CG_ClearWeapLerpFrame(int param_1,uint32_t *param_2,uint param_3);
void CG_SetSniperZoom(int param_1,int param_2);
void CG_FinishWeaponChange(int param_1,int param_2);
void CG_AltWeapon_f(void);
void CG_NextWeap(int param_1);
void CG_PrevWeap(int param_1);
void CG_LastWeaponUsed_f(void);
void CG_NextWeaponInBank_f(void);
void CG_PrevWeaponInBank_f(void);
void CG_NextWeapon_f(void);
void CG_PrevWeapon_f(void);
void CG_OutOfAmmoChange(int param_1);
void CG_MG42EFX(int *param_1);
void CG_MortarEFX(int param_1);
void CG_SpawnTracer(int param_1,float *param_2,float *param_3);
uint32_t CG_CalcMuzzlePoint(int param_1,float *param_2);
void CG_createStatsWindow(void);
void CG_windowInit(void);
void CG_windowReset(uint32_t *param_1,int param_2,int param_3);
uint8_t * CG_windowAlloc(int param_1,int param_2);
void CG_windowFree(uint8_t *param_1);
void CG_windowCleanup(void);
void CG_demoAviFPSDraw(void);
void CG_demoTimescaleDraw(void);
void CG_windowNormalizeOnText(int param_1);
void CG_windowDraw(void);
void CG_printWindow(uint32_t param_1);
void CG_initStrings(void);
uint32_t CG_addString(int param_1,uint32_t param_2);
void CG_removeStrings(int param_1);
void CG_UpdateSvCvars(void);
void CG_Debreifing2_Awards_Parse(void);
void CG_Debreifing2_Awards_Draw(int param_1);
void CG_UpdateClassesMaxHP(void);

#endif

