#ifndef CGAME_UI_H
#define CGAME_UI_H

/* HUD, menus, scoreboards and drawing */

#include "nitmod_types.h"
#include "nitmod_globals.h"

void CG_DrawGrid_constprop_8(int param_1,float param_2,float param_3,float param_4,float param_5);
int CG_DrawSpawnPointInfo_constprop_5(int param_1,int param_2,int param_3,int param_4,int *param_5);
void CG_DrawExpandedAutoMap(void);
void CG_DrawAutoMap(void);
void CG_LimboMenu_f(void);
void CG_Debriefing_ChatEdit_Draw(int param_1);
void CG_Debriefing_PlayerTime_Draw(int param_1);
void CG_Debriefing2TeamSkillHeaders_Draw(int param_1);
void CG_DebriefingPlayerWeaponStats_Draw(int param_1);
void CG_Debriefing_ChatBox_Draw(int param_1);
void CG_Debriefing_PlayerHitReg_Draw(int param_1);
void CG_DebriefingPlayerList_Draw(int param_1);
void CG_DebriefingXPHeader_Draw(uint32_t param_1);
uint32_t CG_Debriefing_QCButton_KeyDown(uint32_t param_1,int param_2);
void CG_Debriefing_ChatEditFinish(int param_1);
uint32_t CG_Debriefing_NextButton_KeyDown(uint32_t param_1,int param_2);
uint32_t CG_Debriefing2_Maps_KeyDown(int param_1,int param_2);
uint32_t CG_Debriefing_ReadyButton_KeyDown(uint32_t param_1,int param_2);
uint32_t CG_Debriefing_Scrollbar_KeyUp(int param_1,int param_2);
uint32_t CG_Debriefing_ChatButton_KeyDown(uint32_t param_1,int param_2);
uint32_t CG_DebriefingPlayerList_KeyDown(uint32_t param_1,int param_2);
void CG_Debriefing_PlayerName_Draw(int param_1);
void CG_Debriefing_PlayerRank_Draw(int param_1);
void CG_Debriefing_PlayerACC_Draw(int param_1);
void CG_Debriefing_PlayerXP_Draw(int param_1);
void CG_DebriefingTitle_Draw(int param_1);
void CG_Debriefing_PlayerMedals_Draw(int param_1);
void CG_Debriefing_NextButton_Draw(int param_1);
void CG_Debriefing_ChatButton_Draw(int param_1);
void CG_Debriefing_ReadyButton_Draw(int param_1);
void CG_Debriefing_PlayerSkills_Draw(int param_1);
void CG_Debriefing_Startup(void);
void CG_Debriefing_Shutdown(void);
void CG_Debriefing_InfoRequests(void);
uint32_t CG_Debriefing_Draw(void);
int CG_Debriefing_GetNextWeaponStat(int param_1);
void CG_Debriefing_TimeToString(float param_1);
char * CG_Debriefing_FullRankNameForClientInfo(int param_1);
uint8_t * CG_Debriefing_RankNameForClientInfo(int param_1);
void CG_Debriefing_ParseWeaponAccuracies(void);
void CG_Debriefing_ParsePlayerKillsDeaths(void);
void CG_Debriefing_ParseWeaponStats(void);
void CG_Debriefing_ParseHitRegions(void);
uint32_t CG_Debriefing_ServerCommand(uint32_t param_1);
uint32_t CG_Debriefing_ScrollGetMax(int param_1);
int CG_Debriefing_ScrollGetCount(int param_1);
uint32_t CG_Debriefing_ScrollGetOffset(int param_1);
void CG_Debriefing_ScrollSetOffset(int param_1,uint32_t param_2);
int CG_Debriefing_ScrollGetBarRect(int param_1,uint32_t *param_2);
void CG_Debriefing_ScrollCheckOffset(int param_1);
void CG_Debriefing_Scrollbar_Draw(int param_1);
uint32_t CG_Debriefing_Scrollbar_KeyDown(int param_1,int param_2);
void CG_Debriefing_MouseEvent(int param_1,int param_2);
void CG_Debriefing_KeyEvent(int param_1,int param_2);
int CG_Debriefing_GetSelectedClientInfo(void);
long double CG_Debriefing_CalcCampaignProgress(void);
int CG_Debriefing_FindWinningTeamForMap(void);
uint32_t CG_Debriefing_FindWinningTeamForPos(int param_1);
void CG_Debriefing2TeamSkillXP_Draw(int param_1);
uint32_t CG_Debriefing_FindOveralWinningTeam(void);
int CG_Debriefing_FindWinningTeam(void);
void CG_DrawFlashFade(void);
void CG_DrawBinocReticle(void);
void CG_DrawAnnouncement(void);
void CG_DrawObjectiveInfo(void);
int CG_Text_Width_Ext_constprop_17(byte *param_1,int param_2,float param_3);
void CG_DrawCrosshair(void);
void CG_DrawBannerPrint(void);
void CG_DrawCenterString(void);
void CG_DrawDemoRecording_part_3(void);
void CG_DrawPlayerStatus(void);
void CG_Text_SetActiveFont(uint32_t param_1);
int CG_Text_Width_Ext(byte *param_1,float param_2,size_t param_3,int param_4);
int CG_Text_Width(byte *param_1,float param_2,size_t param_3);
int CG_Text_Height_Ext(byte *param_1,float param_2,size_t param_3,int param_4);
int CG_Text_Height(byte *param_1,float param_2,size_t param_3);
void CG_Text_Paint_Centred_Ext(void);
long double CG_DrawTime(float param_1,int param_2);
void CG_DrawDisconnect(uint32_t param_1);
long double CG_DrawLagometer(float param_1);
void CG_DrawUpperRight(void);
void CG_DrawLivesLeft(void);
void CG_DrawCrosshairNames(void);
void CG_DrawTimedMenus(void);
void CG_DrawSkillLevels(void);
void CG_DrawActivePowerups(void);
void CG_DrawDemoRecording(void);
void CG_DrawOnScreenNames(void);
void CG_DrawMiscGamemodels(void);
void CG_DrawMissileCamera(float *param_1);
void CG_DrawAnnouncer(void);
void CG_DrawActive(int param_1);
void CG_DrawStringExt3_constprop_0(int param_1,int param_2,byte *param_3,uint32_t *param_4);
void CG_HudPlacement(uint32_t param_1);
void CG_FillRect(float param_1,float param_2,float param_3,float param_4,uint32_t param_5);
void CG_DrawSides(float param_1,float param_2,float param_3,float param_4,float param_5);
void CG_DrawTopBottom(float param_1,float param_2,float param_3,float param_4,float param_5);
void CG_DrawSides_NoScale(float param_1,float param_2,float param_3,float param_4,float param_5);
void CG_DrawTopBottom_NoScale(float param_1,float param_2,float param_3,float param_4,float param_5);
void CG_DrawPic(float param_1,float param_2,float param_3,float param_4,uint32_t param_5);
void CG_DrawChar(int param_1,int param_2,int param_3,int param_4,uint param_5);
void CG_DrawChar2(int param_1,int param_2,int param_3,int param_4,uint param_5);
void CG_DrawStringExt2(void);
void CG_DrawBigString(uint32_t param_1,uint32_t param_2,uint32_t param_3,uint32_t param_4);
void CG_DrawBigString2(uint32_t param_1,uint32_t param_2,uint32_t param_3,uint32_t param_4);
void CG_DrawSmallString(int param_1,int param_2,byte *param_3,uint32_t param_4);
void CG_DrawSmallStringColor(int param_1,int param_2,byte *param_3,uint32_t param_4);
void CG_DrawTinyStringColor(int param_1,int param_2,byte *param_3,uint32_t param_4);
int CG_DrawStrlen(char *param_1);
int CG_DrawMineMarkerFlag_isra_0(int param_1,int param_2,uint32_t param_3,uint32_t *param_4);
void CG_DrawFireTeamOverlay(float *param_1);
void CG_DrawFireteamsByTeam(int param_1,int param_2);
void CG_DrawPlayerSF(int param_1,int *param_2);
void CG_DrawPlayerNF(int param_1,int *param_2);
void CG_DrawInformation(uint32_t param_1);
void CG_DrawOverlays(void);
void CG_LimboPanelRenderText_NoLMS(uint32_t param_1);
void CG_LimboPanelRenderText_SkillsText(uint32_t param_1);
void CG_LimboPanel_RenderObjectiveBack(int param_1);
void CG_LimboPanel_Filter_Draw(int param_1);
void CG_LimboPanel_RenderMedal(int param_1);
void CG_LimboPanel_RenderSkillIcon(int param_1);
void CG_LimboPanel_NameEditFinish(int param_1);
void CG_LimboPanel_RenderTeamButton(int param_1);
void CG_LimboPanel_ClassBar_Draw(int param_1);
void CG_LimboPanel_RenderCommandMap(int param_1);
uint32_t CG_LimboPanel_PlusButton_KeyDown(uint32_t param_1,int param_2);
uint32_t CG_LimboPanel_MinusButton_KeyDown(uint32_t param_1,int param_2);
uint32_t CG_LimboPanel_Filter_KeyDown(int param_1,int param_2);
uint32_t CG_LimboPanel_BriefingButton_KeyDown(uint32_t param_1,int param_2);
void CG_LimboPanel_BriefingButton_Draw(int param_1);
uint32_t CG_LimboPanel_CancelButton_KeyDown(uint32_t param_1,int param_2);
void CG_LimboPanel_RenderHead(int param_1);
void CG_LimboPanel_WeaponLights(int param_1);
uint32_t CG_LimboPanel_WeaponPanel_KeyDown(int param_1,int param_2);
void CG_LimboPanel_RenderLight(int param_1);
uint32_t CG_LimboPanel_ObjectiveText_KeyDown(int param_1,int param_2);
void CG_LimboPanel_Border_Draw(int param_1);
void CG_LimboPanel_RenderObjectiveText(int param_1);
long CG_LimboPanel_GetMaxObjectives(void);
bool CG_LimboPanel_RenderLight_GetValue(int param_1);
uint32_t CG_DrawLimboPlayerHead(uint32_t param_1,int param_2);
void CG_DrawBorder(float param_1,float param_2,float param_3,float param_4,int param_5,int param_6);
int CG_LimboPanel_RenderCounter_ValueForButton(int param_1);
uint CG_LimboPanel_RenderCounter(int param_1);
int CG_LimboPanel_RenderCounter_RollTimeForButton(int param_1);
uint32_t CG_LimboPanel_RenderCounter_MaxChangeForButton(int param_1);
char CG_LimboPanel_RenderCounter_NumRollers(int param_1);
uint32_t CG_LimboPanel_RenderCounter_CountsDown(int param_1);
bool CG_LimboPanel_RenderCounter_CountsUp(int param_1);
uint32_t CG_LimboPanel_RenderCounter_StartSet(int param_1);
bool CG_LimboPanel_RenderCounter_IsReversed(int param_1);
void CG_LimboPanel_Init(void);
uint32_t CG_LimboPanel_Draw(void);
void CG_LimboPanel_KeyHandling(int param_1,int param_2);
uint32_t CG_LimboPanel_GetTeam(void);
int CG_LimboPanel_GetRealTeam(void);
uint32_t CG_LimboPanel_GetClass(void);
void CG_LimboPanel_GetCharacter(void);
void CG_LimboPanel_GetPlayerClass(void);
void CG_LimboPanel_SetSelectedWeaponNumForSlot(int param_1,uint32_t param_2);
void CG_LimboPanel_RequestObjective(void);
uint64_t CG_LimboPanel_ClassCount(int param_1);
uint CG_LimboPanel_TeamCount(int param_1);
bool CG_LimboPanel_ClassIsDisabled(int param_1);
void CG_LimboPanel_RenderClassButton(int param_1);
bool CG_LimboPanel_RealWeaponIsDisabled(int param_1);
int CG_LimboPanel_WeaponCount_ForSlot(int param_1);
void CG_LimboPanel_WeaponIsDisabled(void);
uint32_t CG_LimboPanel_GetSelectedWeaponNum(void);
int CG_LimboPanel_GetWeaponForNumber(int param_1,int param_2,int param_3);
int CG_LimboPanel_WeaponCount(void);
void CG_LimboPanel_SendSetupMsg(int param_1);
uint32_t CG_LimboPanel_OkButton_KeyDown(uint32_t param_1,int param_2);
int CG_LimboPanel_GetSelectedWeaponForSlot(int param_1);
int CG_LimboPanel_GetSelectedWeapon(void);
uint32_t CG_LimboPanel_WeaponLights_KeyDown(int param_1,int param_2);
uint32_t CG_LimboPanel_TeamButton_KeyDown(int param_1,int param_2);
void CG_LimboPanel_GetSelectedWeaponStat(void);
void CG_LimboPanel_RequestWeaponStats(void);
uint32_t CG_LimboPanel_ClassButton_KeyDown(int param_1,int param_2);
void CG_LimboPanel_Setup(void);
void CG_LimboPanel_SetSelectedWeaponNum(int param_1);
void CG_LimboPanel_WeaponPanel(int param_1);
uint32_t CG_LimboPanel_WeaponPanel_KeyUp(int param_1,int param_2);
int CG_LimboPanel_GetWeaponNumberForPos(int param_1);
void CG_LoadPanel_RenderMissionDescriptionText(int param_1);
void CG_LoadPanel_RenderCampaignNameText(int param_1);
void CG_LoadPanel_RenderCampaignTypeText(int param_1);
char * CG_LoadPanel_GameTypeName(uint32_t param_1);
void CG_DrawConnectScreen(int param_1);
void CG_LoadPanel_KeyHandling(uint32_t param_1,uint32_t param_2);
uint32_t CG_LoadPanel_ContinueButtonKeyDown(uint32_t param_1,int param_2);
void CG_DrawCinematic(uint32_t param_1,float param_2,float param_3,float param_4,float param_5);
void jP_SetHUDColors(void);
void CG_DrawPlayerWeaponIcon(float *param_1,uint32_t param_2,int param_3,uint32_t *param_4);
void CG_DrawCursorhint(float *param_1);
void CG_DrawWeapStability(uint32_t *param_1);
void CG_DrawWeapHeat(uint32_t *param_1);
void CG_DrawPMItems(void);
void CG_DrawPMItemsBig(void);
void WM_DrawClientScore_Small_isra_1(int param_1,int param_2,int *param_3,float param_4,int param_5);
void WM_TimeToString(float param_1);
uint32_t cf_draw(float param_1,float param_2,uint32_t param_3,int param_4);
int WM_DrawObjectives(int param_1,int param_2,int param_3);
int WM_TeamScoreboard(int param_1,int param_2,int param_3,float param_4,int param_5,int param_6);
uint32_t CG_DrawScoreboard(void);
void CG_DrawSkyBoxPortal_part_0(int param_1);
uint32_t CG_DrawSkyBoxPortal(uint32_t param_1);
void CG_DrawActiveFrame(int param_1,int param_2,int param_3);
void CG_DrawHitBoxOnHit_part_11(uint32_t *param_1);
void CG_DrawHitBoxOnHit(int *param_1);
void CG_DrawTracer(float *param_1,float *param_2);
void Script_SetTeamColor(int param_1);
void Script_CheckAutoUpdate(void);
void Script_GetAutoUpdate(void);
void Script_Abort(uint32_t param_1,uint32_t *param_2);
uint32_t ItemParse_decoration(int param_1);
uint32_t ItemParse_textasint(int param_1);
uint32_t ItemParse_textasfloat(int param_1);
uint32_t ItemParse_wrapped(int param_1);
uint32_t ItemParse_autowrapped(int param_1);
uint32_t ItemParse_horizontalscroll(int param_1);
uint32_t ItemParse_noToggle(int param_1);
uint32_t MenuParse_popup(int param_1);
uint32_t MenuParse_outOfBounds(int param_1);
uint32_t MenuParse_drawAlwaysOnTop(int param_1);
uint32_t MenuParse_modal(int param_1);
void Scroll_Slider_ThumbFunc(int param_1);
bool ItemParse_name(int param_1,uint32_t param_2);
bool ItemParse_focusSound(int param_1,uint32_t param_2);
bool ItemParse_text(int param_1,uint32_t param_2);
bool ItemParse_group(int param_1,uint32_t param_2);
bool ItemParse_asset_shader(int param_1,uint32_t param_2);
bool ItemParse_background(int param_1,uint32_t param_2);
bool ItemParse_cinematic(int param_1,uint32_t param_2);
bool ItemParse_cvarTest(int param_1,uint32_t param_2);
bool MenuParse_background(int param_1,uint32_t param_2);
bool MenuParse_cinematic(int param_1,uint32_t param_2);
bool MenuParse_soundLoop(int param_1,uint32_t param_2);
bool ItemParse_feeder(int param_1,uint32_t param_2);
bool ItemParse_bordersize(int param_1,uint32_t param_2);
bool ItemParse_textalignx(int param_1,uint32_t param_2);
bool ItemParse_textaligny(int param_1,uint32_t param_2);
bool ItemParse_textscale(int param_1,uint32_t param_2);
uint32_t ItemParse_backcolor(int param_1,uint32_t param_2);
uint32_t ItemParse_forecolor(int param_1,uint32_t param_2);
uint32_t ItemParse_bordercolor(int param_1,uint32_t param_2);
bool ItemParse_special(int param_1,uint32_t param_2);
bool MenuParse_borderSize(int param_1,uint32_t param_2);
uint32_t MenuParse_backcolor(int param_1,uint32_t param_2);
uint32_t MenuParse_forecolor(int param_1,uint32_t param_2);
uint32_t MenuParse_bordercolor(int param_1,uint32_t param_2);
uint32_t MenuParse_focuscolor(int param_1,uint32_t param_2);
uint32_t MenuParse_disablecolor(int param_1,uint32_t param_2);
bool MenuParse_fadeClamp(int param_1,uint32_t param_2);
bool MenuParse_fadeAmount(int param_1,uint32_t param_2);
uint32_t ItemParse_origin(int param_1,uint32_t param_2);
bool ItemParse_style(int param_1,uint32_t param_2);
bool ItemParse_bitflag(int param_1,uint32_t param_2);
bool ItemParse_border(int param_1,uint32_t param_2);
uint32_t ItemParse_visible(int param_1,uint32_t param_2);
bool ItemParse_ownerdraw(int param_1,uint32_t param_2);
bool ItemParse_align(int param_1,uint32_t param_2);
bool ItemParse_textalign(int param_1,uint32_t param_2);
bool ItemParse_textstyle(int param_1,uint32_t param_2);
bool ItemParse_textfont(int param_1,uint32_t param_2);
bool ItemParse_ownerdrawFlag(int param_1,uint32_t param_2);
void ItemParse_settingDisabled(int param_1,uint32_t param_2);
void ItemParse_settingEnabled(int param_1,uint32_t param_2);
void ItemParse_voteFlag(int param_1,uint32_t param_2);
bool MenuParse_fullscreen(int param_1,uint32_t param_2);
bool MenuParse_style(int param_1,uint32_t param_2);
uint32_t MenuParse_visible(int param_1,uint32_t param_2);
bool MenuParse_border(int param_1,uint32_t param_2);
bool MenuParse_ownerdrawFlag(int param_1,uint32_t param_2);
bool MenuParse_ownerdraw(int param_1,uint32_t param_2);
bool MenuParse_fadeCycle(int param_1,uint32_t param_2);
bool MenuParse_itemHotkeyMode(int param_1,uint32_t param_2);
bool ItemParse_outlinecolor(int param_1,uint32_t param_2);
bool MenuParse_outlinecolor(int param_1,uint32_t param_2);
uint32_t * Item_CorrectedTextRect(int param_1);
bool MenuParse_name(int param_1,uint32_t param_2);
uint Item_SettingShow_constprop_35(int param_1);
bool Item_SettingShow_constprop_36(int param_1);
bool MenuParse_rect(int param_1,uint32_t param_2);
bool ItemParse_rect(int param_1,uint32_t param_2);
uint32_t Item_ValidateTooltipData_part_24(int param_1);
bool ItemParse_tooltip(int param_1,uint32_t param_2);
bool ItemParse_tooltipalignx(int param_1,uint32_t param_2);
bool ItemParse_tooltipaligny(int param_1,uint32_t param_2);
uint32_t ItemParse_addColorRangeRel(int param_1,uint32_t param_2);
uint32_t ItemParse_addColorRange(int param_1,uint32_t param_2);
void Script_ExecWolfConfig(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Tooltip_Initialize(int param_1);
void Tooltip_ComputePosition(int param_1);
void Cui_WideRect(float *param_1);
long double Cui_WideX(float param_1);
long double Cui_WideXoffset(void);
uint8_t * UI_Alloc(int param_1);
void Item_ValidateTypeData_part_21(int param_1);
uint32_t ItemParse_asset_model(int param_1,uint32_t param_2);
bool ItemParse_model_origin(int param_1,uint32_t param_2);
bool ItemParse_model_fovx(int param_1,uint32_t param_2);
bool ItemParse_model_fovy(int param_1,uint32_t param_2);
bool ItemParse_model_rotation(int param_1,uint32_t param_2);
bool ItemParse_model_angle(int param_1,uint32_t param_2);
uint32_t ItemParse_model_animplay(int param_1,uint32_t param_2);
uint32_t ItemParse_notselectable(int param_1);
uint32_t ItemParse_type(int param_1,uint32_t param_2);
bool ItemParse_elementwidth(int param_1,uint32_t param_2);
bool ItemParse_elementheight(int param_1,uint32_t param_2);
bool ItemParse_elementtype(int param_1,uint32_t param_2);
uint32_t ItemParse_columns(int param_1,uint32_t param_2);
bool ItemParse_contextMenu(int param_1,uint32_t param_2);
uint32_t ItemParse_cvar(int param_1,uint32_t param_2);
uint32_t ItemParse_maxChars(int param_1,uint32_t param_2);
uint32_t ItemParse_maxPaintChars(int param_1,uint32_t param_2);
bool ItemParse_cvarFloat(int param_1,uint32_t param_2);
void UI_InitMemory(void);
uint32_t UI_OutOfMemory(void);
char * String_Alloc(char *param_1);
bool ItemParse_textfile(int param_1,uint32_t param_2);
uint32_t ItemParse_cvarStrList(int param_1,uint32_t param_2);
uint32_t ItemParse_cvarFloatList(int param_1,uint32_t param_2);
uint32_t ItemParse_cvarListUndefined(int param_1,uint32_t param_2);
void Script_SetAsset(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_ClearCvar(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_SetPlayerModel(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_SetPlayerHead(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_SetBackground(int param_1,uint32_t param_2,uint32_t param_3);
void Script_Exec(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_ExecNOW(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_Play(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_playLooped(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_SetColor(int param_1,uint32_t param_2,uint32_t param_3);
void Script_SetCvar(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_CopyCvar(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_ToggleCvarBit(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Item_RunScript_constprop_37(int param_1,char *param_2);
void Menu_RunCloseScript_part_10(int param_1);
void Script_CloseAllOtherMenus(int param_1);
void Script_CloseAll(void);
void Script_FadeOutMenu(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_FadeInMenu(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void String_Report(void);
uint32_t Float_Parse(uint32_t param_1,float *param_2);
uint32_t Color_Parse(uint32_t param_1,int param_2);
uint32_t Int_Parse(uint32_t param_1,long *param_2);
bool Rect_Parse(uint32_t param_1,float *param_2);
uint32_t String_Parse(uint32_t param_1,uint32_t *param_2);
bool ItemParse_onEsc(int param_1,uint32_t param_2);
bool ItemParse_onEnter(int param_1,uint32_t param_2);
bool ItemParse_onFocus(int param_1,uint32_t param_2);
bool ItemParse_leaveFocus(int param_1,uint32_t param_2);
bool ItemParse_mouseEnter(int param_1,uint32_t param_2);
bool ItemParse_mouseExit(int param_1,uint32_t param_2);
bool ItemParse_mouseEnterText(int param_1,uint32_t param_2);
bool ItemParse_mouseExitText(int param_1,uint32_t param_2);
bool ItemParse_action(int param_1,uint32_t param_2);
bool ItemParse_accept(int param_1,uint32_t param_2);
bool ItemParse_enableCvar(int param_1,uint32_t param_2);
bool ItemParse_disableCvar(int param_1,uint32_t param_2);
bool ItemParse_showCvar(int param_1,uint32_t param_2);
bool ItemParse_hideCvar(int param_1,uint32_t param_2);
bool ItemParse_execKey(int param_1,uint32_t param_2);
bool MenuParse_onOpen(int param_1,uint32_t param_2);
bool MenuParse_onClose(int param_1,uint32_t param_2);
bool MenuParse_onESC(int param_1,uint32_t param_2);
bool MenuParse_onEnter(int param_1,uint32_t param_2);
bool MenuParse_onTimeout(int param_1,uint32_t param_2);
bool MenuParse_execKey(int param_1,uint32_t param_2);
bool MenuParse_execKeyInt(int param_1,uint32_t param_2);
bool ItemParse_doubleClick(int param_1,uint32_t param_2);
void Init_Display(uint32_t param_1);
void GradientBar_Paint(uint32_t *param_1,uint32_t param_2);
void Window_Init(uint16_t *param_1);
void Window_Paint(float *param_1,float param_2,float param_3,float param_4);
void Item_SetScreenCoords(float *param_1,float param_2,float param_3);
void Item_UpdatePosition(float *param_1);
void Menu_UpdatePosition(float *param_1);
void Menu_PostParse(uint32_t *param_1);
int Menu_ClearFocus(int param_1);
void Script_SetFocus(int param_1,uint32_t param_2,uint32_t param_3);
void Script_ClearFocus(void);
void Script_SetMenuFocus(int param_1,uint32_t param_2,uint32_t param_3);
void Script_SetEditFocus(int param_1,uint32_t param_2,uint32_t param_3);
bool IsVisible(uint param_1);
bool Rect_ContainsPoint(float *param_1,float param_2,float param_3);
int Menu_ItemsMatchingGroup(int param_1,char *param_2);
uint32_t Menu_GetMatchingItemByNumber(int param_1,int param_2,char *param_3);
void Script_SetItemColor(int param_1,uint32_t param_2,uint32_t param_3);
void Script_SetMenuItemColor(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_FadeIn(int param_1,uint32_t param_2,uint32_t param_3);
void Script_FadeOut(int param_1,uint32_t param_2,uint32_t param_3);
void Script_Show(int param_1,uint32_t param_2,uint32_t param_3);
void Script_Hide(int param_1,uint32_t param_2,uint32_t param_3);
uint32_t Menu_FindItemByName(int param_1,int param_2);
void Menu_ShowItemByName(uint32_t param_1,uint32_t param_2,int param_3);
void Script_ConditionalHideShow(int param_1,uint32_t param_2,uint32_t param_3);
void Menu_FadeItemByName(uint32_t param_1,uint32_t param_2,int param_3);
uint32_t * Menus_FindByName(uint32_t param_1);
void Menus_CloseAll(void);
void Menu_FadeMenuByName(uint32_t param_1,uint32_t param_2,int param_3);
void Script_Transition(int param_1,uint32_t param_2,uint32_t param_3);
void Script_Orbit(int param_1,uint32_t param_2,uint32_t param_3);
uint32_t Script_CheckProfile(uint32_t param_1);
uint32_t Script_WriteProfile(uint32_t param_1);
void Item_RunScript(int param_1,int *param_2,char *param_3);
void Script_ConditionalScript(uint32_t param_1,uint32_t param_2,uint32_t param_3);
bool Item_EnableShowViaCvar(int param_1,uint param_2);
uint Item_SettingShow(int param_1,int param_2);
uint32_t Item_SetFocus(int param_1,float param_2,float param_3);
int Item_ListBox_MaxScroll(int param_1);
int Item_ListBox_ThumbPosition(float *param_1);
int Item_ListBox_ThumbDrawPosition(float *param_1);
long double Item_Slider_ThumbPosition(float *param_1);
uint32_t Item_Slider_OverSlider(float *param_1,float param_2,float param_3);
uint32_t Item_ListBox_OverLB(float *param_1,float param_2,float param_3);
void Item_ListBox_MouseEnter(float *param_1,float param_2,float param_3,int param_4);
void Item_MouseEnter(int param_1,float param_2,float param_3);
void Item_MouseLeave(int param_1);
float * Menu_HitTest(int param_1,float param_2,float param_3);
void Item_SetMouseOver(int param_1,int param_2);
uint32_t Item_OwnerDraw_HandleKey(int param_1,uint32_t param_2);
uint32_t Item_CheckBox_HandleKey(float *param_1,int param_2);
uint32_t Item_YesNo_HandleKey(float *param_1,int param_2);
uint32_t Item_Multi_CountSettings(int param_1);
int Item_Multi_FindCvarByValue(int param_1);
char * Item_Multi_Setting(int param_1);
uint32_t Item_Multi_HandleKey(float *param_1,int param_2);
void Item_StartCapture(float *param_1,uint32_t param_2);
void Item_StopCapture(void);
uint32_t Item_Slider_HandleKey(float *param_1,int param_2);
void Item_Action(int param_1);
void Menus_Activate(int param_1);
void Menus_ShowByName(uint32_t param_1);
bool Menus_CaptureFuncActive(void);
int Display_VisibleMenuCount(void);
void Rect_ToWindowCoords(float *param_1,float *param_2);
void Item_SetTextExtents(float *param_1,int *param_2,int *param_3,float param_4);
void Item_TextColor(int param_1,float *param_2);
void Item_Text_AutoWrapped_Paint(float *param_1);
void Item_Text_Wrapped_Paint(int param_1);
void Item_Text_Paint(float *param_1);
void Item_TextField_Paint(float *param_1);
void Item_CheckBox_Paint(float *param_1);
void Item_YesNo_Paint(int param_1);
void Item_Multi_Paint(int param_1);
void Controls_GetConfig(void);
void Controls_SetConfig(int param_1);
void Controls_SetDefaults(int param_1);
int BindingIDFromName(uint32_t param_1);
uint8_t * BindingFromName(uint32_t param_1);
void Item_Slider_Paint(float *param_1);
void Item_Bind_Paint(int param_1);
uint32_t Display_KeyBindPending(void);
uint32_t Item_Bind_HandleKey(float *param_1,uint param_2,int param_3);
void AdjustFrom640(float *param_1,float *param_2,float *param_3,float *param_4);
void Item_Model_Paint(float *param_1);
void Item_Image_Paint(float *param_1);
void Item_ListBox_Paint(float *param_1);
void Item_OwnerDraw_Paint(uint32_t *param_1);
void Item_Paint(float *param_1);
void Menu_Paint_part_20(uint32_t *param_1,int param_2);
void Menu_Init(uint32_t *param_1);
int Menu_GetFocusedItem(int param_1);
uint32_t * Menu_GetFocused(void);
void Menu_SetFeederSelection(uint32_t *param_1,int param_2,int param_3,int param_4);
uint32_t Menus_AnyFullScreenVisible(void);
uint32_t * Menus_ActivateByName(uint32_t param_1,int param_2);
void Menus_OpenByName(uint32_t param_1);
void Script_Open(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Script_ConditionalOpen(uint32_t param_1,uint32_t param_2,uint32_t param_3);
void Menus_CloseByName(uint32_t param_1);
void Script_Close(uint32_t param_1,uint32_t param_2,uint32_t param_3);
uint32_t Item_ListBox_HandleKey(float *param_1,uint param_2,uint32_t param_3,int param_4);
void Scroll_ListBox_ThumbFunc(int *param_1);
void Scroll_ListBox_AutoFunc(int *param_1);
uint32_t Item_HandleKey(float *param_1,uint param_2,int param_3);
void Menu_ScrollFeeder(int param_1,int param_2,int param_3);
void Item_Init(uint16_t *param_1);
void Menu_HandleMouseMove(int param_1,float param_2,float param_3);
uint32_t Menu_SetPrevCursorItem(int param_1);
uint32_t Menu_SetNextCursorItem(int param_1);
bool Item_TextField_HandleKey(int param_1,uint param_2);
void Menu_HandleKey(int param_1,int param_2,int param_3);
void Menus_HandleOOBClick(int param_1,uint32_t param_2,int param_3);
void Menu_Paint(int param_1,int param_2);
void Item_ValidateTypeData(int param_1);
uint32_t Item_ValidateTooltipData(int param_1);
uint KeywordHash_Key(char *param_1);
void KeywordHash_Add(int param_1,uint32_t *param_2);
uint32_t * KeywordHash_Find(int param_1,char *param_2);
void Item_SetupKeywordHash(void);
void String_Init(void);
int Item_Parse(uint32_t param_1,uint32_t param_2);
uint32_t MenuParse_itemDef(int param_1,uint32_t param_2);
void Item_InitControls(int param_1);
void Menu_SetupKeywordHash(void);
int Menu_Parse(uint32_t param_1,uint32_t param_2);
void Menu_New(uint32_t param_1);
uint32_t Menu_Count(void);
uint32_t * Menu_Get(int param_1);
void Menu_PaintAll(void);
void Menu_Reset(void);
uint32_t Display_GetContext(void);
uint32_t * Display_CaptureItem(int param_1,int param_2);
uint32_t Display_MouseMove(float *param_1,int param_2,int param_3);
uint32_t Display_CursorType(int param_1,int param_2);
void Display_HandleKey(uint32_t param_1,uint32_t param_2,int param_3,int param_4);
void Display_CacheAll(void);
void C_PanelButtonsSetup(int *param_1,float param_2);
void WM_DrawClientScoreDM(int param_1,int param_2,int *param_3,uint32_t param_4,float param_5);

#endif

