#ifndef CGAME_BG_H
#define CGAME_BG_H

/* Shared background game logic */

#include "nitmod_types.h"
#include "nitmod_globals.h"

int BG_StringHashValue(char *param_1);
int BG_StringHashValue_Lwr(char *param_1);
void BG_AnimParseError(char *param_1);
void BG_ParseCommands_isra_0(int *param_1,int param_2,int param_3);
int BG_IndexForString_constprop_4(char *param_1,uint32_t *param_2);
int BG_AnimationForString(char *param_1,int param_2);
int BG_IndexForString(char *param_1,uint32_t *param_2,int param_3);
char * BG_CopyStringIntoBuffer(char *param_1,int param_2,uint param_3,int *param_4);
void BG_InitWeaponStrings(void);
void BG_ParseConditionBits(uint32_t param_1,uint32_t param_2,int param_3,uint *param_4);
uint32_t BG_ParseConditions(uint32_t param_1,int *param_2);
void BG_AnimParseAnimScript(int param_1,uint32_t param_2,uint32_t param_3,int param_4);
uint32_t BG_EvaluateConditions(int param_1,int *param_2);
int * BG_FirstValidItem(int param_1,int *param_2);
uint BG_ExecuteCommand(int param_1,int param_2,short *param_3,int param_4,int param_5,int param_6);
uint BG_AnimScriptAnimation(int param_1,int param_2,uint param_3,uint32_t param_4);
uint32_t BG_AnimScriptCannedAnimation(int param_1,int param_2);
uint32_t BG_AnimScriptEvent(int param_1,int param_2,int param_3,uint32_t param_4,uint32_t param_5);
int BG_GetAnimString(int param_1,int param_2);
void BG_UpdateConditionValue(int param_1,int param_2,uint32_t param_3,int param_4);
int BG_GetConditionValue(int param_1,int param_2,int param_3);
uint32_t BG_GetConditionBitFlag(int param_1,int param_2,uint32_t param_3);
void BG_SetConditionBitFlag(int param_1,int param_2,uint32_t param_3);
void BG_ClearConditionBitFlag(int param_1,int param_2,uint32_t param_3);
int BG_GetAnimScriptAnimation(int param_1,int param_2,int param_3,int param_4);
uint32_t BG_GetAnimationForIndex(int param_1,int param_2);
void BG_AnimUpdatePlayerStateConditions(int *param_1);
uint32_t BG_RAG_ParseError(uint32_t param_1,char *param_2);
void BG_ClearAnimationPool(void);
uint32_t BG_R_RegisterAnimationGroup(uint32_t param_1,int param_2);
uint32_t BG_LoadCampaignSave(uint32_t param_1,int *param_2,char *param_3);
uint32_t BG_StoreCampaignSave(uint32_t param_1,uint32_t *param_2,char *param_3);
uint32_t BG_PCF_ParseError(uint32_t param_1,char *param_2);
uint32_t BG_ParseCharacterFile(uint32_t param_1,int param_2);
uint8_t * BG_GetCharacter(int param_1,int param_2);
uint8_t * BG_GetCharacterForPlayerstate(int param_1);
void BG_ClearCharacterPool(void);
uint8_t * BG_FindFreeCharacter(uint32_t param_1);
uint8_t * BG_FindCharacter(uint32_t param_1);
void BG_GetFromTable(int param_1);
int * BG_FindItemForWeapon(int param_1);
int BG_FindClipForWeapon(int param_1);
int BG_FindAmmoForWeapon(int param_1);
uint BG_AkimboFireSequence(int param_1,int param_2,int param_3);
bool BG_IsAkimboWeapon(int param_1);
bool BG_IsAkimboSideArm(int param_1,int param_2);
uint32_t BG_AkimboSidearm(int param_1);
int * BG_FindItem(uint32_t param_1);
int * BG_FindItemForClassName(uint32_t param_1);
uint32_t BG_WeaponInWolfMP(uint32_t param_1);
int BG_GrenadesForClass(int param_1,int param_2);
char BG_GrenadeTypeForTeam(int param_1);
void BG_CalculateSpline_r(int param_1,float *param_2,uint32_t *param_3,float param_4);
bool BG_PlayerTouchesItem(int param_1,int param_2,int param_3);
uint32_t BG_TraverseSpline(float *param_1,int *param_2);
uint32_t BG_RaySphereIntersection(float param_1,float *param_2,float *param_3,float *param_4,float *param_5);
void BG_LinearPathOrigin2(float param_1,int *param_2,float *param_3,float *param_4);
void BG_ComputeSegments(int param_1);
void BG_EvaluateTrajectory(uint32_t *param_1,int param_2,float *param_3,int param_4,int param_5);
void BG_EvaluateTrajectoryDelta(uint32_t *param_1,int param_2,float *param_3);
void BG_GetMarkDir(float *param_1,int param_2,float *param_3);
void BG_AddPredictableEventToPlayerstate(uint32_t param_1,uint32_t param_2,int param_3);
byte BG_GetPrimaryWeaponForPlayerState(int param_1);
void BG_PlayerStateToEntityState(int param_1,uint32_t *param_2,uint32_t param_3,int param_4);
uint BG_DuplicateWeapon(uint param_1);
int * BG_ValidStatWeapon(uint param_1);
int BG_WeaponForMOD(int param_1);
uint8_t * BG_Find_PathCorner(uint32_t param_1);
void BG_AddPathCorner(uint32_t param_1,uint32_t *param_2);
uint8_t * BG_Find_Spline(uint32_t param_1);
uint8_t * BG_AddSplinePath(uint32_t param_1,uint8_t *param_2,uint32_t *param_3);
void BG_AddSplineControl(int param_1,uint32_t param_2);
long double BG_SplineLength(uint32_t param_1);
void BG_BuildSplinePaths(void);
uint8_t * BG_GetSplineData(int param_1,uint *param_2);
int BG_MaxAmmoForWeapon(int param_1,int param_2);
bool BG_AddMagicAmmo(int param_1,int param_2,int param_3,int param_4);
uint BG_CanItemBeGrabbed(int param_1,int param_2,uint32_t param_3);
void BG_CreateRotationMatrix(uint32_t param_1,int param_2);
void BG_TransposeMatrix(uint32_t *param_1,uint32_t *param_2);
void BG_RotatePoint(float *param_1,float *param_2);
void PC_SourceWarning(uint32_t param_1,char *param_2);
void PC_SourceError(uint32_t param_1,char *param_2);
uint32_t PC_Float_Parse(uint32_t param_1,float *param_2);
uint32_t PC_Color_Parse(uint32_t param_1,int param_2);
uint32_t PC_Vec_Parse(uint32_t param_1,int param_2);
uint32_t PC_Int_Parse(uint32_t param_1,int *param_2);
bool PC_String_Parse(uint32_t param_1,uint32_t *param_2);
void PC_String_tolower(char *param_1);
bool PC_String_ParseNoAlloc(uint32_t param_1,uint32_t param_2,uint32_t param_3);
byte BG_simpleWeaponState(int param_1);
int BG_cleanName(char *param_1,char *param_2,int param_3,int param_4);
void BG_setCrosshair(char *param_1,float *param_2,float param_3,uint32_t param_4);
bool BG_isLightWeaponSupportingFastReload(uint param_1);
bool BG_IsScopedWeapon(int param_1);
void BG_InitLocations(float *param_1,float *param_2);
uint8_t * BG_GetLocationString(float *param_1);
void BG_ClipVelocity(float *param_1,float *param_2,float *param_3,float param_4);
bool BG_BBoxCollision(float *param_1,float *param_2,float *param_3,float *param_4);
uint32_t BG_FootstepForSurface(uint param_1);
bool BG_CheckCharge(int *param_1);
uint8_t * BG_GetPlayerClassInfo(int param_1,uint param_2);
uint8_t * BG_PlayerClassForPlayerState(int param_1);
bool BG_ClassHasWeapon(int param_1,int param_2);
bool BG_WeaponIsPrimaryForClassAndTeam(int param_1,int param_2,int param_3);
char * BG_TeamName(int param_1);
char * BG_ShortClassnameForNumber(uint32_t param_1);
char * BG_ClassnameForNumber(uint32_t param_1);
char * BG_ClassnameForNumber_Filename(uint32_t param_1);
uint32_t BG_ClassSkillForClass(uint param_1);
uint32_t BG_SS_ParseError(uint32_t param_1,char *param_2);
void BG_ClearScriptSpeakerPool(void);
uint32_t BG_NumScriptSpeakers(void);
int BG_GetIndexForSpeaker(int param_1);
uint8_t * BG_GetScriptSpeaker(int param_1);
uint32_t BG_SS_DeleteSpeaker(int param_1);
uint32_t BG_SS_StoreSpeaker(int param_1);
uint32_t BG_LoadSpeakerScript(uint32_t param_1);
uint32_t BG_WeapStatForWeapon(int param_1);
uint32_t BG_GetStatGoombas(int param_1);
uint32_t BG_SetStatGoombas(int param_1,uint32_t param_2);
uint32_t BG_GetStatBestSpree(int param_1);
uint32_t BG_SetStatBestSpree(int param_1,uint32_t param_2);
uint32_t BG_GetKillSpree(int param_1);
uint32_t BG_SetKillSpree(int param_1,uint32_t param_2);
uint32_t BG_AdjustKillSpree(int param_1,int param_2);
uint32_t BG_AdjustGoombas(int param_1,int param_2);
uint32_t BG_LoadTraceMap(uint32_t param_1,float *param_2,float *param_3);
long double BG_GetSkyHeightAtPoint(float *param_1);
long double BG_GetSkyGroundHeightAtPoint(float *param_1);
long double BG_GetGroundHeightAtPoint(float *param_1);
uint32_t BG_GetTracemapGroundFloor(void);
uint32_t BG_RW_ParseError(uint32_t param_1,char *param_2);
uint32_t BG_ParseWeaponConfig(uint32_t param_1,int param_2);
uint32_t BG_RW_ParseDefinition(uint32_t param_1,int param_2,int param_3);
uint32_t BG_RegisterWeaponFromWeaponFile(int param_1,uint32_t param_2,int param_3);
void BG_RegisterWeapon(uint param_1,int param_2);
uint BG_IsFile(char *param_1);
uint BG_IsDirectory(char *param_1);
bool BG_DeleteFile(char *param_1);
bool BG_RenameFile(char *param_1,char *param_2);
bool PC_Char_Parse(uint32_t param_1,uint8_t *param_2);
uint32_t PC_Script_Parse(uint32_t param_1,uint32_t *param_2);
bool PC_String_Parse_Trans(uint32_t param_1,uint32_t *param_2);
bool PC_Rect_Parse(uint32_t param_1,int param_2);
longlong BG_CursorInRect(float *param_1);
void BG_PanelButton_RenderEdit(int param_1);
uint32_t BG_PanelButton_EditClick(int param_1,uint param_2);
uint32_t BG_PanelButtonsKeyEvent(uint32_t param_1,int param_2,int *param_3);
void BG_PanelButtonsSetup(uint32_t *param_1);
uint64_t BG_PanelButtonsGetHighlightButton(int *param_1);
void BG_PanelButtonsRender(int *param_1);
void BG_PanelButtonsRender_TextExt(int param_1,uint32_t param_2);
void BG_PanelButtonsRender_Text(int param_1);
void BG_PanelButtonsRender_Img(int param_1);
uint32_t BG_PanelButtons_GetFocusButton(void);
void BG_PanelButtons_SetFocusButton(uint32_t param_1);

#endif

